Groot Documentation
ros-planning/navigation.ros.org pull request #113
Opened 2020-11-12 02:33 UTC by gramss

Spin off from #87

2020-11-13 20:54 UTC, SteveMacenski requested changes
My recommendation is to slow down and think like someone that doesn't know anything about this. It skips over details and actually introducing the concepts you're explaining how to enable. At the point someone clicks on this article, they might not even know what groot is, so explain it to them. They probably have only a cursory understanding of a BT, so show how to edit it and the structure of it.

2020-11-13 20:54 UTC, SteveMacenski commented on configuration/packages/configuring-bt-navigator.rst
> +  int    1666    Port    yes
Remove unit and describe the units in the description area. Lets not change our format for parameter tables unless you'd like to update all of them for all pages ;-)

2020-11-13 20:54 UTC, SteveMacenski commented on configuration/packages/configuring-bt-navigator.rst
> +  int    1666    Port    yes
and optional.

2020-11-13 20:54 UTC, SteveMacenski commented on migration/Foxy.rst
> +Check out our Groot tutorial!
Link to tutorial?

2020-11-13 20:54 UTC, SteveMacenski commented on migration/Foxy.rst
> +Switching bt-xmls on the fly through a new goal request is also included.
This isn't part of groot, remove reference.

2020-11-13 20:54 UTC, SteveMacenski commented on migration/Foxy.rst
> +Live Monitoring and Editing of behavior trees with Groot is now possible.
A little more detail here would be helpful, this doesn't say alot

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +Groot - The fancy BehaviorTree Editor
Make this  title actually descriptive to what you're trying to show people. See other titles, be literal

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +`Recently added <https://github.com/ros-planning/navigation2/pull/1958>`_ to the ROS2 and nav2 implementation of BT.cpp V3 is live monitoring of the current status of the behavior tree.
Remove "recently added", this is going to be around for 10+ years. Leave no reference to time or it will be immediately outdated.

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +With Groot one can visualize, edit and create new behavior trees. Also, complete new custom nodes except control flow nodes can be created using Groot.
Why not control flow nodes? You need to add more here, you can't say something like that and run, some explanation is required.

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +2. Select the `Load palette from file` option  (import button) near the top left corner.
Explain what this doing for users.

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +.. image:: images/Groot/groot_bt_editor.png
You need to have your instructions reference and explain what these figures are. You don't number them or reference them in your instructions for anyone to know what they're supposed to be showing or what steps they belong to -- or what they're trying to communicate.

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +.. image:: images/Groot/bt_w_replanning_and_recovery.png
Same here - these must have some kind of reference in the instructions and a description of what's being shown.

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +  If a tree cannot be visualized because some nodes are missing in the pallet, you might need to visit :ref:`plugins` and search for the plugin that is missing.
What about if someone has their own custom nodes?

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +  Monitoring mode is unaffected from this, as the whole factory with sufficient meta data gets transferred upon connection.
This is the editing section, don't talk about monitoring, move this to the monitoring section.

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +Also, the Groot editor allows for creating new custom nodes via its graphical user interface. This also works with nav2 except custom control nodes.
This section never actaully explains how to edit the BT. Please add more here to actually show now  that you have the BT up, what do you do.

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +Behavior trees of the BT.cpp V3 kind do not automatically include monitoring.
The ZMQ thing is too much information. Just explain what needs to happen and the parameters needed to make it happen

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +After activating ``enable_groot_monitoring``, the zmq network ports for a ``zmq-server`` and ``zmq-publisher`` can be set optionally.
what is "activating" what you mean is setting it to true, so you should say that. Be explicit, this is the official instructions for the feature, don't skip over details.

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +  1. complete :ref:`getting_started` and be able to run the tb3 simulation
Capitalize all first words in bullets

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +Live Monitoring Behavior Trees
You never introduce what this means. Have a introduction paragraph letting people know what you're talking about and enabling.

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +  3. (re-)start the tb3 simulation (optionally with ``headless:=True`` for only RVIZ as GUI)
Remove all things in parentheses. The additional commentary is too much and it makes it hard to read

2020-11-13 20:54 UTC, SteveMacenski commented on tutorials/docs/groot.rst
> +After activating ``enable_groot_monitoring``, the zmq network ports for a ``zmq-server`` and ``zmq-publisher`` can be set optionally.
Is the zmq publisher/server details so important you should talk about them in the first few lines of the section? Perhaps this should be moved to the last thing to mention that you can change these ports optionally but the defaults match the defaults in groot.

2020-12-04 22:36 UTC, SteveMacenski commented
@gramss what's the story here?

2020-12-09 05:03 UTC, gramss commented on configuration/packages/configuring-bt-navigator.rst
> +  int    1666    Port    yes
this is now solved and already merged. Should be removed from this PR now..

2020-12-09 05:07 UTC, gramss commented on configuration/packages/configuring-bt-navigator.rst
> +  int    1666    Port    yes
locally done (as rebased)

2020-12-11 15:14 UTC, gramss commented on tutorials/docs/groot.rst
> +Groot - The fancy BehaviorTree Editor
It's the official subtitle of Groot.. :D But yes. Something more literal is more suitable

2020-12-11 15:15 UTC, gramss commented on tutorials/docs/groot.rst
> +`Recently added <https://github.com/ros-planning/navigation2/pull/1958>`_ to the ROS2 and nav2 implementation of BT.cpp V3 is live monitoring of the current status of the behavior tree.
done

2020-12-11 15:36 UTC, gramss commented on tutorials/docs/groot.rst
> +With Groot one can visualize, edit and create new behavior trees. Also, complete new custom nodes except control flow nodes can be created using Groot.
I'll add a section for creating Custom Nodes with Groot. I do not see any reason why it does not work. I had this information from a readme in nav2 about groot.. Probably outdated.

I tested it and it looks the same as the ones we already have in our big nodes.xml
So no reason why this would not work..

2020-12-12 03:59 UTC, gramss commented on tutorials/docs/groot.rst
> +  3. (re-)start the tb3 simulation (optionally with ``headless:=True`` for only RVIZ as GUI)
done

2020-12-12 03:59 UTC, gramss commented on tutorials/docs/groot.rst
> +Live Monitoring Behavior Trees
I added one

2020-12-12 04:00 UTC, gramss commented on tutorials/docs/groot.rst
> +  1. complete :ref:`getting_started` and be able to run the tb3 simulation
done

2020-12-12 04:00 UTC, gramss commented on tutorials/docs/groot.rst
> +After activating ``enable_groot_monitoring``, the zmq network ports for a ``zmq-server`` and ``zmq-publisher`` can be set optionally.
I hope I have done it to your understanding

2020-12-12 04:00 UTC, gramss commented on tutorials/docs/groot.rst
> +2. Select the `Load palette from file` option  (import button) near the top left corner.
done

2020-12-12 04:01 UTC, gramss commented on tutorials/docs/groot.rst
> +.. image:: images/Groot/groot_bt_editor.png
Took me a while but I think I figured it out how to use figures correctly in rst. I did not find another use of this in the current docs

2020-12-12 04:02 UTC, gramss commented on tutorials/docs/groot.rst
> +  If a tree cannot be visualized because some nodes are missing in the pallet, you might need to visit :ref:`plugins` and search for the plugin that is missing.
I tried to describe this in detail now + altered the section of interest here

2020-12-12 04:03 UTC, gramss commented on tutorials/docs/groot.rst
> +Also, the Groot editor allows for creating new custom nodes via its graphical user interface. This also works with nav2 except custom control nodes.
This is still missing..

2020-12-12 04:05 UTC, gramss commented
Okay.

So I went through all your comments and created a new, more detailed draft.
I just noticed that a section to edit the BT is still missing. This would be good to have it also there.

I'm unsure if this is worthy a gif or just some text describing how to properly interact with the editing interface of Groot.

I'm eager to listen what you think of this new draft.

2020-12-14 21:07 UTC, SteveMacenski commented
> I'm unsure if this is worthy a gif or just some text describing how to properly interact with the editing interface of Groot.

Gifs and images are always good!

>  I just noticed that a section to edit the BT is still missing. This would be good to have it also there.

Agreed, that's a necessary element for a full look at Groot

2020-12-14 22:00 UTC, SteveMacenski requested changes
I stopped reading about half way through, this needs alot of work.

Please, please, please **slow down**. You fail to do alot of basics and just jump into things without ever explaining or introducing them (but then talk at length of things that aren't relevant for groot).

An introduction section should start the document. In this section, we should introduce what we're going to do, why we're doing it, and the tools used to do it. 

Every subsequent section should at **least** have an introduction paragraph explaining what this section is going to do and examples of why we do this. You just jump right into things with no context or explanation. 

Every instruction should have a detailed explanation of what you're doing and why. If you load a palette, the least you should do is explain what a palette is and what it is used for. These are not obvious things.

I think it would help you alot to walk away from this for a few days and then come back with fresh eyes. Imagine you're writing this document for someone that knows nothing about groot, palettes, editing BT files, etc. Introduce it like you'd want someone to explain a new technology to you. 

In other words, slow down and be complete

2021-11-24 18:59 UTC, SteveMacenski commented
Working on bringing this to the documentation today. Closing and will reopen new PR once complete

2021-11-24 18:59 UTC, closed without merging

2021-11-24 19:56 UTC, SteveMacenski commented
https://github.com/ros-planning/navigation.ros.org/pull/238