Transformation and URDF Setup Guides
ros-planning/navigation.ros.org pull request #117
Opened 2020-12-01 07:56 UTC by jd-deleon

Co-authored-by: Fiona Estoperez <f.estoperez@samsung.com>
Co-authored-by: Steve Macenski <stevenmacenski@gmail.com>

2020-12-01 08:03 UTC, jd-deleon commented
Proposing this contribution to address some bullet points in ros-planning/navigation2#1589

2020-12-02 20:42 UTC, SteveMacenski commented
FYI, through our CI, if you go to the "artifacts" tab and then index.html you can get a link to a preview of your changes before deploying to the web to make sure all looks good to you https://529-240847415-gh.circle-artifacts.com/0/html/index.html

2020-12-02 21:29 UTC, SteveMacenski requested changes
Awesome! I think you did a great job especially on the URDF section. There's some clarifications I wanted to make I think aids in understanding and then I think its good to merge!

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +To quickly summarize REP 105, this document specifies the naming conventions and semantic meanings of the different coordinate frames used in ROS. Of interest to this tutorial are the ``base_link``,
"The ``base_link`` is a coordinate frame that is attached to a fixed position on the robot, typically at its main chassis and its rotational center." --> really good, I think from this comment, you can remove the "center of robot" comment from the previous section I marked as not entirely true. This covering that distinction perfectly.

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +To quickly summarize REP 105, this document specifies the naming conventions and semantic meanings of the different coordinate frames used in ROS. Of interest to this tutorial are the ``base_link``,
The odom frame is not world fixed, it is fixed, but not relative to the "world", its relative to the robot's starting position.

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +To quickly summarize REP 105, this document specifies the naming conventions and semantic meanings of the different coordinate frames used in ROS. Of interest to this tutorial are the ``base_link``,
I think the clarification that the `odom` frame is used for locally-consistent representations of distances and the map frame is used for globally-consistent representations of distances.

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +REP 103, on the other hand, discusses some standard units of measure and other related conventions to keep integration issues between different ROS packages to a minimum.
Add "The basic overview is that frames are defined using the right hand rule, with Z up and X forward, and units should be standard SI units."

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +REP 103, on the other hand, discusses some standard units of measure and other related conventions to keep integration issues between different ROS packages to a minimum.
That's pretty much all REP103 says

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +The first transform ``map`` => ``odom`` is usually provided by a different ROS package dealing with localization and mapping such as AMCL. This transform updates live in use so we don't set static va
Add "All ROS complaint SLAM and localization packages will provide you with this transformation automatically on launch."

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +The ``odom`` => ``base_link`` is usually published by our odometry system using sensors such as wheel encoders.
Add "This is typically computed via sensor fusion of odometry sensors (IMU, wheel encoders, VIO, etc) using the robot_localization package."

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +All other statically defined transforms (e.g. ``base_link`` => ``laser_link``, ``base_link`` => ``wheels``, ``wheels`` => ``IMU``, etc) is what we will be talking about for the rest of this guide. Th
"from sensors or other frame of interest", alot of times we make other frames that are convenient to work with.

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +And that's it for this short demo - we were able to successfully publish a transform from ``base_link`` to ``base_laser`` using the tf2 library. Note that we do not recommend using the above demo in
"..discussed in the next tutorial, <link to it by name>."

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +In the last section, we have also explored using the static_transform_publisher of tf2 to publish our transforms. You may use this to set up your transforms for Nav2, but this is generally not the be
same with next, not future, tutorial with a link.

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +And that's it for this short demo - we were able to successfully publish a transform from ``base_link`` to ``base_laser`` using the tf2 library. Note that we do not recommend using the above demo in
"... it is just a quick demo to see tf2 in action. For a real robot system, we would create a URDF file which embeds this information and more about your robot for use of the robot_state_publisher rather than the static_transform_publisher."

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +For this guide, we will be creating the URDF for a simple differential drive robot to give you hands-on experience on working with URDF. We will also setup the robot state publisher and visualize our
Add a sentence about why we're doing this (e.g.  this is needed to represent all the sensor, hardware, and robot transforms of your robot for use in navigation)

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +As discussed in the previous section, one of the requirements for Navigation2 is the  ``base_link`` => ``laser_link`` transformations. This transformation tree can range from a simple tree with only
```suggestion
As discussed in the previous tutorial, one of the requirements for Navigation2 is the transformation from  ``base_link`` to the various sensors and reference frames. This transformation tree can range from a simple tree with only one link from the  ``base_link`` to ``laser_link`` or a tree comprised of multiple sensors located in different locations, each having their own coordinate frame. Creating multiple publishers to handle all of these coordinate frame transformations may become tedious. Therefore, we will be making use of the Robot State Publisher package to publish our transforms. 
```

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +.. warning:: This tutorial was tested and written with ROS2 Foxy. However, we always recommend to use the latest version of ROS2 if possible.
Remove this `warning` block and replace any instances of `foxy` with `<ros2-distro>`. Its what we do in all other docs to keep them independent of version to age better. e.x. `ros-<ros2-distro>-xacro`

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +.. seealso:: If you are new to ROS2 or do not have a working environment yet, then please take some time to properly setup your machine using the resources in the official `ROS2 Installation Document
Remove this block, we can assume they're going through these pages in order and this appeared in the last one

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +.. seealso:: If you are new to ROS2 or do not have a working environment yet, then please take some time to properly setup your machine using the resources in the official `ROS2 Installation Document
(and the prior line makes it clear the assumption is that's already done)

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +Next, create a directory for your project, initialize a ROS2 workspace and give your robot a name. For ours, we'll be calling it ``sam-bot``.
Use only underscores, `sam_bot`. Please update here and anywhere else `-` exists.

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +Next, create a directory for your project, initialize a ROS2 workspace and give your robot a name. For ours, we'll be calling it ``sam-bot``.
call the new package `sam_bot_description` thats the standard ROS package name for URDF files

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +Next, let us define some constants that will be used for different sections of our URDF. Note that we will be using XAcro properties to achieve this.
Please have a short couple of sentences explaining what these are. I think its pretty clear from the code, but its always good to be explicit on each of the values.

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +We will also be defining some of the link's visual properties which can be used by tools such as Gazebo and Rviz to show us a 3D model of our robot. Amongst these properties are `<geometry>` which de
Same here, please go through the code block and explain what's happening a little. I think things to mention
- We're accessing the xacro variables from before to set our robot base size using their names as parameters in `${}`.
- The color will be green-blue because of the color choice 
- Its under the visual tag because this is just visualization parameters, which don't impact collision or physical properties.

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +After defining our base_link, we then add a joint to connect it to ``base_link``. In URDF, a ``joint`` element describes the kinematic and dynamic properties between coordinate frames. For this case,
Please explain your math on the joint Z offset.

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +.. note:: If you do not have colcon set up yet, you may install it through the command ``sudo apt install python3-colcon-common-extensions`` or through your preferred package manager.
You can remove this, this would be covered by a ros 2 setup

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +      default_model_path = os.path.join(pkg_share, 'src/description/sam-bot_description.urdf')
I didn't notice any changes to the cmakelists file, does this install the URDF to be able to do this?

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +  ros2 launch launch/display.launch.py
I think it would be good to use the full syntax, if it works for this demo, like `ros2 launch <pkg-name> <launch-file>` though that may require cmakelists updates to install them

2020-12-02 21:29 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +For now, we will have to stop here since we will need to set up a lot more components to actually start simulating our robot in Gazebo. We will be coming back to this project during the course of the
Add "The only major thing missing from this to work in gazebo is the simulation plugins required to mimic your robot controllers. We will introduce those and add them to this UDRF in the appropriate section."

2020-12-11 22:34 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +Before we begin with this section, there two important ROS REPs which we highly suggest for you to check out. These documents detail some standards set about by the ROS community to ensure proper ope
"There **are** two"

2020-12-16 07:48 UTC, jd-deleon commented on setup_guides/urdf/setup_urdf.rst
> +      default_model_path = os.path.join(pkg_share, 'src/description/sam-bot_description.urdf')
Oh I missed this one., already added snippet in f1acdef

2020-12-16 07:52 UTC, jd-deleon commented
All code review comments have been addressed in the last few commits.

2020-12-16 22:10 UTC, SteveMacenski reviewed
Super great now! Only a couple more updates just to polish it up and we can merge it. Mostly just around making sure we use double "`"'s for code and adding a new image as a demo

2020-12-16 22:10 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +The ``odom`` => ``base_link`` is usually published by our odometry system using sensors such as wheel encoders. This is typically computed via sensor fusion of odometry sensors (IMU, wheel encoders,
```suggestion
The ``odom`` => ``base_link`` is usually published by our odometry system using sensors such as wheel encoders. This is typically computed via sensor fusion of odometry sensors (IMU, wheel encoders, VIO, etc) using the ``robot_localization`` package.
```

2020-12-16 22:10 UTC, SteveMacenski commented on setup_guides/transformation/setup_transforms.rst
> +Transforms in Navigation2
This section seems a little out of order now that I look at it. Looking at this guide (https://555-240847415-gh.circle-artifacts.com/0/html/setup_guides/transformation/setup_transforms.html), we talk about transforms, then this, then finishing the TF example on the original example.

I think it would be good to move this section below the `Static Transform Publisher Demo` section so that we go from transform example -> publisher example -> Nav2 TF uses. So just copy paste this down 1 subsection.

2020-12-16 22:10 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +
Please place the image from slide 20 here https://mirror.umd.edu/roswiki/attachments/Events(2f)PR2BetaTraining/tf.pdf. Its nice to show a visual of what a "real" one of these would look like as example to start.

2020-12-16 22:10 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +Here is a brief discussion on what these properties will represent in our urdf. The ``base_*`` properties all define the size of hte robot's main chassis. The ``wheel_radius`` and ``wheel_width`` def
```suggestion
Here is a brief discussion on what these properties will represent in our urdf. The ``base_*`` properties all define the size of hte robot's main chassis. The ``wheel_radius`` and ``wheel_width`` define the shape of the robot's two back wheels. The ``wheel_ygap`` adjusts the gap between the wheel and the chassis along the y-axis whilst ``wheel_zoff`` and ``wheel_xoff`` position the back wheels along the z-axis and x-axis appropriately. Lastly, the ``caster_xoff`` positions the front caster wheel along the x-axis.
```

2020-12-16 22:10 UTC, SteveMacenski commented on setup_guides/urdf/setup_urdf.rst
> +We will also be defining some of the link's visual properties which can be used by tools such as Gazebo and Rviz to show us a 3D model of our robot. Amongst these properties are `<geometry>` which de
```suggestion
We will also be defining some of the link's visual properties which can be used by tools such as Gazebo and Rviz to show us a 3D model of our robot. Amongst these properties are ``<geometry>`` which describes the link's shape and ``<material>`` which describes it's color.
```

2020-12-17 19:24 UTC, SteveMacenski approved these changes
Awesome work! Ready to merge

2020-12-17 19:25 UTC, merged