Update documentation with SpeedFilter
ros-planning/navigation.ros.org pull request #122
Opened 2020-12-14 15:26 UTC by AlexeyMerzlyakov

This is related to https://github.com/ros-planning/navigation2/pull/2074 documentation update.

2020-12-14 20:54 UTC, SteveMacenski requested changes

2020-12-14 20:54 UTC, SteveMacenski commented on configuration/packages/configuring-controller-server.rst
> +    Speed limiting topic name to subscribe.
Please link against the speed limit layer as the example use of it. Also mention that you can use this without the speed restricted layer as well if you provide an external server to manage.

2020-12-14 20:54 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/speed_filter.rst
> +  double 0.0
Update  to 0.1 with code + nav2 repo yaml file.

2020-12-14 20:54 UTC, SteveMacenski commented on configuration/packages/configuring-controller-server.rst
>      The controller server filters the velocity portion of the odometry messages received before sending them to the controller plugin.
Missing entries into the plugin page for the new plugin and the migration guide for mentioning the new feature.

I'd also recommend adding more description of the feature at the top of the speed limit configuration page. This would be a great place to embed your video of it working. Down the line I want to add a `features` section that will contain more exhaustive info / video demos, but for now, lets make use of the video you made

2020-12-15 15:07 UTC, AlexeyMerzlyakov commented on configuration/packages/costmap-plugins/speed_filter.rst
> +  double 0.0
Done in https://github.com/ros-planning/navigation.ros.org/pull/122/commits/1c5fabfed9ff93beaad1d14a41c72d9adf299d62

2020-12-15 15:08 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-controller-server.rst
> +    Speed limiting topic name to subscribe.
Updated at https://github.com/ros-planning/navigation.ros.org/pull/122/commits/892285a3e3fe772105b48dff86942a69e1ad1a3b#diff-462c370fe5978a55c863868a252754323ca17a9a37e5267483c0fc3a312453dcR146

2020-12-15 15:09 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-controller-server.rst
>      The controller server filters the velocity portion of the odometry messages received before sending them to the controller plugin.
Added in https://github.com/ros-planning/navigation.ros.org/pull/122/commits/892285a3e3fe772105b48dff86942a69e1ad1a3b

2020-12-15 21:21 UTC, SteveMacenski approved these changes
Just need the examples and good to go

2020-12-15 21:21 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/speed_filter.rst
> +    Time with which to post-date the transform that is published, to indicate that this transform is valid into the future. Used when filter mask and current costmap layer are in different frames.
Missing the Example fully-configured XML file at the bottom of this page (e.x. https://navigation.ros.org/configuration/packages/configuring-smac-planner.html#example)  and the keepout page

2020-12-16 12:32 UTC, AlexeyMerzlyakov commented on configuration/packages/costmap-plugins/speed_filter.rst
> +    Time with which to post-date the transform that is published, to indicate that this transform is valid into the future. Used when filter mask and current costmap layer are in different frames.
Good. Added here: https://github.com/ros-planning/navigation.ros.org/pull/122/commits/28705b24eb6a6c82a8fe5062e59ade11d33a6ce8.

2020-12-16 15:22 UTC, SteveMacenski approved these changes

2020-12-16 15:22 UTC, merged