Add tutorial for Speed Filter
ros-planning/navigation.ros.org pull request #124
Opened 2020-12-19 13:37 UTC by AlexeyMerzlyakov

Adding the tutorial for Speed Filter (https://github.com/ros-planning/navigation.ros.org/issues/123 task)

2020-12-19 13:45 UTC, AlexeyMerzlyakov commented
Added the initial version of Speed Filter tutorial. Everything is made, except demonstration video. After all texts will be approved, I will shoot and attach the video in the beginning of this tutorial.

2021-01-04 19:39 UTC, SteveMacenski requested changes

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +As was written in :ref:`concepts`, any Costmap Filter (including Speed Filter) are reading the data marked in a filter mask file. All information about filter masks, their types, detailed structure a
```suggestion
As was written in :ref:`concepts`, any Costmap Filter (including Speed Filter) is reading the data marked in a filter mask file. All information about filter masks, their types, detailed structure and how to make a new one is written in a :ref:`navigation2_with_keepout_filter` tutorial at ``1. Prepare filter masks`` chapter. The principal of drawing the filter mask for Speed Filter is the same as for Keepout Filter (to annotate a map with the requested zones), except that ``OccupancyGrid`` mask values have another meaning: these values are encoded speed limits for the areas corresponding to the cell on map.
```

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +  For speed restriction expressed in a percent, ``speed_limit`` will be used exactly as a percent belonging to ``[0..100]`` range, but not as a share from ``[0.0..1.0]`` range.
```suggestion
  For speed restriction expressed in a percent, ``speed_limit`` will be used exactly as a percent belonging to ``[0..100]`` range, not ``[0.0..1.0]`` range.
```

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +Area "A" is filled with ``40%`` gray color, area "B" - with ``70%`` gray, what should mean that speed restriction will take ``100% - 40% = 60%`` in area "A" and ``100% - 70% = 30%`` in area "B" from
```suggestion
Area "A" is filled with ``40%`` gray color, area "B" - with ``70%`` gray, that means that speed restriction will take ``100% - 40% = 60%`` in area "A" and ``100% - 70% = 30%`` in area "B" from maximum speed value allowed for this robot.
```

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +We will use ``scale`` map mode with no thresholds. In this mode darker colors will have higher ``OccupancyGrid`` values. E.g. for area "B" with ``70%`` of gray ``OccupancyGrid`` data will be equal to
```suggestion
We will use ``scale`` map mode with no thresholds. In this mode darker colors will have higher ``OccupancyGrid`` values. E.g. for area "B" with ``70%`` of gray ``OccupancyGrid`` data will be equal to ``70``. So in order to hit the target, we need to choose ``base = 100.0`` and ``multiplier = -1.0``. This will reverse the scale ``OccupancyGrid`` values to a desired one.
```

You already mentioned in the sentence prior

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +  occupied_thresh: 1.0
are these 2 thresholds even used in this situation? Is it important to change at all?

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +  World map itself and filter mask could have different sizes, origin and resolution which might be useful e.g. for cases when filter mask is covering smaller areas on maps or when one filter mask is
```suggestion
  World map itself and filter mask could have different sizes, origin and resolution which might be useful (e.g. for cases when filter mask is covering smaller areas on maps or when one filter mask is used repeatedly many times, like annotating a speed restricted area for same shape rooms in the hotel). For this case, you need to correct ``resolution`` and ``origin`` fields in YAML as well so that the filter mask is correctly laid on top of the original map. This example shows using the main map as a base, but that is not required.
```

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +  Another important note is that since Costmap2D does not support orientation, the last third "yaw" component of the ``origin`` vector should be equal to zero. For example: ``origin: [1.25, -5.18, 0.
Remove this as a note and add it as a sentence in the yaml file modification section above

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +      topic_name: "/filter_mask"
Lets chose a less generic name than this for the topic, keep in mind this is the tutorial that people will use as a design reference so lets use a topic that's actually indicative of speed filter

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> + - As was described in a previous chapter, ``base`` and ``multiplier`` should be set to ``100.0`` and ``-1.0`` accordingly.
```suggestion
 - As was described in a previous chapter, ``base`` and ``multiplier`` should be set to ``100.0`` and ``-1.0`` accordingly for the purposes of this tutorial example.
```

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +You can place the plugin either in the ``global_costmap`` section in ``nav2_params.yaml`` to have speed restriction mask applied to global costmap or in the ``local_costmap`` to apply speed mask to t
Please be more stern than a recommendation, we do not want anyone to have them in both because it would really mess things up

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +As stated in the `design <https://github.com/ros-planning/navigation2/blob/main/doc/design/CostmapFilters_design.pdf>`_, Speed Filter publishes speed restricting `messages <https://github.com/ros-pla
```suggestion
As stated in the `design <https://github.com/ros-planning/navigation2/blob/main/doc/design/CostmapFilters_design.pdf>`_, Speed Filter publishes speed restricting `messages <https://github.com/ros-planning/navigation2/blob/main/nav2_msgs/msg/SpeedLimit.msg>`_ targeted for a Controller Server so that it could restrict maximum speed of the robot when it needed. Controller Server has a ``speed_limit_topic`` ROS parameter for that, which should be set to the same as in ``speed_filter`` plugin value. This topic in the map server could also be used to any number of other speed-restricted applications beyond the speed limiting zones, such as dynamically adjusting maximum speed by payload mass.
```

2021-01-04 19:39 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +For using Speed Filter with local costmap, use the following configuration:
We should choose one or the other local / global costmap to recommend in the tutorial.

2021-01-12 09:57 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_speed_filter.rst
> +  occupied_thresh: 1.0
Yes, that is because of in the example we want to have 1:1 mask grayscale % -> speed limit % conversion. From the tutorial:
> We will use scale map mode with no thresholds.

This mean, that `occupied_thresh = 1.0` and `free_thresh = 0.0`.

2021-01-12 11:30 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_speed_filter.rst
> +  Another important note is that since Costmap2D does not support orientation, the last third "yaw" component of the ``origin`` vector should be equal to zero. For example: ``origin: [1.25, -5.18, 0.
Moved in https://github.com/ros-planning/navigation.ros.org/pull/124/commits/0ca276abe001d1fddab1d0caf89e8a9d15a95f5c#diff-8e354ab7d89ece0f0ce8893b7a0ac5fd4a8c11335c98fd9073499bb896162d95R93

2021-01-12 11:38 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_speed_filter.rst
> +      topic_name: "/filter_mask"
Updated to `/speed_filter_mask` in https://github.com/ros-planning/navigation.ros.org/commit/0ca276abe001d1fddab1d0caf89e8a9d15a95f5c#diff-8e354ab7d89ece0f0ce8893b7a0ac5fd4a8c11335c98fd9073499bb896162d95L226.
Plus updated in the same way for the Keepout tutorial: https://github.com/ros-planning/navigation.ros.org/commit/0ca276abe001d1fddab1d0caf89e8a9d15a95f5c#diff-9de6c0db49184c10da140edc0e8a0b610ce2186d7c72119697d77b581184d93cL208.

Also, updated the tutorials repo accordingly to fit the documentation:
https://github.com/ros-planning/navigation2_tutorials/pull/18/commits/284e4bed38804d582b479dc4b4a1fc008f519921

One thing was untouched - is a demo videos for Keepout and Speed filter. I do not think that to re-take whole video only because of parameter name change is a reasonable idea. However, correct me if I'm wrong.

2021-01-12 11:41 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_speed_filter.rst
> +You can place the plugin either in the ``global_costmap`` section in ``nav2_params.yaml`` to have speed restriction mask applied to global costmap or in the ``local_costmap`` to apply speed mask to t
This was changed to ban starting from https://github.com/ros-planning/navigation.ros.org/pull/124/commits/0ca276abe001d1fddab1d0caf89e8a9d15a95f5c#diff-8e354ab7d89ece0f0ce8893b7a0ac5fd4a8c11335c98fd9073499bb896162d95L265

2021-01-12 11:44 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_speed_filter.rst
> +For using Speed Filter with local costmap, use the following configuration:
Fixed stating from https://github.com/ros-planning/navigation.ros.org/commit/0ca276abe001d1fddab1d0caf89e8a9d15a95f5c#diff-8e354ab7d89ece0f0ce8893b7a0ac5fd4a8c11335c98fd9073499bb896162d95L269

Also, arranged some sentences there to make the narration more consistent:
https://github.com/ros-planning/navigation.ros.org/pull/124/commits/0ca276abe001d1fddab1d0caf89e8a9d15a95f5c#diff-8e354ab7d89ece0f0ce8893b7a0ac5fd4a8c11335c98fd9073499bb896162d95L267
->
https://github.com/ros-planning/navigation.ros.org/pull/124/commits/0ca276abe001d1fddab1d0caf89e8a9d15a95f5c#diff-8e354ab7d89ece0f0ce8893b7a0ac5fd4a8c11335c98fd9073499bb896162d95R279

2021-01-13 18:34 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +  occupied_thresh: 1.0
That should be made really clear why you're doing this and that its important, I would have just scanned right through that without thinking that it didn't apply to this as much.

2021-01-13 18:34 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +      topic_name: "/filter_mask"
yeah, don't update a video for small details.

2021-01-13 19:05 UTC, SteveMacenski approved these changes
Just that one other item but otherwise no other review comments

2021-01-18 16:33 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_speed_filter.rst
> +  occupied_thresh: 1.0
Added a sentence about thresholds choice in https://github.com/ros-planning/navigation.ros.org/pull/124/commits/26a9ceea8da06b9bdd8e5a00694e35ce46add883

2021-01-19 19:21 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_speed_filter.rst
> +We will use ``scale`` map mode with no thresholds. In this mode darker colors will have higher ``OccupancyGrid`` values. E.g. for area "B" with ``70%`` of gray ``OccupancyGrid`` data will be equal to
```suggestion
We will use ``scale`` map mode with no thresholds. In this mode darker colors will have higher ``OccupancyGrid`` values. E.g. for area "B" with ``70%`` of gray ``OccupancyGrid`` data will be equal to ``70``. So in order to hit the target, we need to choose ``base = 100.0`` and ``multiplier = -1.0``. This will reverse the scale ``OccupancyGrid`` values to a desired one. No thresholds (``free_thresh`` ``occupied_thresh``) were chosen for the convenience in the ``yaml``  file: to have 1:1 full range conversion of lightness value from filter mask -> to speed restriction percent.
```

2021-01-19 19:21 UTC, SteveMacenski reviewed
Make this one clarification and LGTM to merge

2021-01-20 17:28 UTC, SteveMacenski approved these changes

2021-01-20 17:28 UTC, merged