initial work to add documentation of GPS WPF
ros-planning/navigation.ros.org pull request #129
Opened 2021-01-05 05:07 UTC by jediofgever

Related to https://github.com/ros-planning/navigation.ros.org/issues/127

2021-01-05 19:33 UTC, SteveMacenski commented
You could skip the tutorial for the case of just the core things needed for the documentation of the PR. We could later add the tutorial so that this isn't blocking.

Or we could do it here too, it's up to you :smile:

2021-01-25 20:06 UTC, SteveMacenski requested changes
Good first run at the tutorial, but it needs work. 
- Ordering needs some work to get across the GPS navigation points first and very clearly before we discuss the specific implementation of it using a waypoint follower
- Typos and missing renderings of code blocks - if you have CI build, you can go to circle -> artifacts ->html/index.html to see your rendered version. You can also compile locally. 
- Generally more discussion required on topics

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +The action client node then can read this waypoints in yaml file and go through them. Assuming that you have ``sensor_msgs::msg::NavSatFix`` message type available under /gps/fix topic and ``sensor_m
"collector" - also link to that

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +The action client node then can read this waypoints in yaml file and go through them. Assuming that you have ``sensor_msgs::msg::NavSatFix`` message type available under /gps/fix topic and ``sensor_m
"collect"

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +how the IMU should report the data at `Robot Localization <http://docs.ros.org/en/melodic/api/robot_localization/html/preparing_sensor_data.html#imu>`_. For the orientation, only yaw angle is our con
```suggestion
how the IMU should report the data at `Robot Localization <http://docs.ros.org/en/melodic/api/robot_localization/html/preparing_sensor_data.html#imu>`_. 
```

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +``gps_waypoint_collector.launh.py`` in ``nav2_gps_waypoint_follower_demo`` ;
"launch"

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +                              {'yaml_file_out': "/home/user_name/collected_points.yaml"}]  #change this according to your home dir
```suggestion
                              {'yaml_file_out': "/path/to/collected_points.yaml"}]   # change this to desired location
```

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +remap your topics accordingly.
Delete this

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +frequency parameter will determine density of collected points. Also do not forget to replace your user name in the path given to yaml file.
code block params

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +frequency parameter will determine density of collected points. Also do not forget to replace your user name in the path given to yaml file.
These also don't all need to be single paragraphs, please combine more of these sentences into structure.

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +.. code-block:: bash
None of these code blocks are rendering

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +This callback is called periodicly accrding to the frequency you set, if the robot moves the values will be updated. The points are published to a topic as well.
"periodically" 

Please review this tutorial a few times and find the typos - there's a bunch of them

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +Assuming that you have already collected your waypoints and they reside at `navigation2_tutorials/nav2_gps_waypoint_follower_demo/params/demo_gps_waypoints.yaml`.
```suggestion
For the purposes of this section, we assume that you have already collected your waypoints and they reside at ``navigation2_tutorials/nav2_gps_waypoint_follower_demo/params/demo_gps_waypoints.yaml``. 
```

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +You can simply launch the GPS waypoint following with provided node.
These all don't need to be independent paragraphs

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +.. code-block:: bash
Not rendering

2021-01-25 20:06 UTC, SteveMacenski commented on tutorials/docs/navigation2_gps_navigation.rst
> +If you save more than one different waypoint data files then just change the demo_gps_waypoints.yaml with your desired file.
This section doesn't really end with a robot following waypoints or explaining any of the things they're launching. Alot more explanation required.

2021-01-26 01:16 UTC, jediofgever commented
I will work on items you mentioned, but my work's priority has changed so I cannot look into it on my work time but in free additional time.

2023-10-06 14:49 UTC, SteveMacenski commented
Superseded!

2023-10-06 14:49 UTC, closed without merging