Documentation changes for ray tracing param changes
ros-planning/navigation.ros.org pull request #131
Opened 2021-01-13 21:17 UTC by danieljeswin

## Description 

* Documenting the `raytrace_min_range` and `raytrace_max_range` params introduced in this [pull request](https://github.com/ros-planning/navigation2/pull/2126).

2021-01-14 18:09 UTC, SteveMacenski requested changes
LGTM, just need to fix one thing that's not quite rendering

2021-01-14 18:09 UTC, SteveMacenski commented on migration/Foxy.rst
> +Raytracing functionality was modified to include a minimum range parameter from which ray tracing starts to clear obstacles to avoid incorrectly clearing obstacles too close to the robot. This issue
All of your parameters need to be in double "`"'s for rst markdown you need 2 around code blocks to render - just a small thing

2021-01-14 18:11 UTC, SteveMacenski commented
by the way, if you hit "show all checks" and go to the job "details", you can get access to your PR's version of the website. Hit "artifacts" and "html/index.html" and it'll open up generated website you can surf to see how your changes look

2021-01-15 00:51 UTC, SteveMacenski commented
I just realized that the parameter is `raytrace_min_range` but we're also apply it to the marking not just raytrace clearing. 

(thinking aloud) we could change it to `obstacle_min_range` and `obstacle_max_range` and the min is also applied to raytracing. We could also make separate marking and clearing `min` variables. Finally, we could make a new name for this that's distinctly not `obstacle` or `raytrace` and we say its applied to both, though I think that's the worse of the  3 options.

What do you think? Sorry I didn't catch this sooner, this is actually why the docs can help alot, seeing it all next to each other gave me an "ah ha" moment. I think separate marking and clearing min variables would be the way to go. That wouldn't involve too much rework, just storing the second `min` variable and applying them in the `mark` functions.

2021-01-15 01:12 UTC, danieljeswin commented
Yeah I think having seperate marking and clearing variables is the way to go

2021-01-15 18:53 UTC, SteveMacenski commented
Awesome, sorry I didn't catch that sooner. Great work!

2021-01-15 23:24 UTC, danieljeswin commented
No worries! I have added a minimum range parameter for it and renamed the existing parameter as the max range parameter

2021-01-22 18:56 UTC, SteveMacenski approved these changes

2021-01-22 18:56 UTC, merged