Initial BT tutorial
ros-planning/navigation.ros.org pull request #141
Opened 2021-03-02 02:01 UTC by vinnnyr

Starting this PR to spark initial conversation and gather initial feedback. 

Looking for initial feedback here for the BT tutorial. I have yet to go about and add the "custom BT" portion of the tutorial, but have so far covered the existing `navigate_w_replanning_and_recovery.xml` default BT.

Few concerns here:

- Is this too dry for a tutorial? Am I going into the weeds too much? Am I not going into it enough? It is hard to gauge for me, and the tutorial seems quite long already. 
- Do I need more pictures or gifs to show what is going on? Is there a way I can get groot to help me with this (tagging @gramss for insight)

2021-03-03 20:15 UTC, SteveMacenski commented
> Am I going into the weeds too much?

I think this tutorial, of any, should be more in the weeds since this is genuinely a new concept to most in robotics so very few will even know the vocabulary we're using. 

> Do I need more pictures or gifs to show what is going on?

These are good, take some groot screen shots or use the BT visualization script in `/tools` of Nav2 to generate some visualizations of the trees so people can see them. The XML is good, but its much easier for people to understand the tree structure looking at... well... trees. For instance in the "Navigate With Replanning and Recovery" section, you show the main Bt first thing, I think you should show the actual tree before that XML block so they can see how the tree goes into the XML. After that point, for any "complete" BT's I'd show the visualization of the tree. For any sub-trees or specific calls, show the XML. 

Reviewing now for more detailed commentary...

2021-03-03 20:46 UTC, SteveMacenski requested changes
I think there should be a bit more organization, but this looks good. So far the document is mostly just walking through the existing BT but I get that your intent is to work from there to modify it to use a specific path below. I think you should continue working on this and we can figure out how to organize the pages later (might make sense to move the BT explanation into a subpage in concepts and then this builds from that or something - either way, work on it here and we can figure it out later)

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Creating a Custom Behavior Tree in ROS2 / Nav2
I'd drop the "in ROS2 / Nav2", I think that's clear from context on out website :wink:

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +but these usually have to be configured and modified based on the application of the robot.
```suggestion
but these sometimes have to be re-configured based on the application of the robot. 
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +* Have a robot (simulated, or physical) that can be used for testing that already works with Nav2
Add a ref link to the getting started page so that they can get started if this is the first page they're looking at

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +    * There is a short explaination in `navigation concepts <../../concepts/index.html>`_
"explaination" -> explanation. In general, type this into something with spell checking and fix all of them, I won't call them all out in the PR review

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +
Between prereq's and "Navigate With Replanning and Recovery", I think you should add a section giving a more gentle introduction building on the most basic behavior tree basics. For example, you  can assume they know what an action/decorator/condition node are, but you should introduce some of our implementations of these that are fundamental. Like ComputePathToPose FollowPath GoalUpdated and Rate/Distance/TimeControllers. That way you give them a little more gentle entry into learning about "what is an action node" to "what are some of the action nodes in nav2" so that when they see the BT, they have some understanding they can tie back into.

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +.. code-block::
None of this is rendering. You may want to use Groot rather to create images instead. It would make it easier to update over time too if we just needed to update the BT for changes. You can see the test version of this website here https://650-240847415-gh.circle-artifacts.com/0/html/tutorials/docs/custom_behavior_tree.html

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +These smaller subtrees are the children of the top-most ``RecoveryNode``, let's call these the ``NavigateWithReplanning`` subtree and the ``RecoveryFallback`` subtree.
```suggestion
These smaller subtrees are the children of the top-most ``RecoveryNode``, let's call these the ``Navigation`` subtree and the ``Recovery`` subtree.
```

These are the actual words I use to describe them, so it would be good to show that here so that as they read other discussions they can draw the parallel

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +
Also, probably use groot, not rendering

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +**Warning**
Make this an actual RST warning, you can see examples of it in https://navigation.ros.org/build_instructions/index.html#manually-build-main dropdowns

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +* A ``Recovery`` in the context of BT is entirely different than a ``Recovery`` in the Nav2 context
```suggestion
* A ``Recovery`` is in the context of BT, not a navigation ``Recovery`` behavior
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +In Nav2, a ``Recovery`` refers to a specific action executed by the robot. When calling out the ``RecoveryFallback``,
This can be removed, the warning covers sufficiently

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +* If the ``RecoveryFallback`` subtree then returns ``SUCCESS`` then ``NavigateWithReplanning`` will be executed again.
Bullets need a line separating, this does not render how you think it would https://650-240847415-gh.circle-artifacts.com/0/html/tutorials/docs/custom_behavior_tree.html

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Note that the ``RecoveryNode`` is a custom ``control`` type node made for Nav2, but can be replaced by any other control type node based on the application.
I think this line can be removed, obviously any of these can be removed at any time

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +NavigateWithReplanning
"Navigation Subtree"

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +RecoveryFallback
"Recovery SubTree"

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Replacements in the BT goes without saying for any node, and from here on out I will only call this out for particularly interesting subsitutions.
Add: "The following two sections discuss the navigation and recovery subtrees at more length."

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +
groot, probably :-)

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +The parent node of this subtree is ``PipelineSequence``, which again is a custom Nav2 BT.
```suggestion
The parent node of this subtree is ``PipelineSequence``, which is a custom Nav2 BT node.
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +        PipelineSequence
didnt render, but I think this could be ascii if you got it to render, its simple enough that wouldn't change

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +The other children and leaves of the tree are simply to throttle, handle failures, and handle updated goals.
```suggestion
The other children and leaves of the tree are simply to throttle, handle failures, and ensuring the robot is responsive to updated goals.
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +    <root main_tree_to_execute="MainTree">
This BT (and others) in this have incorrect indentations. Rate controller should be indenting its members, so should reactive fallback. Please go over and correct in all BTs

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +The ``PipelineSequence`` allows the ``ComputePathToPose`` to be ticked, and once that succeeds, the ``ComputePathToPose`` and ``FollowPath`` to be ticked.
```suggestion
The ``PipelineSequence`` allows the ``ComputePathToPose`` to be ticked, and once that succeeds, ``FollowPath`` to be ticked.
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +For example, the ``RateController`` node simply helps keep the BT ticks at the specified frequency. The default frequency for this BT is 1 hz.
```suggestion
For example, the ``RateController`` node simply helps keep planning at the specified frequency. The default frequency for this BT is 1 hz. 
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +This is done to prevent the BT from hitting the planning server with too many useless requests. Consider changing this frequency to something higher or lower depending on the application and the comp
```suggestion
This is done to prevent the BT from hitting the planning server with too many useless requests at the tree update rate (100Hz). Consider changing this frequency to something higher or lower depending on the application and the computational cost of 
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Recall from above that the ``RecoveryNode`` that this will return ``SUCCESS``
```suggestion
Recall from above that the ``RecoveryNode`` will return ``SUCCESS`` 
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Recall from above that the ``RecoveryNode`` that this will return ``SUCCESS``
This paragraph is really hard to read, might want to consider a way to describe the impact of this node without going through all of the options literally

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +The ``ComputePathToPose`` is a simple action client to the ``ComputePathToPose`` ROS 2 action server.
Remove this - this opens another topic I don't think we want to discuss here (what are these BT nodes ACTUALLY doing?)

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +For convenience, the ``NavigateWithReplanning`` ASCII representation is below again:
I'd remove this line and the ASCII, just have it 1 time in the section, they can scroll up 1/2 a page :-)

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Now that we have covered the structure of the first major subtree, the ``ComputePathToPose`` subtree, the ``FollowPath`` subtree is largely symetric.
Mirror comments above for the follow path section below

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +.. _custom_behavior_tree:
When talking about the recoveries in the main navigation subtree, you can refer to them as "contextual recoveries" because they are recoveries specifically selected for that context of failure (vs system level recoveries in the recovery subtree that are to deal with system-wide failures)

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +                                        |
Groot :-)

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +This should look familiar to the replanning portions of the ``NavigateWithReplanning`` tree. This is a common BT pattern to handle the situation "Unless 'this condition' happens,Do action A".
```suggestion
This should look familiar to the replanning portions of the ``NavigateWithReplanning`` tree. This is a common BT pattern to handle the situation "Unless 'this condition' happens, Do action A".
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +- DistanceTraveled
Space between them to render as a list

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Condition nodes can be very powerful, and other custom NAV2 condition nodes include:
"Nav2"

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +in a ``ReactiveFallback`` with a ``isBatteryLow``condition -- meaning the ``navigate_w_replanning_and_recovery`` tree will execute *unless* the battery becomes low.
```suggestion
in a ``ReactiveFallback`` with a ``isBatteryLow`` condition -- meaning the ``navigate_w_replanning_and_recovery`` tree will execute *unless* the battery becomes low (and then entire a different subtree for docking to recharge). 
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +In this case, ``GoalUpdated`` returns ``FAILURE`` (keep in mind this status is checked asynchronously), then the BT moves on to tick the ``RoundRobin`` node.
```suggestion
If ``GoalUpdated`` returns ``FAILURE``, then the BT moves on to tick the ``RoundRobin`` node.
```

2021-03-03 20:46 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +In this case, ``GoalUpdated`` returns ``FAILURE`` (keep in mind this status is checked asynchronously), then the BT moves on to tick the ``RoundRobin`` node.
You also cover this in the paragraph above, make sure to read through this, there's some non-linearity jumping back in forth or entering a detailed discussion about a BT node in the middle of walking through the tree. Move all BT node explanations first, then go into describing the flow of the tree. Apply for all descriptions :-)

2021-03-27 02:40 UTC, vinnnyr commented
Just merged in something that walks through the custom BT nodes, wanted to push it here and make sure it renders properly before I go through and re-edit the `navigate_w_replanning_and_recovery` portion of the tutorial. 

Does your this new page (https://navigation.ros.org/behavior_trees/index.html) change the direction of this PR / this section I am about to go and edit?

I think it does, we will have a bit more duplicate words.

2021-03-27 02:55 UTC, vinnnyr commented
Additionally, need some advice on how to get these images rendering nicely / professionally. (Currently just using a paint program to slap the labels “(running), (idle), (failure)” etc. 

 I will focus on this issue last, the images for now can serve as a “sketch” of what the end product would be .. but I cannot imagine it being this in the final version. 

The Groot trees took a lot of manual manipulation to get into an aspect ratio that would look good on the webpage so I used the bt2img utility.

2021-03-31 06:11 UTC, SteveMacenski commented
can you give an example? I think how we've done it elsewhere is visualizing the behavior trees using Groot / that script you mentioned.

2021-03-31 12:41 UTC, vinnnyr commented
> can you give an example? I think how we've done it elsewhere is visualizing the behavior trees using Groot / that script you mentioned.

Here is the latest build which has those trees: https://714-240847415-gh.circle-artifacts.com/0/html/tutorials/docs/custom_behavior_tree.html

Right now these are generated using the bt2img.py utility but manually marked up in a paint program for labels.

2021-03-31 20:55 UTC, SteveMacenski commented
I think the python script does a reasonable job at making the tutorial-ready tree.

I might add the state on top of the BT node rather than overlapping/below so that its not overlapping in the box itself. Another option would be putting a border around the BT nodes rather than the `(words)`. Green = success, red = failure, grey = idle, blue = running or something.

2021-04-03 19:35 UTC, vinnnyr commented on tutorials/docs/custom_behavior_tree.rst
> +    * There is a short explaination in `navigation concepts <../../concepts/index.html>`_
I am being more careful about this now, although the latest commit here should no longer have that, I am leaving this discussion "unresolved" so I remember to do that one final time before we are ready.

2021-04-05 14:33 UTC, vinnnyr commented
@SteveMacenski I have significantly edited this now to address your first round of comments, and I think it is worth another round of review from you before I move on to the "custom" portion of the tutorial.

2021-04-05 20:45 UTC, SteveMacenski reviewed
Overall, much better! Much smaller comments and alot fewer of them. This is a really great resource on the BTs of Nav2 and I super appreciate your attention to detail on this. It will help alot of folks!

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Introduction To Nav2 Specific Nodes
I think this section, `Introduction To Nav2 Specific Nodes`, should be placed under the `behavior_trees` page now [that it exists](https://728-240847415-gh.circle-artifacts.com/0/html/behavior_trees/index.html). It should be a new page above the other 3 explaining the basics behind the default BTs titled "Introduction To Nav2 Nodes". It will be the explanation of the flow of the important Nav2 BT nodes so that all explanation of the trees afterwards will have that understanding.

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Introduction To Nav2 Specific Nodes
After its moved, the introduction above this should reference that page to read before going into how to create your own custom behavior tree.

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +- GoalUpdated
Having the `name - explanation` format in Condition as you had in Action would be nice (e.g. explain what each are)

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Decorator: Rate Controller
There are more controller decorators taht should be mentioned - speed, distance, and rate are the big 3. But there are a few more that should be listed in bullet as above https://github.com/ros-planning/navigation2/tree/main/nav2_behavior_tree/plugins/decorator

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +The rate controller node helps control the ticking of its children nodes. The tick rate is an exposed blackboard parameter, it is being used in the default Nav2 BT to limit the rate at which the ``Co
```suggestion
The rate controller node helps control the ticking of its children nodes. The tick rate is an exposed port, it is being used in the default Nav2 BT to limit the rate at which the ``ComputePathToPose`` action node is called.
```

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +The PipelineSequence control node re-ticks previous children when a child returns ``RUNNING``.
```suggestion
The ``PipelineSequence`` control node re-ticks previous children when a child returns ``RUNNING``.
```

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> + .. image:: images/custom_behavior_tree/control_pipelineSequence.png
In this example run, ActionA already returned success, why did it return running again and running at the same time as ActionC? I think this is confusing to a first introduction of this node - even if that's how the node works (which I'm not 100% sure it is). 

Looking at the code, https://github.com/ros-planning/navigation2/blob/main/nav2_behavior_tree/plugins/control/pipeline_sequence.cpp#L36 it seems like if ActionA returned running, the loop would be exited with a running status, so ActionC wouldn't be called to even be able to have the running state until A re-completed again.

So I think the image below 4 should be (running, success, idle), until running re-succeeds to trigger ActionC.

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +2. Upon tick of the parent node, the first child (``Action_A`` is ticked. Let's assume on tick the child returns ``RUNNING``.
```suggestion
2. Upon tick of the parent node, the first child (``Action_A``) is ticked. Let's assume on tick the child returns ``RUNNING``.
```

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +6. On this last tick, let's assume ``Action_C`` returns ``FAILURE``. The parent will circle and tick ``Action_A`` again. ``Action_A`` returns ``RUNNING`` and so will the parent RoundRobin node. This
This pattern will continue indefinitely, but in what situation does this stop? I don't think this explanation ever mentions that

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +let's focus on the Navigation subtree.
What's with the "|" pipes?

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +let's focus on the Navigation subtree.
https://728-240847415-gh.circle-artifacts.com/0/html/tutorials/docs/custom_behavior_tree.html#navigation-subtree they're rendering at the end of that paragraph

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +    This is done to prevent the BT from flooding the planning server with too many useless requests at the tree update rate (100Hz). Consider changing this frequency to something higher or lower depe
"Also consider using another decorator such as the distance or speed controller if appropriate"

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +The ``Recovery`` subtree is the second big "half" of the Nav2 default ``navigate_w_replanning_and_recovery.xml`` tree.
All places where "navigate_w_replanning_and_recovery.xml" is listed, the Bt will be renamed in PR2271 with NavThroughPoses to "navigate_to_pose_w_replanning_and_recovery.xml", it may be worth updating all here now since that will likely be merged in before this (sometime this week)

2021-04-05 20:45 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +For example, let's say the robot is stuck and the ``Navigation`` subtree returns ``FAILURE``:
It would be nice if this example ended with a successful fix (e.g. one of the BT node actually did end up fixing the navigation subtree) so that the user can see how this can be used to **successfully** get the robot out of a jam

2021-08-05 01:41 UTC, SteveMacenski commented
Hey! Just touching base on this

2021-08-09 01:43 UTC, vinnnyr commented on tutorials/docs/custom_behavior_tree.rst
> + .. image:: images/custom_behavior_tree/control_pipelineSequence.png
I think the way it is written here is correct, although I think you are right that is might be a bad first intro of the node. 
We can modify the scenario so that `ActionA` does not return `RUNNING` again after already being ticked, although I think we lose some of the nuance of the pipeline if we do that. 

> In this example run, ActionA already returned success, why did it return running again and running at the same time as ActionC?

A gets reticked, even though it has returned SUCCESS before, but I don't think the parent control node will not exit with `RUNNING` since the A will not be the `last_child_ticked_` in this case (the index of B would have been assigned to that variable in this case) .

 https://github.com/ros-planning/navigation2/blob/792893a5b56256cff8e9d4fb581e71d23892b5d6/nav2_behavior_tree/plugins/control/pipeline_sequence.cpp#L50

B is now `SUCCESS` so we move on to tick C, which happens to return `SUCCESS`. 


I think this test also reflect this: https://github.com/ros-planning/navigation2/blob/792893a5b56256cff8e9d4fb581e71d23892b5d6/nav2_behavior_tree/test/plugins/control/test_pipeline_sequence.cpp#L102

let me know if you would like some more meat describing this subtly, or if we should modify the scenario a bit to be simpler for the first intro

2021-08-09 02:03 UTC, vinnnyr commented
Hey @SteveMacenski  , I apologize this slipped. I think we have some outstanding discussion on `PipelineSequence` . 

I believe I have addressed everything else so far.

I suggest that we punt the "custom BT" portion of the tutorial to a separate PR so we can at least get the work we did thus far released, as I am afraid I cannot predict a timeline for the other "custom BT" portion of this ticket. 

If you agree, I can remove all reference to the "custom BT" part of the tutorial and we can pick that up at a separate time.

2021-08-20 23:17 UTC, SteveMacenski requested changes

2021-08-20 23:17 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +If at any point the goal gets updated, this subtree will halt all children and return ``SUCCESS``.
"This allows for quick reactions to new goals and preempt currently executing recoveries."

2021-08-20 23:17 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +Custom Action
I love all of this description and walking through the BT. Can we move this over to the "Nav2 Behavior Trees" section as another subpage called "Detailed Behavior Tree Walkthrough". Then we can have that as another bullet in the Prerequisites for this tutorial.

2021-08-20 23:17 UTC, SteveMacenski commented on tutorials/docs/custom_behavior_tree.rst
> +
Then, I think we can focus in on this tutorial. The new intro paragraph would read

> There are many example behavior trees provided in nav2_bt_navigator/behavior_trees, but these sometimes have to be re-configured based on the application of the robot. The following tutorial will walk through how to modify the current main default BT navigate_to_pose_w_replanning_and_recovery.xml to do another potentially useful task. This example will show how to develop a BT that follows a predefined path.

So you an still start with the image of the default BT and then dive into the updates needed to do this tutorial task.

2021-08-21 01:14 UTC, SteveMacenski approved these changes

2021-08-21 01:14 UTC, merged