Add pure pursuit controller tutorial
ros-planning/navigation.ros.org pull request #15
Opened 2020-05-19 01:31 UTC by shrijitsingh99

Signed-off-by: Shrijit Singh <shrijitsingh99@gmail.com>

Tutorial for pure pursuit controller.
Any changes needed or content improved?

2020-05-19 01:50 UTC, SteveMacenski commented
>  Add an image of the controller working in simulation

Gif please, videos always preferred.

2020-05-19 02:02 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +    In controllers, this method is used to set member variables, declare ROS parameters with default parameters and read their values.
I think you messed up the formatting here with a couple extra spaces, that shows up as a quote. This section should be a relatable walk through of the plugin and the API, so you should reword everything from being general in the table to being specific and approachable to the reader for this point down

2020-05-19 02:03 UTC, shrijitsingh99 commented
> Gif please, videos always preferred.
Since I can show it in simulation only currently, is video needed, or is GIF enough?
I don't mind doing either.

2020-05-19 02:03 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +The passed in arguments are stores in member variables so that hey can be used at a later stage if needed.
Typo, and just include it in the snipped above. 1 snippet and then explain  the lines in order below.

2020-05-19 02:04 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +Here, we prepend the mapped plugin name to the parameter like this ``plugin_name_ + ".desired_linear_vel"``. This is done as Navigation2 allows ,loading multiple
You have a comma just hanging around, I think that should be deleted.

2020-05-19 02:05 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +This method is used to store the global plan and the goal pose (i.e. last pose of the global plan). Additionaly it used to transform the global plan into
Typo

2020-05-19 02:05 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +This is used to convert the global path from ``nav_msgs::msg::Path`` to ``nav_2d_msgs::msg::Path2D``. This is done as the ``Path2D`` message is easier to
Remove that from both this tutorial and implementation. You should not make use of the `nav_2d_msgs` package at all.

2020-05-19 02:06 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +This is used to convert the global path from ``nav_msgs::msg::Path`` to ``nav_2d_msgs::msg::Path2D``. This is done as the ``Path2D`` message is easier to
Do not make use of any messages defined in the dwb metapackage

2020-05-19 02:06 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +The global path needs to be transformed into the appropriate frame before using it. This is generally same as costmap frame for man controllers.
man controllers?

2020-05-19 02:06 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +In our case, this frame is the robot's own frame. So, we transform the global path into the robot's frame.
That's probably not true, you probably translate it into odometry frame?

2020-05-19 02:08 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +A new TwistStamped message is created to store the computed velocitu and then this message is returned.
typo

2020-05-19 02:09 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +  return hypot(pose.pose.position.x - goal_pose_.pose.position.x, pose.pose.position.y - goal_pose_.pose.position.y) <= goal_tolerance_;
I hope that's not actually all on one line, that's way over the character limit

2020-05-26 18:21 UTC, SteveMacenski commented
Pinging @shrijitsingh99

2020-06-11 13:03 UTC, shrijitsingh99 commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +In this tutorial we will be implementing the pure pursuit path tracking algorithm. It is recommended you go over the `paper <https://www.ri.cmu.edu/pub_files/pub3/coulter_r_craig_1992_1/coulter_r_cra
> quick summary of what it says.

I think the summary may not be needed as the paper is essentially 3-4 pages. So the user can easily fo through it.

2020-06-11 13:05 UTC, shrijitsingh99 commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +We will be implementing the pure pursuit controller. The annotated code in this tutorial can be found in `navigation_tutorials <https://github.com/ros-planning/navigation2_tutorials>`_ repository as
I have currently implemented the simplest form of the algorithm so as to make it easy for the reader to understand the process of creating a controller and not get bogged down by the algorithm. 

Maybe we can implement an advanced version of this on the main repo.

2020-06-11 13:21 UTC, shrijitsingh99 commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +In our case, this frame is the robot's own frame. So, we transform the global path into the robot's frame.
The lookahead point needs to be in the robot frame for calculation of the curvature of the path.
It is possible to do the entire thing in the odometry frame but I think it will add additional complexity, which can be avoided since this is a tutorial to get started.

2020-06-11 13:22 UTC, shrijitsingh99 commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +This is used to convert the global path from ``nav_msgs::msg::Path`` to ``nav_2d_msgs::msg::Path2D``. This is done as the ``Path2D`` message is easier to
Added to the TODO, will remove this once other things in the tutorial are sorted.

2020-06-11 13:25 UTC, shrijitsingh99 commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +The passed in arguments are stores in member variables so that hey can be used at a later stage if needed.
> explain the lines in order below.
Like, explain each argument? I didn't quite follow

2020-06-11 13:26 UTC, shrijitsingh99 commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +    In controllers, this method is used to set member variables, declare ROS parameters with default parameters and read their values.
Okay, I will look into rewording some areas, to make it more approachable.

2020-06-11 23:38 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +This is used to convert the global path from ``nav_msgs::msg::Path`` to ``nav_2d_msgs::msg::Path2D``. This is done as the ``Path2D`` message is easier to
@shrijitsingh99 this should be removed now, I can't approve this PR while that reference is still there. If nothing else, change in the docs now and update in the code later

2020-06-11 23:39 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +In this tutorial we will be implementing the pure pursuit path tracking algorithm, based on the `paper <https://www.ri.cmu.edu/pub_files/pub3/coulter_r_craig_1992_1/coulter_r_craig_1992_1.pdf>`_.
```suggestion
In this tutorial we will be implementing the pure pursuit path tracking algorithm, based on this `paper <https://www.ri.cmu.edu/pub_files/pub3/coulter_r_craig_1992_1/coulter_r_craig_1992_1.pdf>`_. 
```

2020-06-11 23:39 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +We will be implementing the pure pursuit controller. The annotated code in this tutorial can be found in `navigation_tutorials <https://github.com/ros-planning/navigation2_tutorials>`_ repository as
```suggestion
We will be implementing the pure pursuit controller. The annotated code in this tutorial can be found in `navigation_tutorials <https://github.com/ros-planning/navigation2_tutorials>`_ repository as the ``nav2_pure_pursuit_controller``.
```

2020-06-11 23:40 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +| cleanup()                 | This method should clean up resoures which are created for the controller.            | Yes                    |
"resources"

2020-06-11 23:41 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +| computeVelocityCommands() | This method is called when a new velocity command is required by the robot to follow  | Yes                    |
you repeat "to follow" twice

2020-06-11 23:41 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +|                           | takes in 2 parameters: reference to the current robot pose and its current velocity,  |                        |
"It takes..."

2020-06-11 23:42 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +The passed in arguments are stored in member variables so that hey can be used at a later stage if needed.
```suggestion
The passed in arguments are stored in member variables so that they can be used at a later stage if needed.
```

2020-06-11 23:43 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +.. code-block:: c++
Please put the entire configure code block together and then speak about it. Separating the lines makes it not clear (and not uniform with other plugin tutorials) where those lines are located. Have them all in 1 block and then speak about them in different paragraphs under it so they can reference the code block. Ditto for all other sections below.

2020-06-11 23:44 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +This method is used to store the global plan and the goal pose (i.e. last pose of the global plan). Additionaly it is used to transform the global plan into
```suggestion
This method is used to store the global plan and the goal pose (i.e. last pose of the global plan). Additionally it is used to transform the global plan into 
```

2020-06-11 23:46 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +Here, we check whether the current robot pose, is within a certain distance (i.e. goal tolerance) from from the goal pose. If it is then we return true
```suggestion
Here, we check whether the current robot pose, is within a certain distance (i.e. goal tolerance) from from the goal pose. If it is, then we return true
```

2020-06-11 23:47 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +The remaining methods are not used but its mandatory to override them. As per the rules, we did override all but left them empty.
Please explain here what they are used for, even though you didn't override them. Just something like "our implementation did not require anything in activate / deactivate since it did not provide any services or topic subscriptions".

2020-06-18 17:00 UTC, SteveMacenski commented
@shrijitsingh99 pinging again

2020-07-01 22:13 UTC, shrijitsingh99 commented
Ooops I keep on forgetting about this, my bad :sweat_smile:. I will for sure finish it this week.

2020-07-01 22:24 UTC, SteveMacenski commented
So close! Lets try to get this done in the next week or two

2020-07-29 21:30 UTC, SteveMacenski commented
@shrijitsingh99 pinging

2020-08-26 22:54 UTC, SteveMacenski commented
@shrijitsingh99 pinging

2020-09-03 17:08 UTC, shrijitsingh99 commented
On it 😀

2020-09-03 17:30 UTC, SteveMacenski commented
Once this is done, we can close the tutorials ticket, I wrote the rest of them last week :rocket:

2020-09-14 13:20 UTC, shrijitsingh99 commented
Finally, progress on this from my side 😅 
Changes:
1. Update code to reflect the API changes in nav2_controller
2. Made it similar to existing tutorials
3. Ran it through Grammarly (Should be free of grammatical mistakes hopefully)
4. Removed all reference DWB dependencies

2020-09-14 18:50 UTC, SteveMacenski commented
You also need to resolve the merge conflict

2020-09-14 18:57 UTC, SteveMacenski requested changes

2020-09-14 18:57 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +| **Virtual method**        | **Method description**                                                                | **Requires override?** |
Your table isn't rendering, see build errors in CI (or build locally). https://421-240847415-gh.circle-artifacts.com/0/html/tutorials/docs/writing_new_nav2controller_plugin.html

2020-09-14 18:57 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +The list of methods and their descriptions and necessity are presented in the table below:
```suggestion
The list of methods, their descriptions, and necessity are presented in the table below:
```

2020-09-14 18:57 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +Here, ``plugin_name_ + ".desired_linear_vel"`` is fetching the ROS parameters desired_linear_vel which is specific to our controller.
```suggestion
Here, ``plugin_name_ + ".desired_linear_vel"`` is fetching the ROS parameters ``desired_linear_vel`` which is specific to our controller. 
```

2020-09-14 18:57 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +Now, if we want to retrieve the parameters for that specific plugin, we use <mapped_name_of_plugin>.<name_of_parameter> as done in the above snippet.
```suggestion
Now, if we want to retrieve the parameters for that specific plugin, we use ``<mapped_name_of_plugin>.<name_of_parameter>`` as done in the above snippet. 
```

2020-09-14 18:57 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +For example, our example controller is mapped to the name FollowPath and to retrieve the desired_linear_vel parameter, which is specific to "FollowPath”,
```suggestion
For example, our example controller is mapped to the name ``FollowPath`` and to retrieve the ``desired_linear_vel`` parameter, which is specific to "FollowPath”, 
```

2020-09-14 18:57 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +we used FollowPath.desired_linear_vel. In other words, FollowPath is used as a namespace for plugin-specific parameters.
```suggestion
we used ``FollowPath.desired_linear_vel``. In other words, ``FollowPath`` is used as a namespace for plugin-specific parameters. 
```

2020-09-14 18:57 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +  node_ = parent;
Please put the function signatures and `{}` in the snippets so its clear what function they're looking at

2020-09-14 18:57 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +  controller_plugin_ids: ["FollowPath"]
Include some parameters here. Also, that's not how the plugins are loaded, see the other tutorials.

2020-09-14 18:58 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +The remaining methods are not used but its mandatory to override them. As per the rules, we did override all but left them empty.
This is still relevant

2020-09-14 18:58 UTC, SteveMacenski commented
Pretty close, just a few things to clean up. The code should be good to go for a PR in the tutorial repo at this point.

2020-09-15 14:32 UTC, shrijitsingh99 commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +  controller_plugin_ids: ["FollowPath"]
Updated based on the current param file in `nav2_bringup`.

2020-09-15 14:44 UTC, shrijitsingh99 commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +| **Virtual method**        | **Method description**                                                                | **Requires override?** |
Fixed. Strangely VSCode was still rendering it, even though the table structure was malformed

2020-09-15 16:16 UTC, SteveMacenski requested changes
Closer, a few smaller things and I think this is good to go

2020-09-15 16:16 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +|                           | controller's member variables. This method takes 4 input params: shared pointer to    |                        |
Weak pointer now I believe

2020-09-15 16:16 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +|                           | should clean up resoures which are created for the controller.                        |                        |
"resources"

2020-09-15 16:16 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +| setPlan()                 | Method is called when controller server goes to on_cleanup state. Ideally this method | Yes                    |
This description isn't what `setPlan` does

2020-09-15 16:16 UTC, SteveMacenski commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +        robot_frame: "base_link"
Could you instead use the robot frame provided from the costmap_2d configuration?

2020-09-15 18:36 UTC, shrijitsingh99 commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +| setPlan()                 | Method is called when controller server goes to on_cleanup state. Ideally this method | Yes                    |
Is the updated definition okay?

2020-09-15 18:37 UTC, shrijitsingh99 commented on tutorials/docs/writing_new_nav2controller_plugin.rst
> +        robot_frame: "base_link"
Yeah, that's much better. Updated the code and removed references of `robot_frame` from the tutorial.

2020-09-16 01:11 UTC, merged

2020-09-16 01:13 UTC, SteveMacenski commented
@shrijitsingh99 please submit the code to the navigation2_tutorials repo