planner_selector in migration guide
ros-planning/navigation.ros.org pull request #152
Opened 2021-03-22 20:04 UTC by pabloinigoblasco

Simple documentation to include the planner_selector on the migration guide.

2021-03-22 23:37 UTC, SteveMacenski requested changes

2021-03-22 23:37 UTC, SteveMacenski commented on plugins/index.rst
> +| `Planner Selector`_                        | Pablo Iñigo Blasco  | Selects the global planner               |
"based on a topic input, otherwises uses a default planner id"

2021-03-22 23:37 UTC, SteveMacenski commented on migration/Foxy.rst
> +
Just above this is the `SingleTrigger` added BT node section, you can remove this new section and just add this to the list after SingleTrigger with a link to the PR

2021-03-22 23:37 UTC, SteveMacenski commented on configuration/packages/bt-plugins/actions/PlannerSelector.rst
> +.. _bt_planner_selector_node:
There's no link to this page anywhere, please add this page to the list https://692-240847415-gh.circle-artifacts.com/0/html/configuration/packages/configuring-bt-xml.html on this page under Action Plugins to have this page then properly linked

2021-03-22 23:37 UTC, SteveMacenski commented on configuration/packages/bt-plugins/actions/PlannerSelector.rst
> +It is used to select the planner that will be used by the planner server. It subscribes to the _planner_selector_ topic to recive command msgs with the name of the planner to be used. It is commonly
```suggestion
It is used to select the planner that will be used by the planner server. It subscribes to the ``planner_selector`` topic to receive command messages with the name of the planner to be used. It is commonly used before of the ComputePathToPoseAction. The ``selected_planner`` output port is passed to ``planner_id`` input port of the ComputePathToPoseAction. If none is provided on the topic, the ``default_planner`` is used.
```

2021-03-23 20:18 UTC, SteveMacenski commented
https://github.com/ros-planning/navigation.ros.org/blob/master/configuration/packages/configuring-bt-xml.rst Last thing missing is your rst file has to be added to the Action list here so that it can be accessed

2021-03-23 20:36 UTC, pabloinigoblasco commented on configuration/packages/bt-plugins/actions/PlannerSelector.rst
> +.. _bt_planner_selector_node:
This should be already done:
https://github.com/ros-planning/navigation.ros.org/pull/152/commits/3bc2462254a2e33bb2e1ecc959b546d9275edc53

2021-03-23 20:43 UTC, SteveMacenski approved these changes

2021-03-23 20:43 UTC, merged