Add Sensors Setup Guide
ros-planning/navigation.ros.org pull request #194
Opened 2021-08-03 09:30 UTC by jd-deleon

Co-authored-by: Areeya Rubenecia a.rubenecia@samsung.com
Co-authored-by: Fiona Estoperez f.estoperez@samsung.com
Co-authored-by: Steve Macenski stevenmacenski@gmail.com

2021-08-03 17:36 UTC, SteveMacenski requested changes
The costmap_2d section needs a bit of work, but overall great! I think it just needs to be simplified so we can leverage the default configurations/launch files in the packages by removing the gazebo `demo/` namespace to our data sources. 

Also, I think an edit over this section remembering that our goal is to explain how to set up our sensors w.r.t. costmap_2d might be good. There are a couple of times where it goes in to explaining more info as an overview of costmap_2d rather than focusing from the perspective of 'setting up my sensors for the first time'. I don't think any of the content is wrong, I think some of the sentences could be better tied back to the goal of the tutorial more directly

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +.. image:: images/sensor_laserscan_gazebo.png
For all image pairs, can you get them to render in the middle of the page? These 2 are nearly 50% so they effectively so, but the next one for instance is off to the left noticeably.

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +To give you a better grasp of how to set up sensors on a simulated robot, we will build up on our previous tutorials and attach sensors to our simulated robot ``sam_bot``. Similar to the previous tut
```suggestion
To give you a better grasp of how to set up sensors on a simulated robot, we will build up on our previous tutorials and attach sensors to our simulated robot ``sam_bot``. Similar to the previous tutorial where we used Gazebo plugins to add odometry sensors to ``sam_bot``, we will be using the Gazebo plugins to simulate a lidar sensor and a depth camera on ``sam_bot``. If you are working with a real robot, most of these steps are still required for setting up your URDF frames and it will not hurt to also add in the gazebo plugins for later use. 
```

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +Now that we have a robot with its sensors set up, we can use the obtained sensor information to build a map of the environment and to localize the robot on the map. The ``slam_toolbox`` package is a
```suggestion
Now that we have a robot with its sensors set up, we can use the obtained sensor information to build a map of the environment and to localize the robot on the map. The ``slam_toolbox`` package is a set of tools and capabilities for 2D Simultaneous Localization and Mapping (SLAM) in potentially massive maps with ROS2. It is also one of the officially supported SLAM libraries in Nav2, and we recommend to use this package in situations you need to use SLAM on your robot setup. Aside from the ``slam_toolbox``, localization can also be implemented through the ``nav2_amcl`` package. This package implements Adaptive Monte Carlo Localization (AMCL) which estimates the position and orientation of the robot in a map. Other techniques may also be available, please check Nav2 documentation for more information.
```

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +The costmap implementation consists of multiple layers, each of which has a certain function that contributes to a cell's overall cost. It consists of the following layers: static layer, inflation la
```suggestion
The costmap implementation consists of multiple layers, each of which has a certain function that contributes to a cell's overall cost. The package consists of the following layers, but are plugin-based to allow customization and new layers to be used as well: static layer, inflation layer, range layer, obstacle layer, and voxel layer. The static layer represents the map section of the costmap, like those produced by SLAM. The obstacle layer includes the obstacles reported by sensors in 2D. The voxel layer is similar to the obstacle layer but handles 3D data instead. The range layer allows for the inclusion of sonar and infrared data to our costmap. Lastly, the inflation layer represents the added cost values around lethal obstacles such that our robot avoids navigating into obstacles due to the robot's geometry. In the next subsection of this tutorial, we will have some discussion about the basic configuration of the different layers in ``nav2_costmap_2d``. 
```

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +In this subsection, we will show an example configuration of ``costmap_2d`` and explain the basic configuration parameters. The code block below is an example of ``costmap_2d`` configuration using st
```suggestion
In this subsection, we will show an example configuration of ``costmap_2d`` and explain the basic configuration parameters for your sensors. The code block below is an example of ``costmap_2d`` configuration using static layer, obstacle layer, voxel layer, and inflation layer. Note that this block of parameters will be included in the `config/nav2_params.yaml <https://github.com/ros-planning/navigation2_tutorials/blob/master/sam_bot_description/config/nav2_params.yaml>`_ file  when we launch Nav2 at the end of this section.
```

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +        rolling_window: true
This should be false for most situations, its only true generally for the local costmap

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +Now, we will configure the parameters of ``slam_toolbox``. Go to the ``config`` directory and create a ``mapper_params.yaml`` file. Then copy the contents of `config/mapper_params.yaml <https://githu
So I think here just use my parameter files / launch files in SLAM Toolbox itself, not adding a new launch/config file in this package here (especially just for a demo unless you've remapped the scan topics to non-default `scan`). If you have, I think you should remove the `demo/` namespace since that isn't standard

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +Before we launch the ``slam_toolbox``, make sure you have launched sam_bot's ``display.launch.py`` by executing the the lines below. Remember that this provides our ``odom`` => ``base_link`` and ``ba
The URDF doesn't provide the odom->baselink transformation. Gazebo does through the diff drive plugin

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +We will configure the parameters of Nav2 to use our costmap configuration in the previous subsection. Create a file named ``nav2_params.yaml`` under the ``config`` directory and then copy the content
As well here, if you remove the `demo` namespace, then you can just use the default parameters and launch files in Nav2 itself

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +  ros2 launch slam_toolbox online_async_launch.py slam_params_file:=<full/path/to/config/mapper_params.yaml>
Where is gazebo launched?

2021-08-03 17:36 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +We will configure the parameters of Nav2 to use our costmap configuration in the previous subsection. Create a file named ``nav2_params.yaml`` under the ``config`` directory and then copy the content
Also, where is gazebo launched in this instruction?

2021-08-04 08:53 UTC, arubenecia commented on setup_guides/sensors/setup_sensors.rst
> +Now, we will configure the parameters of ``slam_toolbox``. Go to the ``config`` directory and create a ``mapper_params.yaml`` file. Then copy the contents of `config/mapper_params.yaml <https://githu
We already removed the demo namespace and removed the new config file for slam toolbox.

2021-08-04 08:54 UTC, arubenecia commented on setup_guides/sensors/setup_sensors.rst
> +Before we launch the ``slam_toolbox``, make sure you have launched sam_bot's ``display.launch.py`` by executing the the lines below. Remember that this provides our ``odom`` => ``base_link`` and ``ba
The display.launch.py also launches Gazebo so the odom->baselink transform should be provided upon launching display.launch.py. We will make clarifications about this on the draft.

2021-08-04 08:56 UTC, arubenecia commented on setup_guides/sensors/setup_sensors.rst
> +We will configure the parameters of Nav2 to use our costmap configuration in the previous subsection. Create a file named ``nav2_params.yaml`` under the ``config`` directory and then copy the content
The demo namespace and the new config file for nav2 have also been removed

2021-08-04 08:56 UTC, arubenecia commented on setup_guides/sensors/setup_sensors.rst
> +  ros2 launch slam_toolbox online_async_launch.py slam_params_file:=<full/path/to/config/mapper_params.yaml>
Gazebo is launched inside the display.launch.py

2021-08-04 17:34 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +Now, we will configure the parameters of ``slam_toolbox``. Go to the ``config`` directory and create a ``mapper_params.yaml`` file. Then copy the contents of `config/mapper_params.yaml <https://githu
They are still included in the tutorials PR

2021-08-04 17:35 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +We will configure the parameters of Nav2 to use our costmap configuration in the previous subsection. Create a file named ``nav2_params.yaml`` under the ``config`` directory and then copy the content
OK, make sure to update the tutorials PR

2021-08-05 08:16 UTC, arubenecia commented
The tutorial is now updated. Changes made according to the comments are included in the latest commits.

2021-08-05 18:24 UTC, SteveMacenski requested changes

2021-08-05 18:24 UTC, SteveMacenski commented on setup_guides/sensors/setup_sensors.rst
> +For the voxel layer (lines 51-66), we set the ``publish_voxel_map`` parameter to ``True`` to enable the publishing of the 3D voxel grid. The resolution of the voxels in height is defined using the ``
```suggestion
For the voxel layer (lines 51-66), we set the ``publish_voxel_map`` parameter to ``True`` to enable the publishing of the 3D voxel grid. The resolution of the voxels in height is defined using the ``z_resolution`` parameter, while the number of voxels in each column is defined using the ``z_voxels`` parameter. The ``mark_threshold`` parameter sets the minimum number of voxels in a column to mark as occupied in the occupancy grid. We set the ``observation_sources`` parameter of the voxel layer to ``scan``, and we set the scan parameters (in lines 61-66) similar to the parameters that we have discussed for the obstacle layer. As defined in its ``topic`` and ``data_type`` parameters, the voxel layer will use the ``LaserScan`` published on the ``/scan`` topic by the lidar scanner.
```

2021-08-05 18:24 UTC, SteveMacenski approved these changes

2021-08-05 18:24 UTC, merged