Add documentation for the new on_completion() function of the BtServi…
ros-planning/navigation.ros.org pull request #195
Opened 2021-08-03 16:49 UTC by philison

…ceNode.

Documents changes introduced in [this PR](https://github.com/ros-planning/navigation2/pull/2481/commits/f9d60039d452089611496e5fca09783fbd6a4e95).

2021-08-03 17:38 UTC, SteveMacenski requested changes

2021-08-03 17:38 UTC, SteveMacenski commented on migration/Galactic.rst
> +**************************
The `***` line has to exactly match the length of the header

2021-08-03 22:00 UTC, philison commented on migration/Galactic.rst
> +**************************
I see. I fixed it.

2021-08-04 00:14 UTC, SteveMacenski approved these changes

2021-08-04 00:14 UTC, merged