Add docs for Denoise Layer plugin (costmap_2d)
ros-planning/navigation.ros.org pull request #209
Opened 2021-09-17 08:23 UTC by ryzhikovas

2022-03-31 10:25 UTC, AlexeyMerzlyakov reviewed
This is pretty large plugin being adding into Nav2 stack. So, please add new "New Plugins" section to "Galactic to Humble" migration guide where to make a short description and reference to the Denoise Layer plugin there. You can find similar sections in Galactic and Foxy migration guides as an example.

2022-03-31 10:25 UTC, AlexeyMerzlyakov commented on plugin_tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +It apply erosion function with kernel from image below (left if ``group_connectivity_type`` = 4 or right if ``group_connectivity_type`` = 8) to the costmap.
Some reference link to erosion function would be great

2022-03-31 10:25 UTC, AlexeyMerzlyakov commented on plugin_tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +    :width: 222px
Does the erosion apply to pixels colored in white? Please add some explanation, what white and black pixels mean here.

2022-03-31 10:25 UTC, AlexeyMerzlyakov commented on plugin_tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +This algorithm is about 10 times slower, so use it with caution and only when necessary.
->
This algorithm is about 10 times slower than first, so use it with caution and only when necessary.

2022-04-15 08:01 UTC, ryzhikovas commented
I have fixed the issues mentioned. If at the same time I did not introduce new shortcomings, then I am ready to synchronize (fetch + rebase) whis the parent branch.

2022-04-19 09:03 UTC, AlexeyMerzlyakov reviewed
Thank you for the thorough work there! Some small changes are required and we could go.

2022-04-19 19:13 UTC, ryzhikovas commented
Fixed in these last two commits [[1]](https://github.com/ros-planning/navigation.ros.org/pull/209/commits/22308fcd07e795d98e1c0c44b51f7deedd2da873), [[2]](https://github.com/ros-planning/navigation.ros.org/pull/209/commits/6513710e3d100c1055512cb26a0423b36ecf2648). In addition, performed the rebase.

2022-04-20 08:57 UTC, AlexeyMerzlyakov approved these changes
LGTM

2022-04-28 18:19 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/denoise.rst
> +Denoise Layer Parameters
I would recommend that the default example here only uses the denoise in the local costmap, due to performance issues and small bits of noise are more dramatic in the local controller's use of the costmap anyhow

2022-04-28 18:19 UTC, SteveMacenski commented on migration/Galactic.rst
> +New plugin
```suggestion
New Denoise Costmap Layer Plugin
```

2022-04-28 18:19 UTC, SteveMacenski commented on plugin_tutorials/index.rst
> +   docs/filtering_of_noise-induced_obstacles.rst
This tutorial should be moved to the general tutorials list, the "plugin tutorials' are for writing plugins not tutorials about using the plugins themselves, but that's an easy confusion point.

2022-04-28 18:19 UTC, SteveMacenski commented on plugin_tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +Denoise Layer is Costmap2D plugin. You can enable the ``DenoiseLayer`` plugin in Costmap2D by adding ``denoise_layer`` to the ``plugins`` parameter in ``nav2_params.yaml``. You can place it in the ``
I would add a note here that this is typically most usable in the local costmap, though usable in the global costmap as well. Since the local costmap updates are much smaller, it will have less impact on run-time performance. I'm concerned that if users generally use this in the global costmap, it will cause performance issues when paired with typically-high-range lidars of 20+ meters which the update window may be massive.

Another reason is that since this works only in the update window, if you have salt and pepper noise in the local costmap, it disappears and is not remembered when going back into that region since the local costmap doesn't store data in areas after it has left.

The global costmap does though, so if we leave an area and the salt / pepper noise was being handled by this later, it would still be there when we came back. This isn't necessarily a problem, but makes me want to make the point to users that you can do this, but there are some real things to think about if doing so.

2022-12-26 08:02 UTC, AlexeyMerzlyakov reviewed
Please re-base over latest main branch; and check Steve and my comments

2022-12-26 08:02 UTC, AlexeyMerzlyakov commented on plugin_tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +  ros2 launch nav2_bringup tb3_simulation_launch.py
Currently, `ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False` (https://navigation.ros.org/getting_started/index.html#running-the-example)

2023-01-30 17:42 UTC, ryzhikovas commented on plugin_tutorials/index.rst
> +   docs/filtering_of_noise-induced_obstacles.rst
[Done](https://github.com/ros-planning/navigation.ros.org/pull/209/commits/b6b1238467a0d580e1a8e301241d7a73f02c3b33)

2023-01-30 17:42 UTC, ryzhikovas commented on configuration/packages/costmap-plugins/denoise.rst
> +Denoise Layer Parameters
[Done](https://github.com/ros-planning/navigation.ros.org/pull/209/commits/7fa905827fea2dd8d2fb125198bbd3b302faba80)

2023-01-30 17:42 UTC, ryzhikovas commented on migration/Galactic.rst
> +New plugin
[Fixed](https://github.com/ros-planning/navigation.ros.org/pull/209/commits/031c24798db54d4d090a42d187992f8d0a800a5c)

2023-01-30 17:42 UTC, ryzhikovas commented on plugin_tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +Denoise Layer is Costmap2D plugin. You can enable the ``DenoiseLayer`` plugin in Costmap2D by adding ``denoise_layer`` to the ``plugins`` parameter in ``nav2_params.yaml``. You can place it in the ``
[Done](https://github.com/ros-planning/navigation.ros.org/pull/209/commits/3261c55a16f02ee47f04c8b488b9918f08afe10e). If I misunderstood your thought or described it poorly, please help me with a clear statement of this warning.

2023-01-30 17:43 UTC, ryzhikovas commented on migration/Galactic.rst
> +
[Fixed](https://github.com/ros-planning/navigation.ros.org/pull/209/commits/2711f4a97f0fb6bbaa6ad5a004eb0510dbfafee8)

2023-01-30 17:43 UTC, ryzhikovas commented on plugin_tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +  ros2 launch nav2_bringup tb3_simulation_launch.py
[Fixed](https://github.com/ros-planning/navigation.ros.org/pull/209/commits/279ed83e90d70273352b7540a28c0c99de67fd47)

2023-02-01 14:28 UTC, AlexeyMerzlyakov reviewed
The documentation updates seems to be already ironed in previous reviews. There are a few strokes and I see no problem to go.

2023-02-01 14:28 UTC, AlexeyMerzlyakov commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +Values less than 255 will be interpreted as free cells when processed (but will not be distorted in the cost map).
From `DenoiseLayer::isBackground()` it seems that we have to treat `INSCRIBED_INFLATED_OBSTACLE (253)` and `LETHAL_OBSTACLE (254)` as obstacles, and sometimes `NO_INFORMATION (255)`. This means that values less that 253 will be interpreted as free cells when processed. Please correct the description accordingly.

2023-02-02 13:46 UTC, ryzhikovas commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +  If some sensor generates intercorrellated noise-induced obstacles and small obstacles in the world are unlikely, small groups of obstacles can be removed.
Fixed

2023-02-02 13:50 UTC, ryzhikovas commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +Values less than 255 will be interpreted as free cells when processed (but will not be distorted in the cost map).
https://github.com/ros-planning/navigation.ros.org/pull/209/commits/a2cd0470f9110c45264c9ec25f7d0ce03ffedc17 I suppose there is no need to explain here when ``NO_INFORMATION`` is an obstacle, because it is a small detail?

2023-02-03 11:56 UTC, AlexeyMerzlyakov approved these changes
One comment (please restore back clarification). After it, LGTM.
@SteveMacenski, could you also please take a look on the PR?

2023-02-03 11:56 UTC, AlexeyMerzlyakov commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +will be interpreted as obstacle cell. Cells with any other values will be interpreted as ``FREE_SPACE`` when processed.
```
Cells with any other values will be interpreted as ``FREE_SPACE`` when processed.
->
Cells with any other values will be interpreted as ``FREE_SPACE`` when processed (won't be distorted in the cost map).
```
I think, this is important clarificaiton

2023-02-03 11:56 UTC, AlexeyMerzlyakov commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +Values less than 255 will be interpreted as free cells when processed (but will not be distorted in the cost map).
> I suppose there is no need to explain here when NO_INFORMATION is an obstacle, because it is a small detail?

I also think so.

2023-02-03 12:31 UTC, ryzhikovas commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +will be interpreted as obstacle cell. Cells with any other values will be interpreted as ``FREE_SPACE`` when processed.
https://github.com/ros-planning/navigation.ros.org/pull/209/commits/4ac0320c382fdf14f61ddf835075199261911bf4

2023-03-21 21:18 UTC, ryzhikovas commented
@SteveMacenski, @AlexeyMerzlyakov, does this pull request still have a chance of being accepted? If yes, I will keep this PR relevant for the main branch.

2023-03-22 15:54 UTC, SteveMacenski commented
Yes, Alexey messaged me last week about reviewing this after he's given his approvals and its my plan to do it the week after next (unfortunately, I'm no longer at Samsung Research so my time for reviewing large scale changes is limited between other responsibilities). 

@AlexeyMerzlyakov what would help me greatly is if you reviewed your review comments and "Resolve" the ones that are completed to your satesfaction already so that they're no longer expanded in the thread. That way, I can look at only the ones that are not yet complete while I read through the full thread in detail as I'm reviewing the code for context. It would be good to know with certainty which are "done" and which might have been forgotten about.

2023-03-23 07:12 UTC, AlexeyMerzlyakov commented
> @AlexeyMerzlyakov what would help me greatly is if you reviewed your review comments and "Resolve" the ones that are completed to your satisfaction already

It looks like I have no access or rights to do that. The PR review items do not have "Resolve" button anymore:
![Screenshot_2023-03-23_10-08-57](https://user-images.githubusercontent.com/60094858/227129807-d5de5bca-991c-4017-9ebd-711e5dba0841.png)

2023-04-07 07:56 UTC, AlexeyMerzlyakov commented on configuration/packages/costmap-plugins/denoise.rst
> +Denoise Layer Parameters
https://github.com/ros-planning/navigation.ros.org/pull/209/commits/18ade8d885022c30fddf6ec62bee61d3f0deada2 after rebase

2023-04-07 07:56 UTC, AlexeyMerzlyakov commented on plugin_tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +Denoise Layer is Costmap2D plugin. You can enable the ``DenoiseLayer`` plugin in Costmap2D by adding ``denoise_layer`` to the ``plugins`` parameter in ``nav2_params.yaml``. You can place it in the ``
https://github.com/ros-planning/navigation.ros.org/pull/209/commits/68827ccc5852f658ce3bcc19fc792ba924676e2f after rebase

2023-04-07 08:05 UTC, AlexeyMerzlyakov commented
@SteveMacenski, thank you for the support!
I've closed all resolved items. [One](https://github.com/ros-planning/navigation.ros.org/pull/209#discussion_r861194104) is remained to check that this is exactly what you expect.

2023-04-18 16:25 UTC, SteveMacenski requested changes

2023-04-18 16:25 UTC, SteveMacenski commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +Filtering of noise-induced obstacles
```suggestion
Filtering of Noise-Induced Obstacles
```

2023-04-18 16:25 UTC, SteveMacenski commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +Incorrect definition of the robot position on the map or noisy sensor measurements can cause to errors in ``Voxel Layer`` or ``Obstacle Layer``. As a result, salt and pepper noise may appear on the c
```suggestion
Noisy sensor measurements can cause to errors in ``Voxel Layer`` or ``Obstacle Layer``. As a result, salt and pepper noise may appear on the costmap. This noise creates false obstacles that prevent the robot from finding the best path on the map. While the images above show both salt and pepper noise as well as error due to mislocalization, this layer will only remove sensor noise, not mislocalized artifacts misaligned with the static map.
```

2023-04-18 16:25 UTC, SteveMacenski commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +It is important to note that ``DenoiseLayer`` typically should be placed before inflation_layer.
```suggestion
It is important to note that ``DenoiseLayer`` typically should be placed before the inflation layer.
```

2023-04-18 16:25 UTC, SteveMacenski commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +Moreover, ``DenoiseLayer`` treated costmap as a binary map.
```suggestion
Moreover, ``DenoiseLayer`` processes only obstacle information in the costmap.
```

2023-04-18 16:25 UTC, SteveMacenski commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +  This feature can’t be considered problem, but is worth be taken into account.
```suggestion
  It is worth taking this into account as an application designer.
```

2023-04-18 16:25 UTC, SteveMacenski commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +  Use this plugin to filter the global costmap with caution. Firstly, it introduces performance-related risks.
```suggestion
  Use this plugin to filter the global costmap with caution. Firstly, it introduces potential performance issues.
```

2023-04-18 16:25 UTC, SteveMacenski commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +  Secondly, if salt and pepper noise is present in the local costmap, it disappears and is not remembered when going back into that region
I don't think this secondly sentence is necessary, remove L81-83.

2023-04-25 08:48 UTC, ryzhikovas commented on tutorials/docs/filtering_of_noise-induced_obstacles.rst
> +  Secondly, if salt and pepper noise is present in the local costmap, it disappears and is not remembered when going back into that region
3cd2571

2023-04-25 08:52 UTC, ryzhikovas commented
Thank you for the exact wording. The small number of edits is the merit of Alexey, who helped a lot with the documentation at an early stage.

2023-04-26 22:18 UTC, SteveMacenski approved these changes
Approved pending code review itself

2023-05-12 06:49 UTC, merged