Fixed example for AMCL initial pose settings
ros-planning/navigation.ros.org pull request #270
Opened 2022-02-03 12:54 UTC by moooeeeep

The previous example didn't really translate to the yaml format that has to be filled in there.

2022-02-03 13:38 UTC, moooeeeep commented
Looking at other doc entries, it seems the format given in those tables is supposed to resemble C++ list-initialization instead of actual yaml format. So probably I misunderstood the format of these entries.

I feel giving yaml snippets there would be more useful, but others might disagree. Probably one should adjust this consistently (if at all), which this PR obviously doesn't attempt. Feel free to discuss/close.

2022-02-03 18:07 UTC, SteveMacenski requested changes

2022-02-03 18:07 UTC, SteveMacenski commented on configuration/packages/configuring-amcl.rst
> +  Pose2D         {x: 0.0, y: 0.0, z: 0.0, yaw: 0.0}
You need to extend the `===` and `---` lines so that the formatting of the table renders properly. See other examples in the file essentially the lengths of the fields need to match the structure of the table.

2022-02-04 07:25 UTC, moooeeeep commented on configuration/packages/configuring-amcl.rst
> +  Pose2D         {x: 0.0, y: 0.0, z: 0.0, yaw: 0.0}
No problem. I adjusted the markup accordingly.

2022-02-04 07:27 UTC, SteveMacenski approved these changes
Much appreciated, thanks!!

2022-02-04 07:27 UTC, merged