Added first_map_only parameter in docs
ros-planning/navigation.ros.org pull request #284
Opened 2022-03-02 18:23 UTC by hardesh

Adresses #281

2022-03-07 18:36 UTC, SteveMacenski requested changes

2022-03-07 18:36 UTC, SteveMacenski commented on configuration/packages/configuring-amcl.rst
> +:first_map_only_:
No underscore, then LGTM!

2022-03-07 18:36 UTC, SteveMacenski commented on configuration/packages/configuring-amcl.rst
> +        first_map_only_: false
Remove the underscore here too!

2022-03-08 02:22 UTC, hardesh commented on configuration/packages/configuring-amcl.rst
> +:first_map_only_:
Hi Steve,
I think we'll have to change it in the code as well https://github.com/ros-planning/navigation2/blob/0a961df9cbe50356484877681abfdbeae6ba7b33/nav2_amcl/src/amcl_node.cpp#L1058

2022-03-08 02:23 UTC, hardesh commented on configuration/packages/configuring-amcl.rst
> +:first_map_only_:
only this parameter has underscore after it

2022-03-08 20:57 UTC, SteveMacenski commented on configuration/packages/configuring-amcl.rst
> +:first_map_only_:
https://github.com/ros-planning/navigation2/blob/6522fed52926f240736d628d28c11a0be8f238cb/nav2_amcl/src/amcl_node.cpp#L1058

oof, yeah that would be good to correct, thanks for bringing that up. Yes, we should remove the underscore here. That was clearly a copy-paste error when it was being ported from ROS 1. Thanks for mentioning that!

2022-03-21 18:14 UTC, SteveMacenski commented
Any update?

2022-03-26 10:42 UTC, hardesh commented
Should I also open a PR in nav2? I thought you were going to take this up :grimacing: 

Also if I fix this it'll be merged in `main` and it can't be backported to foxy right?

2022-03-26 10:43 UTC, hardesh commented
I can open a PR in nav2 tomorrow

2022-03-26 19:57 UTC, SteveMacenski commented
Yeah, opening a PR would be great! 

And no, unfortunately it can’t be backported since it would change behavior suddenly

2022-03-29 18:30 UTC, merged

2022-03-29 18:31 UTC, SteveMacenski commented
@hardesh Thanks for the PRs and pointing out this issue, it is much appreciated! :small_airplane:

2022-04-01 15:45 UTC, hardesh commented
No problem! :smiley: