Mixed replan
ros-planning/navigation.ros.org pull request #288
Opened 2022-03-11 19:49 UTC by jwallace42

Added documentation to support the new PathExpiringTimer condition BT node.

2022-03-14 20:50 UTC, SteveMacenski commented on configuration/packages/configuring-bt-xml.rst
> +  bt-plugins/conditions/PathExpiringTimer.rst
This is also missing from the plugins page

2022-03-14 20:51 UTC, SteveMacenski commented
See the checklist on the main PR for documentation things missing (migration guide, plugins page)

2022-03-19 16:36 UTC, jwallace42 commented
So, I think I got in all the doc changes. 

I think we should do a separate pr for the walk through page. 
This will also need a nav2 pr for the bt_navigator file path change. 

We could link the above two together.

2022-03-21 17:44 UTC, SteveMacenski commented on configuration/packages/bt-plugins/conditions/PathExpiringTimer.rst
> +    <PathExpiringTimer path="{path}"/>
Missing seconds

2022-03-21 17:47 UTC, SteveMacenski commented on behavior_trees/index.rst
> -   trees/nav_to_pose_and_replan_if_path_invalid.rst
Also, add the new BT + changes to the migration guide

2022-03-21 17:52 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_and_constant_replanning_and_if_path_becomes_invalid.rst
> +In nominal execution, replanning can be triggered by an a invalid previous path, a new goal or if a new path has not been created for 15 seconds.
```suggestion
In nominal execution, replanning is triggered by the path becoming invalid (e.g. in collision), a new goal is received, or after 15 seconds to refine the path occasionally during execution.
```

2022-03-21 17:53 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_and_constant_replanning_and_if_path_becomes_invalid.rst
>  However, this time, if the planner fails, it will trigger contextually aware recoveries in its subtree, clearing the global costmap.
This continuance of the paragraph doesn't make sense anymore with your changes from the original other BT page you copy pasted this from. I think this needs to be a new paragraph and changing the wording to make sense. There is no "this time" in this paragraph / previous explanation

2022-03-23 14:03 UTC, jwallace42 commented
Sorry about that. I didn't realize that the BT had changed so much. The section sounds pretty good now let me know if you have any other suggestions.

2022-03-23 21:08 UTC, SteveMacenski commented on migration/Galactic.rst
> +'<https://github.com/ros-planning/navigation2/pull/2591>' to allow for constant replanning and replanning if the path is invalid.
This doesn't render, the link isn't in the right format. It would be nice to also explain a little more about the new BT, not just the new node :smile:

2022-03-23 21:08 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_and_constant_replanning_and_if_path_becomes_invalid.rst
> +Navigate To Pose And Constant Replanning And If Path Becomes Invalid
"With" constant replanning, I think is the right terminology we've used in the past

2022-03-23 21:08 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_and_constant_replanning_and_if_path_becomes_invalid.rst
> +Navigate To Pose And Constant Replanning And If Path Becomes Invalid
Mostly also so that we don't have 2 "and"s in the title

2022-03-23 21:08 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_and_constant_replanning_and_if_path_becomes_invalid.rst
> +Navigate To Pose And Constant Replanning And If Path Becomes Invalid
Maybe ` Navigate To Pose with Consistent Replanning and If Path Becomes Invalid`?

2022-03-23 21:08 UTC, SteveMacenski commented on migration/Galactic.rst
> +'<https://github.com/ros-planning/navigation2/pull/2591>' to allow for constant replanning and replanning if the path is invalid.
The first one in L259 does though, so use that format

2022-03-24 18:55 UTC, SteveMacenski approved these changes
LGTM - just needs the merge conflict resolved

2022-03-24 18:57 UTC, SteveMacenski requested changes

2022-03-24 18:57 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.rst
> +		          <PathExpiringTimer seconds="15" path="{path}"/>
Change to 10s

2022-03-24 18:57 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.rst
> +In nominal execution, replanning can be triggered by an a invalid previous path, a new goal or if a new path has not been created for 15 seconds.
15->10

2022-03-28 18:48 UTC, SteveMacenski approved these changes

2022-03-28 18:48 UTC, SteveMacenski commented
@jwallace42 pull in master so CI turns over, there was a bug before. Then I can visually inspect and merge

2022-03-28 19:08 UTC, merged