adding documentation for BT node path_longer_on_approach
ros-planning/navigation.ros.org pull request #289
Opened 2022-03-15 09:50 UTC by padhupradheep

2022-03-15 19:56 UTC, SteveMacenski commented on plugins/index.rst
> +| `PathLongerOnApproach`_  | Pradheep Padmanabhan| Triggers child nodes if the new  |
Mention `On approach to the goal`

2022-03-15 19:56 UTC, SteveMacenski commented on migration/Galactic.rst
> +.. image:: images/nav2_patience_near_goal_and_clear_obstacle.gif
These gifs are great! We should make a new BT page to discuss this new BT and these gifs would also come in handy there. 

You should also link the configuration pages to that new BT description page so that they can see it in application

2022-03-15 19:56 UTC, SteveMacenski commented on migration/Galactic.rst
> +In the `PR <https://github.com/ros-planning/navigation2/pull/2802>`_, a new Decorator BT node known as ``PathLongerOnApproach`` has been added to provide with the functionality to check and potential
You need double "`" to render as code in rst format

2022-03-15 19:57 UTC, SteveMacenski commented on migration/Galactic.rst
> +.. image:: images/nav2_patience_near_goal_and_clear_obstacle.gif
https://navigation.ros.org/behavior_trees/index.html new page should go under here. Add a new entry after [Navigate To Pose and Replan Only if Path Invalid](https://navigation.ros.org/behavior_trees/trees/nav_to_pose_and_replan_if_path_invalid.html) and add the description / image / gifs

2022-03-16 19:00 UTC, SteveMacenski commented
Just need the new tree page and LGTM

2022-03-21 18:04 UTC, SteveMacenski requested changes
I had some suggestions that you should take, but might be worth re-reading that first paragraph and trying to better explain the role of this for a practical utility for users. Its important its clear what it is doing and why from the start

2022-03-21 18:04 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_and_pause_near_goal_obstacle.rst
> +In addition, this behavior tree allows the robot to efficently handle the dynamic obstacle closer to the goal proximity on approach by pausing the robot's navigation and wait until the obstacle has c
```suggestion
In addition, this behavior tree allows the robot to efficiently handle an obstacle (e.g. forklift, person, or other temporary obstacle) close to the goal by pausing the robot's navigation and wait until the obstacle has cleared.
```

2022-03-21 18:04 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_and_pause_near_goal_obstacle.rst
> +navigating along a significantly longer path to reach the goal location.
```suggestion
Then, the robot will continue to the goal after the obstacle has moved. If the obstacle is unmoved, navigation will continue using the longer path around to reach the final goal location.
```

2022-03-22 09:12 UTC, padhupradheep commented
> I had some suggestions that you should take, but might be worth re-reading that first paragraph and trying to better explain the role of this for a practical utility for users. Its important its clear what it is doing and why from the start

Sure, let me give it some more thoughts!

2022-03-22 13:06 UTC, padhupradheep commented
I changed the contents in the first para. Now, it introduces, what it does ? and why is it needed ? do let me know your thoughts. I can try to improve it further.

2022-03-22 18:43 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_and_pause_near_goal_obstacle.rst
> +Ultimately, this behavior tree aids in solving the problem of long cycle time, caused because of the long path generated due to the temporary obstacles present close to the goal location.
What is "long cycle time"?

2022-03-22 18:43 UTC, SteveMacenski commented on behavior_trees/trees/nav_to_pose_and_pause_near_goal_obstacle.rst
> +Apart from the functionalities of :ref:`behavior_tree_nav_to_pose`, this behavior tree allows the robot to efficiently handle an obstacle (e.g. forklift, person, or other temporary obstacle) close to
It doesn't "wait until..." it waits a fixed amount of time. This implies that it will be checking if its gone

2022-03-22 18:54 UTC, padhupradheep commented on behavior_trees/trees/nav_to_pose_and_pause_near_goal_obstacle.rst
> +Ultimately, this behavior tree aids in solving the problem of long cycle time, caused because of the long path generated due to the temporary obstacles present close to the goal location.
Cycle time of a process that the robot tries to achieve.

2022-03-22 19:10 UTC, padhupradheep commented on behavior_trees/trees/nav_to_pose_and_pause_near_goal_obstacle.rst
> +Ultimately, this behavior tree aids in solving the problem of long cycle time, caused because of the long path generated due to the temporary obstacles present close to the goal location.
I meant the process time that the robot is taking…

2022-03-23 16:32 UTC, padhupradheep commented
I still want to work on it a bit, so you can safely skip the last commit.

2022-03-23 17:13 UTC, padhupradheep commented on behavior_trees/trees/nav_to_pose_and_pause_near_goal_obstacle.rst
> +Ultimately, this behavior tree aids in solving the problem of long cycle time, caused because of the long path generated due to the temporary obstacles present close to the goal location.
Could just give me an idea here, if is it okay to use "cycle time" or is it bit confusing?

2022-03-28 19:01 UTC, SteveMacenski commented
Let me know when you want me to take a look

2022-03-29 09:05 UTC, padhupradheep commented
Now it's time for you to take a look. I think, I'm blinded now to find mistakes.

2022-03-29 19:02 UTC, SteveMacenski requested changes
Otherwise LGTM now!

2022-03-30 09:20 UTC, padhupradheep commented on behavior_trees/index.rst
> +   trees/nav_to_pose_and_replan_if_path_invalid.rst
Ah it is in line 15, I should have added it by mistake, while doing the merge. Damn I did it again.. Psst!!

2022-03-30 18:08 UTC, SteveMacenski approved these changes

2022-03-30 18:08 UTC, merged