Recovery to behavior
ros-planning/navigation.ros.org pull request #298
Opened 2022-03-30 17:59 UTC by jwallace42

2022-03-30 18:55 UTC, SteveMacenski requested changes
Migration page: 

I think the migration guide needs a section regarding the behaviors recovery transition and renamed plugin names for users to know how to port the changes. 
- Launch files lifecycle manager need behavior_server not recovery_server
- yaml needs behavior_server not recovery_server
- yaml needs plugin namespaces changed
- Anything else?

2022-03-30 18:55 UTC, SteveMacenski commented on configuration/packages/configuring-behavior-server.rst
Add a note that pre-Rolling/Humble this was the Recovery server, not behavior. Some points as to places that it was renamed to help users

2022-03-30 18:55 UTC, SteveMacenski commented on behavior_trees/overview/nav2_specific_nodes.rst
> +* Spin, Wait, Backup - Action Server Client
Add behaviors

2022-03-30 18:55 UTC, SteveMacenski commented on concepts/index.rst
> +Recovery behaviors are a mainstay of fault-tolerant systems.
Also mention this server can host non-recovery behaviors, its a generalized behavior server to share expensive resources like costmaps, TF buffers, etc and allows each behavior to act independently and with its own API

2022-03-31 20:29 UTC, jwallace42 commented
> It doesn't look like you fixed many of the review comments?
> 
> > Nope, that was everything!
> 
> But be specific about what exactly to change

Like the names of the files?

2022-04-04 21:30 UTC, SteveMacenski commented on concepts/index.rst
> +It is important to note that the behavior server can hold any behavior that need access to costmap or TF buffer not just recovery behaviors.
```suggestion
It is important to note that the behavior server can hold any behavior to share access to expensive resources like costmaps or TF buffers, not just recovery behaviors. Each may have their own API.
```

2022-04-04 21:35 UTC, SteveMacenski approved these changes

2022-04-04 21:35 UTC, merged