Constrained smoother and TruncatePathLocal BT Node
ros-planning/navigation.ros.org pull request #308
Opened 2022-05-05 11:00 UTC by afrixs

2022-05-06 19:08 UTC, SteveMacenski commented
2 changes missing:

Need to add the BT node and the Smoother algorithm to the tables in the navigation algorithms page: https://github.com/ros-planning/navigation.ros.org/blob/master/plugins/index.rst. For the BT node, its all you, but for the smoother add both of our names since it was based on my initial work in Smac. 

Also need migration guide update to mention that hey this exists with a short description and a link to the configuration / PR.

2022-05-06 19:15 UTC, SteveMacenski requested changes
Love it, really only a couple of changes but otherwise LGTM

2022-05-06 19:15 UTC, SteveMacenski commented on configuration/packages/bt-plugins/actions/TruncatePathLocal.rst
> +:transform_tolerance:
Transform tolerance appears twice

2022-05-06 19:15 UTC, SteveMacenski commented on configuration/packages/bt-plugins/actions/TruncatePathLocal.rst
> +:max_robot_pose_search_dist:
I think this is an input port?

Also, I think this is missing the output port for the `output_path`

2022-05-06 19:15 UTC, SteveMacenski commented on configuration/packages/configuring-constrained-smoother.rst
> +.. image:: images/constrained_smoother/constrained_smoother.png
Make a note that the blue is original, green is smoothed (what's red?)

Also, make a note that the blue is a particularly bad example of a path to highlight the power of the smoother (that's not a usually expected output of Smac in its current form in Nav2)

2022-05-06 19:15 UTC, SteveMacenski commented on configuration/packages/configuring-constrained-smoother.rst
> +  double         30.0
Are these weights all tuned and reasonable default values? Just checking, we care alot about out-of-the-box quality in Nav2

2022-05-09 13:40 UTC, afrixs commented on configuration/packages/configuring-constrained-smoother.rst
> +  double         30.0
Yes, I think the smoother gives pretty good results with these values.

2022-05-09 13:47 UTC, afrixs commented on configuration/packages/configuring-constrained-smoother.rst
> +.. image:: images/constrained_smoother/constrained_smoother.png
The red is irrelevant here (it's published by our internal controller). Frankly, I just found this image among some old screenshots, didn't spend time creating a clearer one without extra visualizations... But I considered it good enough as an example, that's why I put it there...

Added the notes

2022-05-09 18:31 UTC, SteveMacenski commented
Changes are approved but still missing the 2 items from the comment above; 


```
Need to add the BT node and the Smoother algorithm to the tables in the navigation algorithms page: https://github.com/ros-planning/navigation.ros.org/blob/master/plugins/index.rst. For the BT node, its all you, but for the smoother add both of our names since it was based on my initial work in Smac.

Also need migration guide update to mention that hey this exists with a short description and a link to the configuration / PR.
```

2022-05-10 17:53 UTC, merged