change plugin tutorials for humble
ros-planning/navigation.ros.org pull request #316
Opened 2022-05-27 21:50 UTC by Ryujiyasu

Fix points

1. change "Recovery" to "Behavior"
2. delete  Eloquent and earlier info (because EOL version)

2022-05-27 22:56 UTC, SteveMacenski requested changes

2022-05-27 22:56 UTC, SteveMacenski commented on plugin_tutorials/docs/writing_new_behavior_plugin.rst
> +3- Pass the plugin name through params file (Galactic and earlier)
Humble and newer should be first, then the second copy of Galactic and older should just specify the changes to the Humble and newer code block (e.g. change `behavior_server` to `recovery_server` in namespace, but that's it?). We don't need to make this excessively long

2022-05-29 00:03 UTC, Ryujiyasu commented on plugin_tutorials/docs/writing_new_behavior_plugin.rst
> +3- Pass the plugin name through params file (Galactic and earlier)
ok

2022-05-30 06:23 UTC, Ryujiyasu commented on plugin_tutorials/docs/writing_new_behavior_plugin.rst
> +3- Pass the plugin name through params file (Galactic and earlier)
- [ ] Humble and newer ->first
- [ ] shorten sentence

thank you!!

2022-05-31 18:33 UTC, SteveMacenski reviewed
LGTM, just 2 small changes

2022-05-31 18:33 UTC, SteveMacenski commented on plugin_tutorials/docs/writing_new_behavior_plugin.rst
> +--------------------------------------------------------------
This line needs to be reset to the same length as the message above it (or the compiler complains)

2022-05-31 18:33 UTC, SteveMacenski commented on plugin_tutorials/docs/writing_new_behavior_plugin.rst
> +To enable the plugin, we need to modify the ``nav2_params.yaml`` file as below to replace following params_file
```suggestion
To enable the plugin, we need to modify the ``nav2_params.yaml`` file as below to replace following params
```

2022-05-31 21:40 UTC, Ryujiyasu commented on plugin_tutorials/docs/writing_new_behavior_plugin.rst
> +--------------------------------------------------------------
OK

2022-05-31 21:43 UTC, Ryujiyasu commented on plugin_tutorials/docs/writing_new_behavior_plugin.rst
> +To enable the plugin, we need to modify the ``nav2_params.yaml`` file as below to replace following params_file
ok

2022-05-31 22:37 UTC, SteveMacenski approved these changes

2022-05-31 22:37 UTC, merged

2022-05-31 22:37 UTC, SteveMacenski commented
Thanks!