Add Collision Monitor documentaiton pages
ros-planning/navigation.ros.org pull request #333
Opened 2022-07-14 08:20 UTC by AlexeyMerzlyakov

This pull request is a documentation update for the https://github.com/ros-planning/navigation2/pull/2982.
Contains: migration guide, parameters description, usage tutorial.

2022-07-15 19:52 UTC, SteveMacenski requested changes

2022-07-15 19:52 UTC, SteveMacenski commented on migration/Galactic.rst
> +***********************
Make a new `Humble` migration guide page for this

2022-07-15 19:52 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +Collision Monitor - is an independent layer in Nav2 providing an additional level of robot safety assurance.
Update with README's requested introduction changes

2022-07-15 19:52 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +Collision Monitor - is an independent layer in Nav2 providing an additional level of robot safety assurance.
In general below, apply changes I made to the readme here

2022-07-15 19:52 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +- **Slowdown model**: Define a safety area around the robot and slow the maximum speed for a ``slowdown_ratio``, if more than ``max_points`` points will appear inside the area.
```suggestion
- **Slowdown model**: Define a safety area around the robot and slow the maximum speed by a ``slowdown_ratio``, if more than ``max_points`` points will appear inside the area.
```

2022-07-15 19:52 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +    List of safety area shapes (stop/slowdown bounding boxes, footprint, approach circle, etc...). Causes an error, if not specialized.
Zones, remove the phrase "safety area" from all docs, we should avoid the word "safety"

2022-07-15 19:52 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +    List of data sources (llaser scanners, pointclouds, etc...). Causes an error, if not specialized.
```suggestion
    List of data sources (laser scanners, pointclouds, etc...). Causes an error, if not specialized.
```

2022-07-15 19:52 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +    Polygon vertexes, listed in ``{p1.x, p1.y, p2.x, p2.y, p3.x, p3.y, ...}`` format. Used for ``polygon`` type. Minimum 3 points for a triangle polygon. Causes an error, if not specialized.
Give an example box

2022-07-15 19:52 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +    Safety behavior model. Available values are ``stop``, ``slowdown``, ``approach``. Causes an error, if not specialized.
```suggestion
    Zone model. Available values are ``stop``, ``slowdown``, ``approach``. Causes an error, if not specialized.
```

2022-07-15 19:52 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +    Maximum number of points to enter inside polygon to be ignored (w/o causing an action).
```suggestion
    Number of data readings within a zone to trigger the action
```

2022-07-15 19:52 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +  string         "footprint"
I don't think that's a sensible default, use the topic the local costmap publishes with the footprint

2022-07-15 20:03 UTC, SteveMacenski requested changes

2022-07-15 20:03 UTC, SteveMacenski commented on tutorials/docs/using_collision_monitor.rst
> +Since Collision Monitor is designed to operate as an independent safety node, Nav2 stack has no knowledge about it.
Updates w.r.t. readme

2022-07-15 20:03 UTC, SteveMacenski commented on tutorials/docs/using_collision_monitor.rst
> +    +                  ('/cmd_vel', '/cmd_vel_raw')]
Don't globally remap the topic, remap only in the controller server's node that its output is now `cmd_vel_raw`

2022-07-15 20:03 UTC, SteveMacenski commented on tutorials/docs/using_collision_monitor.rst
> +Since Collision Monitor performs effectively to avoid collisions, we need to increase the probability of it, e.g. by allowing the robot to get closer to the obstacles.
Remove all of this, we should not intentionally make it easier for the robot to get into collision, even for demonstration purposes.

2022-07-15 20:03 UTC, SteveMacenski commented on tutorials/docs/using_collision_monitor.rst
> +Since Collision Monitor performs effectively to avoid collisions, we need to increase the probability of it, e.g. by allowing the robot to get closer to the obstacles.
Many people will read this as a "oh, I can leave this lower now" rather than only for the purposes of making it trigger 1 time to show it working. 

If you want to show a video with reduced inflation showing this node working to slow down / stop the robot, that's a useful video, but I wouldn't ask people to do that themselves. Just show it working

2022-07-18 08:59 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-collision-monitor.rst
> +    Maximum number of points to enter inside polygon to be ignored (w/o causing an action).
The question about the change: should this parameter to be a number of a points, *starting from* an action will be triggered, or maximum number of points *to be ignored before* an action? According to the initial task description from the ticket 1899:

> Define a bounding box and a point threshold and if > N points appear in this box in front of the robot, stop it. Usually with a larger bounding box in front of the stop box to warn of a collision and slow the maximum speeds.

It is second definition. Means, that if `> max_points` will enter inside polygon, the action will be triggered.

If read the proposed definition,
> Number of data readings within a zone to trigger the action

it should be `>= max_points` to trigger an action.

To fit initial conditions, making the following change in docs instead:
```
- Maximum number of points to enter inside polygon to be ignored (w/o causing an action).
+ Maximum number of data readings within a zone to not trigger the action
```
Please let me know, if this number should have another meaning.

2022-07-18 15:58 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-collision-monitor.rst
> +    List of safety area shapes (stop/slowdown bounding boxes, footprint, approach circle, etc...). Causes an error, if not specialized.
Remove all phrases in docs and README (changed to "zones" or similar)

2022-07-18 15:59 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-collision-monitor.rst
> +    Polygon vertexes, listed in ``{p1.x, p1.y, p2.x, p2.y, p3.x, p3.y, ...}`` format. Used for ``polygon`` type. Minimum 3 points for a triangle polygon. Causes an error, if not specialized.
[Done](https://github.com/ros-planning/navigation.ros.org/pull/333/files#diff-60e7d74687df0b5a07a3d91dc411c686e266df32edbdb653cf6e2ffc2674bc7cR175)

2022-07-18 15:59 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-collision-monitor.rst
> +    Safety behavior model. Available values are ``stop``, ``slowdown``, ``approach``. Causes an error, if not specialized.
[Changed](https://github.com/ros-planning/navigation.ros.org/pull/333/files#diff-60e7d74687df0b5a07a3d91dc411c686e266df32edbdb653cf6e2ffc2674bc7cR197) to "Zone behavior model"

2022-07-18 16:00 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-collision-monitor.rst
> +  string         "footprint"
[Changed](https://github.com/ros-planning/navigation.ros.org/pull/333/files#diff-60e7d74687df0b5a07a3d91dc411c686e266df32edbdb653cf6e2ffc2674bc7cR270) to "local_costmap/published_footprint"

2022-07-18 16:03 UTC, AlexeyMerzlyakov commented on tutorials/docs/using_collision_monitor.rst
> +Since Collision Monitor performs effectively to avoid collisions, we need to increase the probability of it, e.g. by allowing the robot to get closer to the obstacles.
Removed the reference, but remained `0.02` inflation radius in all visual examples

2022-07-19 18:54 UTC, SteveMacenski approved these changes
Just that last nit change in the un-resolved comment!

2022-07-20 10:04 UTC, AlexeyMerzlyakov commented
If you are talking about https://github.com/ros-planning/navigation.ros.org/pull/333#discussion_r923114276, it is [ready ](https://github.com/ros-planning/navigation.ros.org/pull/333/files#diff-60e7d74687df0b5a07a3d91dc411c686e266df32edbdb653cf6e2ffc2674bc7cR208)(also [updated](https://github.com/ros-planning/navigation2/pull/2982/files#diff-d3d7f7e1c461b03d4a5868bd2766b722163399e0cb51227319a5b24e7cb8a434R178) in the code comments for the variable in header).

2022-07-20 17:58 UTC, merged