update Costmap API documentation
ros-planning/navigation.ros.org pull request #344
Opened 2022-09-07 19:45 UTC by JacksonK9

update Costmap API documentation as the Pull Request of navigation2

[#navigation2/31](https://github.com/ros-planning/navigation2/pull/3169#issue-1361167645)

2022-09-08 16:57 UTC, SteveMacenski requested changes

2022-09-08 16:57 UTC, SteveMacenski commented on commander_api/index.rst
> +| setCost(mx, my, cost)                 | Set the cost (``np.int8``) of a cell in the costmap using mx(``int``),     |
Why is this one np.int8 but others are just straight ints?

2022-09-08 16:57 UTC, SteveMacenski commented on commander_api/index.rst
> +| getCostXY(mx, my)                     | Get the cost (``int``) of a cell in the costmap using mx(``int``),         |
Make the units similar to above, where they're in square brackets, ex

Get the cost [int] of a cell in the costmap using mx [int].

2022-09-08 16:57 UTC, SteveMacenski commented on commander_api/index.rst
> +| getCostXY(mx, my)                     | Get the cost (``int``) of a cell in the costmap using mx(``int``),         |
And make sure to have a space between the "thing" (mx, my, etc) and the units. Some are butted against each other

2022-09-08 22:30 UTC, JacksonK9 commented on commander_api/index.rst
> +| setCost(mx, my, cost)                 | Set the cost (``np.int8``) of a cell in the costmap using mx(``int``),     |
The type of costmap is np.array of np.int8.
So I pointed that detail, But we can use just straight int.
Do you think I should change to Int? or Just leave it?

2022-09-08 23:41 UTC, SteveMacenski commented on commander_api/index.rst
> +| setCost(mx, my, cost)                 | Set the cost (``np.int8``) of a cell in the costmap using mx(``int``),     |
uint seems right, since negative values are invalid

2022-09-08 23:43 UTC, JacksonK9 commented on commander_api/index.rst
> +| setCost(mx, my, cost)                 | Set the cost (``np.int8``) of a cell in the costmap using mx(``int``),     |
Okay I will change all the int type to np.uint8 and notify again.
Thank you for your comment 👍

2022-09-09 12:36 UTC, JacksonK9 commented
I think document show the type with (``np.uint8``) and unit with [m].

So I add the type and unit to the document of commander api.

Thank you.

2022-09-09 17:12 UTC, SteveMacenski requested changes

2022-09-09 17:12 UTC, SteveMacenski commented on commander_api/index.rst
> +| getCostXY(mx, my)                     | Get the cost (``np.uint8``) of a cell in the costmap using mx (``int``)    |
again, units in square brackets.

2022-09-09 17:13 UTC, SteveMacenski requested changes

2022-09-09 17:13 UTC, SteveMacenski commented on commander_api/index.rst
> +| getCostIdx(index)                     | Get the cost (``np.uint8``) of a cell in the costmap using index (``int``) |
Again, why are we mixing uints and ints?

2022-09-09 17:19 UTC, SteveMacenski commented on commander_api/index.rst
> +| getCostXY(mx, my)                     | Get the cost (``np.uint8``) of a cell in the costmap using mx (``int``)    |
Also, the actual API implementation uses `np.int8` not unsigned ints

2022-09-10 06:26 UTC, JacksonK9 commented on commander_api/index.rst
> +| getCostXY(mx, my)                     | Get the cost (``np.uint8``) of a cell in the costmap using mx (``int``)    |
As I check these two lines.

setInitialPose(initial_pose)          | Sets the initial pose (``PoseStamped``) of the robot to localization.  

getResolution()                       | Get map resolution [m/cell].      

So I think the "variable type" is using parentheses and the "unit" is using square bracket.

As a result, I change like the below line.

mapToWorld(mx, my)                    | Get the wx (``float``) [m], wy (``float``) [m] of world coordinate XY using

Should I change to "Get the wx [``float``] [m], wy [[``float``] [m] of world coordinate XY using" ?

Can you tell me which one is better?

Thank you for your comment.

2022-09-12 17:40 UTC, merged

2022-09-12 17:40 UTC, SteveMacenski approved these changes