piping error codes
ros-planning/navigation.ros.org pull request #365
Opened 2022-11-07 14:48 UTC by jwallace42

The the documentation for [#3251](https://github.com/ros-planning/navigation2/pull/3251).

2022-11-07 19:41 UTC, SteveMacenski requested changes

2022-11-07 19:41 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +Your nav2 server may also wish to return a error code. It is important to note that error codes from 0-99999 are reserved for internal nav2 servers. All servers are offest by 1000. The table below sh
If you have the inclination, if you read through this document and make changes do that it reads like a `Add New Nav2 Task Server` document, you can move this into the normal tutorials directory. Most likely just needs small changes on the front end with more detail on what the task server should do / the 3 elements in this document. 

If not, I can do it sometime this week

2022-11-07 19:41 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +
This should be its own subsection with a header

2022-11-07 19:57 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +
Also state all should contain NONE=0 if no error occurred

2022-11-07 19:57 UTC, SteveMacenski commented on migration/Humble.rst
> +`PR #3043 <https://github.com/ros-planning/navigation2/pull/3251>`_ pipes the highest priority error code through the bt_navigator. The lower the error code, the higher the priority. Error codes from
Add in the policy details and ranges for each task server here. Be robust / complete since this will be the first introduction to this people will experience

2022-11-08 13:24 UTC, jwallace42 commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +Your nav2 server may also wish to return a error code. It is important to note that error codes from 0-99999 are reserved for internal nav2 servers. All servers are offest by 1000. The table below sh
Alright, 

I will try to update it by the end of the week.

2022-11-09 22:27 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +A nav2 task server consists of server side logic to complete different types of requests. In this guide, we will discuss the core components needed to add a nav2 task server.
```suggestion
A nav2 task server consists of server side logic to complete different types of requests, usually called by the autonomy system or through the Behavior Tree Navigator. In this guide, we will discuss the core components needed to add a new task server to Nav2 (ex. Controller, Behavior, Smoother, Planner Servers). Namely, how to set up your new Lifecycle-Component Node for launch and state management and the communication of semantically meaningful error codes (if necessary). 

While this tutorial does not cover how to add the complementary Behavior Tree Node to interact with this new Task Server, that is covered at length in :ref:`writing_new_nbt_plugin` so this Task Server can be invoked in the BTs in BT Navigator.

If you've created a new Task Server that may have general reuse for the community, consider contacting the maintainers to add it to the Nav2 project! Nav2 gets better by contributions by users like you!

2022-11-09 22:28 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +    int16 UNKNOWN=100000 # Reserved for UNKNOWN
Is that the case? I'm not sure that's sensible since that would mean that UNKNOWN error (but still an errror) from the controller server is less important than a superficial error from the planner server

2022-11-09 22:30 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +Your nav2 task server may also wish to return a error code. It is important to note that error codes from 0-99999 are reserved for internal nav2 servers with each server offset by 1000. The table bel
```suggestion
Your nav2 task server may also wish to return a error code in its action response (though not required). If there are semantically meaningful and actionable types of failures for your system, this is a systemic way to communicate those failures which may be automatically aggregated into the responses of the navigation system to your application.

It is important to note that error codes from 0-99999 are reserved for internal nav2 servers with each server offset by 1000. The table below shows the current servers along with the expected error code structure.

```

2022-11-09 22:30 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +
You don't list the expected field name in the action definition its looking for

2022-11-09 22:30 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +
(error_code)

2022-11-09 22:30 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +
At least explicitly outside of the msg definition below

2022-11-09 22:31 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +
You don't mention adding it to the list in the BT Navigator parameter for querying

2022-11-09 22:32 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +| `Planner Server`_                   | 2000-2999              |
Add in parenthesis the differences between the 2 planner server ranges

2022-11-11 15:30 UTC, jwallace42 commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +    int16 UNKNOWN=100000 # Reserved for UNKNOWN
It would still be more important than a error from the planner server.

Controller Server would throw 1000 which would be less than anything thrown by the planner server(2000-3999) and thus be the dominate error code returned to the higher level autonomy system.

2022-11-11 18:26 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +    int16 UNKNOWN=100000 # Reserved for UNKNOWN
Actually looking at the code in the PR though, you don't have UNKNOWN set as 100k, so I'm not sure why its in this documentation :smile:

2022-11-11 18:36 UTC, jwallace42 commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +    int16 UNKNOWN=100000 # Reserved for UNKNOWN
Well this example isn't the controller server, it is a external server(route server) which the user is building.

2022-11-11 18:39 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +    int16 UNKNOWN=100000 # Reserved for UNKNOWN
Oh sorry, that comment about being reserved threw me off.

This is correct, just remove that reserved for unknown comment and add something a little different: `# First value in sequence should be UNKNOWN`. The word "reserved" shared with NONE as `0` implied to me that all UNKNOWN for all servers should be 100k - since that's what the message for NONE means.

2022-11-11 19:07 UTC, jwallace42 commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> +    int16 UNKNOWN=100000 # Reserved for UNKNOWN
Sorry for the confusion!

2022-11-14 19:03 UTC, SteveMacenski commented
All open comments are still remaining :smile:

2022-11-15 20:44 UTC, SteveMacenski commented on tutorials/docs/adding_a_nav2_task_server.rst
> +Your nav2 task server may also wish to return a 'error_code' in its action response (though not required). If there are semantically meaningful and actionable types of failures for your system, this
An empty line after a header is required

2022-11-15 20:44 UTC, SteveMacenski commented on tutorials/docs/adding_a_nav2_task_server.rst
> +| Last Nav2 server                                  | NONE=0, UNKNOWN=10000 | 10001-10099          |
Route Server?

2022-11-15 20:44 UTC, SteveMacenski commented on tutorials/docs/adding_a_nav2_task_server.rst
> +Error codes are attached to the response of the action message. An example can be seen below for the route server
```suggestion
Error codes are attached to the response of the action message. An example can be seen below for the route server. Note that by convention we set the error code field within the message definition to ``error_code``.

```

2022-11-15 20:44 UTC, SteveMacenski commented on migration/Humble.rst
> +The lowest error in the "error_code_id_names" is then returned in the action request(navigate to pose, navigate through poses waypoint follower).
```suggestion
The lowest error in the "error_code_id_names" is then returned in the action request (navigate to pose, navigate through poses waypoint follower), whereas the code enums increase the higher up in the software stack - giving higher priority to lower-level failures.
```

2022-11-15 20:44 UTC, SteveMacenski commented on tutorials/docs/adding_a_nav2_task_server.rst
> +The `error_code_id_names` define what error codes to compare. The lowest error code of the sequence is then returned.
```suggestion
The `error_code_id_names` define what error codes to compare. The lowest error code of the sequence is then returned - whereas the code enums increase the higher up in the software stack - giving higher priority to lower-level failures.

```

2022-11-18 19:21 UTC, SteveMacenski commented on migration/Humble.rst
>  The following error codes are supported (with more to come as necessary): Unknown, TF Error, Invalid Path, Patience Exceeded, Failed To Make Progress, or No Valid Control.
Missing BT Navigator's new error code vector parameter

2022-11-18 19:21 UTC, SteveMacenski commented on migration/Humble.rst
> +The lowest error in the "error_code_id_names" is then returned in the action request (navigate to pose, navigate through poses waypoint follower), whereas the code enums increase the higher up in the
```suggestion
The lowest error in the "error_code_id_names" is then returned in the action request (navigate to pose, navigate through poses, waypoint follower), whereas the code enums increase the higher up in the software stack - giving higher priority to lower-level failures.
```

2022-11-28 19:52 UTC, SteveMacenski commented on migration/Humble.rst
> +The lowest error in the "error_code_id_names" is then returned in the action request (navigate to pose, navigate through poses waypoint follower), whereas the code enums increase the higher up in the
```suggestion
The lowest error in the "error_code_id_names" is then returned in the action request (navigate to pose, navigate through poses, waypoint follower), whereas the code enums increase the higher up in the software stack - giving higher priority to lower-level failures.
```

2022-11-28 19:56 UTC, SteveMacenski commented on tutorials/docs/adding_a_nav2_task_server.rst
> +A nav2 task server consists of server side logic to complete different types of requests, usually called by the autonomy system or through the Behavior Tree Navigator. In this guide, we will discuss
```suggestion
A nav2 task server consists of server side logic to complete different types of requests, usually called by the autonomy system or through the Behavior Tree Navigator. In this guide, we will discuss the core components needed to add a new task server to Nav2 (ex. Controller, Behavior, Smoother, Planner Servers). Namely, how to set up your new Lifecycle-Component Node for launch and state management and the communication of semantically meaningful error codes (if necessary) to a behavior tree or application to be fully integrated into the framework. 

```

2022-11-28 19:57 UTC, SteveMacenski commented
Still just missing that 1 parameter and this is G2G

2022-12-07 19:05 UTC, jwallace42 commented on migration/Humble.rst
>  The following error codes are supported (with more to come as necessary): Unknown, TF Error, Invalid Path, Patience Exceeded, Failed To Make Progress, or No Valid Control.
My branch shows this change but the git diff does not.

2022-12-07 20:26 UTC, SteveMacenski commented on setup_guides/lifecycle_composition/setup_lifecycle_composition.rst
> -.. _lifecycle_composition:
Doesn't this page need to be removed from the index for trying to compile it (e.g. https://github.com/ros-planning/navigation.ros.org/blob/master/setup_guides/index.rst)

2022-12-07 20:26 UTC, SteveMacenski commented on migration/Humble.rst
>  The following error codes are supported (with more to come as necessary): Unknown, TF Error, Invalid Path, Patience Exceeded, Failed To Make Progress, or No Valid Control.
Can you try force pushing?

2022-12-07 20:26 UTC, SteveMacenski approved these changes

2022-12-07 20:29 UTC, SteveMacenski commented on migration/Humble.rst
>  The following error codes are supported (with more to come as necessary): Unknown, TF Error, Invalid Path, Patience Exceeded, Failed To Make Progress, or No Valid Control.
@jwallace42 I even went to your branch and I can't see the change there either. I think something didn't get pushed to Git, its not just the diff.

2022-12-07 22:24 UTC, jwallace42 commented
I think the force pushed worked. Sorry about that.

2022-12-08 00:58 UTC, SteveMacenski commented
I still don't see it, please redo it in this PR.

2022-12-08 15:12 UTC, jwallace42 commented on migration/Humble.rst
> +A new parameter for the the BT Navigator called "error_code_id_names" was added to the nav2_params.yaml to define the error codes to compare.
This is where I talk about the new bt navigator error code params.

2022-12-08 18:55 UTC, SteveMacenski commented on migration/Humble.rst
> +A new parameter for the the BT Navigator called "error_code_id_names" was added to the nav2_params.yaml to define the error codes to compare.
You're missing the BT navigator error codes new parameter in its configuration guide page for the BT navigator since its a new param that needs to be in our parameter description guide

2022-12-09 01:10 UTC, SteveMacenski requested changes
Then I'll merge! thansk!

2022-12-09 01:10 UTC, SteveMacenski commented on configuration/packages/configuring-bt-navigator.rst
> +          - follow_path_error_code
Add the line

```
# - path_smoother_error_code (or whatever this is)
```

The purpose being to document its a thing, even if its not on by default

2022-12-09 14:19 UTC, jwallace42 commented on configuration/packages/configuring-bt-navigator.rst
> +          - follow_path_error_code
added, it is not showing up in the diff but you can see it [here](https://github.com/jwallace42/navigation.ros.org/blob/pipe_error_codes/configuration/packages/configuring-bt-navigator.rst)

2022-12-09 19:08 UTC, SteveMacenski approved these changes

2022-12-09 19:08 UTC, SteveMacenski commented on configuration/packages/configuring-bt-navigator.rst
> +          - smoother_error_code
```suggestion
          # - smoother_error_code, navigate_to_pose_error_code, navigate_through_poses_error_code, etc
```

2022-12-09 19:08 UTC, SteveMacenski commented on migration/Humble.rst
> +The following errors codes are supported (with more to come as necessary): Unknown and Task Executor Failed.
```suggestion
The following errors codes are supported (with more to come as necessary): Unknown and Task Executor Failed.
See :ref:`adding_a_nav2_task_server` and the PR for additional information.
```

2022-12-09 19:08 UTC, SteveMacenski commented on tutorials/docs/adding_a_nav2_task_server.rst
> +The `error_code_id_names` define what error codes to compare. The lowest error code of the sequence is then returned - whereas the code enums increase the higher up in the software stack - giving hig
```suggestion
The `error_code_id_names` inside of the BT Navigator define what error codes to look for on the blackboard by the server. The lowest error code of the sequence is then returned - whereas the code enums increase the higher up in the software stack - giving higher priority to lower-level failures.

```

2022-12-09 19:08 UTC, merged