bump sphinx
ros-planning/navigation.ros.org pull request #367
Opened 2022-11-09 23:40 UTC by jwallace42

Pr to resolve #364.

2022-11-13 21:14 UTC, SteveMacenski requested changes

2022-11-13 21:14 UTC, SteveMacenski commented on .circleci/config.yml
> +        pip3 install sphinx==4.2.0 breathe sphinx_rtd_theme sphinxcontrib-plantuml jinja2==3.0.3
Version control breathe

2022-11-13 21:14 UTC, SteveMacenski commented on .circleci/config.yml
> -        pip3 install sphinx==3.5.0 docutils==0.14 sphinx_rtd_theme breathe==4.28.0 sphinxcontrib-plantuml jinja2==3.0.3
Do we not need docutils?

2022-11-13 21:14 UTC, SteveMacenski commented on .circleci/config.yml
> +        pip3 install sphinx==4.2.0 breathe sphinx_rtd_theme sphinxcontrib-plantuml jinja2==3.0.3
I don't want updates to break CI

2022-11-14 15:30 UTC, jwallace42 commented on .circleci/config.yml
> -        pip3 install sphinx==3.5.0 docutils==0.14 sphinx_rtd_theme breathe==4.28.0 sphinxcontrib-plantuml jinja2==3.0.3
It is a dependency of breathe. I added it back in to be explicit.

2022-11-14 18:27 UTC, SteveMacenski commented
https://output.circle-artifacts.com/output/job/7793d1a2-8e0a-423d-835c-63cb3e869c5f/artifacts/0/html/build_instructions/index.html

It looks like this broke the collapsing sections in build/install (ref: https://navigation.ros.org/build_instructions/index.html)

2022-11-30 13:52 UTC, closed without merging