added documentation for 'update_on_request' parameter
ros-planning/navigation.ros.org pull request #376
Opened 2022-11-26 08:25 UTC by JohnTGZ

Adds documentation for the 'update_on_request' parameter implementation in the [**Nav2 PR**](https://github.com/ros-planning/navigation2/pull/3300)

Signed-off-by: johntgz <johntan@openrobotics.org>

2022-11-28 20:00 UTC, SteveMacenski requested changes
Generally LGTM

2022-12-04 14:12 UTC, JohnTGZ commented on configuration/packages/configuring-costmaps.rst
> +:update_on_request:
This would be an entry inside the humble migration guide?

2022-12-06 22:19 UTC, SteveMacenski commented on migration/Humble.rst
> +************************
The length of the **** line has to match the header length too to render properly

2022-12-06 22:19 UTC, SteveMacenski commented on migration/Humble.rst
> +`PR #3300 <https://github.com/ros-planning/navigation2/pull/3300>` adds the `update_on_request` parameter that enables updating the costmap only upon request by an algorithm server. The use case woul
```suggestion
`PR #3300 <https://github.com/ros-planning/navigation2/pull/3300>` adds the `update_on_request` parameter that enables updating the costmap only upon request by an algorithm server. The use case would be for benchmarking or test cases -- or to update costmaps only when required instead of on a regular cycle in a separate thread.
```

2022-12-16 00:24 UTC, SteveMacenski approved these changes

2023-08-30 23:42 UTC, closed without merging