Update index.rst
ros-planning/navigation.ros.org pull request #382
Opened 2023-01-06 13:32 UTC by afifswaidan

Added line iterator and collision checker documentation, also updated the docs for costmap_2d for the new function (``mapToWorldValidatged``).

2023-01-06 18:48 UTC, SteveMacenski requested changes

2023-01-06 18:48 UTC, SteveMacenski commented on commander_api/index.rst
> +Line Iterator API
I think you can remove this section, since the line iterator is more an internal class for the collision detector

2023-01-06 18:48 UTC, SteveMacenski commented on commander_api/index.rst
> +*********************************
The *** line has to match the length of the header (remove a couple)

2023-01-06 18:48 UTC, SteveMacenski commented on commander_api/index.rst
> +| lineCost(x0, x1, y0, y1, step_size=0.1)      | Iterate over all the points along a line and check for collision.                          |
Is the default 0.1? Shouldn't it be 1 cell?

2023-01-06 18:48 UTC, SteveMacenski commented on commander_api/index.rst
> +| footprintCost(footprint)                     | Iterate over all the points in a footprint (``Polygon``) and check for collision.          |
Id just say "Checks the footprint (``Polygon``) for collision at its implicit provided coordinate pose."

The iterate over points thing lacks the detail about the line iteration stuff, which I think is TMI for this 1-liner

2023-01-06 19:48 UTC, afifswaidan commented on commander_api/index.rst
> +| lineCost(x0, x1, y0, y1, step_size=0.1)      | Iterate over all the points along a line and check for collision.                          |
We made it default to 1 cell in the Line Iterator API, but here this function is being called inside the ```footprintCost``` function. Since footprints usually aren't very big the lines in it (in the polygon) can be iterated quickly with a step size of 0.1m.
Still, the user can increase the step size if the footprint is big enough.

2023-01-06 19:49 UTC, afifswaidan commented on commander_api/index.rst
> +| footprintCost(footprint)                     | Iterate over all the points in a footprint (``Polygon``) and check for collision.          |
Okay, will do that.

2023-01-06 19:50 UTC, afifswaidan commented on commander_api/index.rst
> +*********************************
I just noticed that also in the previous APIs, the *** line always 2 (*) characters more than the header.
Thats why I made it longer by 2 (*). I will remove them.
Thanks for the notice!

2023-01-06 19:50 UTC, afifswaidan commented on commander_api/index.rst
> +Line Iterator API
Okay sure, will do that.

2023-01-07 14:10 UTC, afifswaidan commented on commander_api/index.rst
> +| lineCost(x0, x1, y0, y1, step_size=0.1)      | Iterate over all the points along a line and check for collision.                          |
Okay, I got your point.
If we aim for speed more than just accuracy then definitely we should increase the step size.
Should I make it default to 1.0 or 0.5 in the ``lineCost`` function?

2023-01-09 18:28 UTC, SteveMacenski commented on commander_api/index.rst
> +| lineCost(x0, x1, y0, y1, step_size=0.1)      | Iterate over all the points along a line and check for collision.                          |
0.5 seems like a reasonable default

2023-01-17 06:17 UTC, SteveMacenski approved these changes

2023-01-17 06:17 UTC, merged