added smoother error code bt node
ros-planning/navigation.ros.org pull request #384
Opened 2023-01-11 00:07 UTC by jwallace42

Updated documentation for the new smoother error code bt node

2023-01-11 19:19 UTC, SteveMacenski requested changes

2023-01-11 19:19 UTC, SteveMacenski commented on tutorials/docs/adding_smoother.rst
>  .. code-block:: xml
I think this is missing the configuration guide page (along with the others)

2023-01-11 19:19 UTC, SteveMacenski commented on tutorials/docs/adding_smoother.rst
> +      <WouldASmootherRecoveryHelp error_code="{would_a_smoother_recovery_help}">
`smoother_error_code`?

2023-01-11 19:19 UTC, SteveMacenski commented on tutorials/docs/adding_smoother.rst
> +      <SmoothPath unsmoothed_path="{path}" smoothed_path="{path}" error_code_id={smoother_error_code}"/>
Missing quotes

2023-01-11 19:19 UTC, SteveMacenski commented on tutorials/docs/adding_smoother.rst
> +If you wish to have recoveries for the smoother error codes:
```suggestion
If you wish to have recoveries for the smoother error codes, such as triggering the system recoveries branch of a behavior tree:
```

2023-01-12 15:16 UTC, jwallace42 commented on tutorials/docs/adding_smoother.rst
>  .. code-block:: xml
Added this in!

2023-01-12 19:54 UTC, SteveMacenski requested changes

2023-01-12 19:54 UTC, SteveMacenski commented on configuration/packages/bt-plugins/conditions/AreErrorCodesPresent.rst
> +    <AreErrorCodesPresent error_code="{error_code}" error_codes_to_check="{error_codes_to_check}"/>
Can you show some specific codes? Maybe 2 entries: 1 with a BT variable containing them (like you have) and another with a list of numbers that works (e.g. `403, 205, 302,` etc)?

2023-01-12 19:54 UTC, SteveMacenski commented on configuration/packages/bt-plugins/conditions/AreErrorCodesPresent.rst
> +    <AreErrorCodesPresent error_code="{error_code}" error_codes_to_check="{error_codes_to_check}"/>
I feel like that'll be a common application of this node

2023-01-13 19:20 UTC, SteveMacenski approved these changes

2023-01-13 19:21 UTC, merged