add Tailos' rosie robot https://tailos.com
ros-planning/navigation.ros.org pull request #400
Opened 2023-03-11 23:45 UTC by AustinDeric

2023-03-12 19:37 UTC, SteveMacenski requested changes
Thanks so much for adding this! Great to see another user of this work!

2023-03-12 19:37 UTC, SteveMacenski commented on about/robots.rst
> +|         |rosie|          +         ||        +           ||        |
Looking at the builds, this isn't working (see artifact of build: https://output.circle-artifacts.com/output/job/2fbc4e63-aa28-48ec-9f11-f30149bf70c5/artifacts/0/html/about/robots.html). The table isn't there. 

Try filling the other 2 fields with the `|soon|` field. Also, the table needs to be properly formatted. Markdown doesn't care about it, but restructured text does :smile: See the other rows above this one for examples!

2023-03-13 19:08 UTC, AustinDeric commented on about/robots.rst
> +|         |rosie|          +         ||        +           ||        |
done, ty!

2023-03-13 19:10 UTC, AustinDeric commented
> Thanks so much for adding this! Great to see another user of this work!

yea we are looking at increasing our contributions back to the community this year as well.  here are some recent ones that come to mind: 
1. https://github.com/tailosinc/ros2_nav2/pull/24
2. https://github.com/SteveMacenski/slam_toolbox/pull/505

2023-03-13 20:13 UTC, SteveMacenski commented on about/robots.rst
> +|         |rosie|        +         |soon|        +           |soon|        |
Still 1 space off here, it won't render :frowning:

2023-03-13 22:02 UTC, SteveMacenski commented
Your (1) is a private repo, so I can't see it :wink: 

> yea we are looking at increasing our contributions back to the community this year as well. If you have any ideas for this, i'd be more than happy to discuss further. Would be great if you could meet our world-class team.

That's really great to hear! Do you have an email address I can contact you over? I have a couple of things that might be worth discussing. I'd also be happy to meet the team!

2023-03-14 15:20 UTC, merged