Add new limit polygon description
ros-planning/navigation.ros.org pull request #412
Opened 2023-04-07 07:58 UTC by BriceRenaudeau

2023-04-07 09:07 UTC, AlexeyMerzlyakov reviewed
Please add the pull request description and reference to the original PR3519 from Nav2 where it related to, to have the proper history. 

The "limit" is not a polygon type (as "Polygon" or "Circle"). It is new safety behavior (or action type, also used in the parameters and mentioned in the documentation), so please correct the description at migration guide.

Also, please add the `LIMIT` safety behavior (action type) to the CM's configuration page (`configuration/packages/configuring-collision-monitor.rst`).

2023-04-07 09:07 UTC, AlexeyMerzlyakov commented on migration/Humble.rst
> +
`LIMIT` is not a new polygon type. It is new safety behavior model, so please correct the header and description

2023-04-07 10:06 UTC, BriceRenaudeau commented on migration/Humble.rst
> +
Done

2023-04-10 06:52 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-collision-monitor.rst
> +- **Limit model**: Define a zone around the robot and restricts the maximum speed to ``linear_limit`` and ``angular_limit``, if ``min_points`` or more points will appear inside the area.
I think, it is better to be more specific here:
... restricts maximum linear and angular velocities to ``linear_limit`` and ``angular_limit`` values accordingly, if ...

2023-04-10 06:52 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-collision-monitor.rst
> +      polygon_pub_topic: "polygon_limit"
Doubling information, please remove one unnecessary line

2023-04-10 06:52 UTC, AlexeyMerzlyakov commented on migration/Humble.rst
> +`PR #3519 <https://github.com/ros-planning/navigation2/pull/3519>`_ adds a new safety behavior model ``limit`` that restricts maximum linear and angular speed to specific values (``linear_limit`` and
... in the polygon
->
... in the given shape

The circle shape is also could be used for `limit` model

2023-04-11 12:41 UTC, BriceRenaudeau commented on configuration/packages/configuring-collision-monitor.rst
> +- **Limit model**: Define a zone around the robot and restricts the maximum speed to ``linear_limit`` and ``angular_limit``, if ``min_points`` or more points will appear inside the area.
Done

2023-04-11 12:41 UTC, BriceRenaudeau commented on migration/Humble.rst
> +`PR #3519 <https://github.com/ros-planning/navigation2/pull/3519>`_ adds a new safety behavior model ``limit`` that restricts maximum linear and angular speed to specific values (``linear_limit`` and
Done

2023-04-11 12:41 UTC, BriceRenaudeau commented
Thanks for your review.

2023-04-12 10:14 UTC, AlexeyMerzlyakov approved these changes
LGTM

2023-05-03 02:26 UTC, SteveMacenski requested changes
2 small changes and this LGTM for when I review / approve the main PR itself. Sorry for the delay

2023-05-03 02:26 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +          max_points: 3
Shouldn't this be min_points now?

2023-05-03 02:26 UTC, SteveMacenski commented on migration/Humble.rst
> +`PR #3519 <https://github.com/ros-planning/navigation2/pull/3519>`_ adds a new safety behavior model ``limit`` that restricts maximum linear and angular speed to specific values (``linear_limit`` and
The word "safety" cannot appear since this is not a safety rated piece of software and we make no warranty as it relates to safety wrt it. This is an important distinction

2023-05-03 07:09 UTC, BriceRenaudeau commented on configuration/packages/configuring-collision-monitor.rst
> +          max_points: 3
Ok

2023-05-03 07:10 UTC, BriceRenaudeau commented on migration/Humble.rst
> +`PR #3519 <https://github.com/ros-planning/navigation2/pull/3519>`_ adds a new safety behavior model ``limit`` that restricts maximum linear and angular speed to specific values (``linear_limit`` and
I remember the thread about the naming and the limitations of this package. I changed it.

2023-05-23 01:42 UTC, merged