Fix parameter name for params_file
ros-planning/navigation.ros.org pull request #427
Opened 2023-05-30 05:09 UTC by OTL

The parameter name for a parameter file has a typo.
It's actually `param*s*_file`.

https://github.com/ros-planning/navigation2/blob/1b5920cc253e33a14cd94c81cccf670d13ee13cf/nav2_bringup/launch/bringup_launch.py#L41

2023-05-30 22:54 UTC, SteveMacenski requested changes

2023-05-30 22:54 UTC, SteveMacenski commented on tuning/index.rst
> +- ``params_file`` : The main navigation configuration file. Defaults to ``nav2_params.yaml`` in the package's ``params/`` directory.
https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/launch/tb3_simulation_launch.py#L42

This appears to be correct.

2023-05-30 22:55 UTC, SteveMacenski approved these changes

2023-05-30 22:55 UTC, merged

2023-05-30 22:55 UTC, SteveMacenski commented
Thanks!

2023-05-31 01:19 UTC, OTL commented
My presure!