Add enum options to Obstacle Layer params
ros-planning/navigation.ros.org pull request #438
Opened 2023-06-20 13:51 UTC by RBT22

The documentation for [#3612](https://github.com/ros-planning/navigation2/pull/3612)

2023-06-20 14:00 UTC, RBT22 commented
> Need to add to migration guide on website that this new feature exists to folks can use it!

Where should I put the migration guide?

> Need to add on configuration guide for costmap 2d the new setting so folks in the future can know its there

What should be this one? Isn't it enough to put info about it in the layer params docs?

2023-06-20 18:28 UTC, SteveMacenski requested changes
We also need an entry in the migration guide announcing this change

2023-06-20 18:28 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/obstacle.rst
> +  | If the master value is NO_INFORMATION, it is overwritten. This is the default.
```suggestion
  | This is the default.
```

2023-06-20 18:28 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/voxel.rst
> +  | If the master value is NO_INFORMATION, it is overwritten. This is the default.
```suggestion
  | This is the default.
```

2023-06-21 14:54 UTC, SteveMacenski approved these changes

2023-06-21 14:54 UTC, merged