Add collision detector docu
ros-planning/navigation.ros.org pull request #451
Opened 2023-08-03 10:08 UTC by tonynajjar

2023-08-03 15:55 UTC, SteveMacenski requested changes

2023-08-03 15:55 UTC, SteveMacenski commented on configuration/index.rst
> +   packages/configuring-collision-detector.rst
These are sorted by packages, so the collision detector should be a sub-page of the collision monitor node entry. You might want to look at the Smac Planner page for reference, but you don't have to follow that style if you don't want -- just a reference of where we have ~3 subpage entries for 1 package. It would be good to do a basic introduction of the package and the nodes and then link to the configuration pages of each

2023-08-03 15:55 UTC, SteveMacenski commented on configuration/packages/configuring-collision-detector.rst
> +In some cases, the user may want to be informed about the detected obstacles without affecting the robot's velocity and instead take a different action within an external node. For example, the user
Remove `\`

2023-08-03 16:22 UTC, tonynajjar commented
Done I believe. Sorry if it's not as verbose as you would wish but I really need to move on with this contribution; it took much more time than expected

2023-08-03 17:40 UTC, tonynajjar commented on configuration/packages/collision_monitor/configuring-collision-monitor-node.rst
> +.. _configuring_collision_monitor:
https://output.circle-artifacts.com/output/job/bcd5236c-bab0-4a7e-81fb-ed932dc74719/artifacts/0/html/configuration/packages/configuring-collision-monitor.html

Not sure I get it, so not like this? 

![image](https://github.com/ros-planning/navigation.ros.org/assets/14879660/a337388f-a9ed-4da3-985e-00b63e2d9680)

2023-08-04 17:43 UTC, SteveMacenski commented on configuration/packages/collision_monitor/configuring-collision-monitor-node.rst
> +The Collision Monitor is a node providing an additional level of robot safety.
Add a ref to the tutorial in this too as you did in the detector rst file

2023-08-04 17:44 UTC, SteveMacenski commented on configuration/packages/collision_monitor/configuring-collision-monitor-node.rst
> +.. _configuring_collision_monitor:
Ah sorry, maybe my diff didn't show me that, I see it now, yes that works! 

Could you just add like a 1-2 sentence in that landing page of what the 2 nodes are?

2023-08-04 17:44 UTC, SteveMacenski commented
otherwise LGTM in general, but I'll let @AlexeyMerzlyakov review as well when he's back from vacation

2023-08-10 13:46 UTC, tonynajjar commented on configuration/packages/collision_monitor/configuring-collision-monitor-node.rst
> +The Collision Monitor is a node providing an additional level of robot safety.
There was already a ref to the tutorial at the bottom, I brought it up the page

2023-08-10 19:41 UTC, SteveMacenski requested changes
I'll let Alexey approve the content of the subpages with the changes, but LGTM structurally

2023-08-10 19:41 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +The Collision Detector is responsible for detecting obstacles in a certain static region or in the robot's path and reporting them/
remove `/` and put a `.`

2023-08-10 19:41 UTC, SteveMacenski commented on configuration/packages/configuring-collision-monitor.rst
> +Nav2 collision monitor
Rename back to Collision Monitor, it should be the package name. The `Nav2` prefix is redundant on Nav2 docs (+ none of the other packages do this and it impacts the navigation side-bar name of the page)

2023-08-14 12:34 UTC, AlexeyMerzlyakov commented on configuration/packages/collision_monitor/configuring-collision-detector-node.rst
> +However, unlike the Collision Monitor that uses different behavior models, the Collision Detector does not use any of them and therefore the `action_type` should always be set to `none`. If set to an
> If set to anything else, it will implicitly be set to `none` and yield a warning.

In latest revision it is not a true

2023-08-14 12:34 UTC, AlexeyMerzlyakov commented on configuration/packages/collision_monitor/configuring-collision-detector-node.rst
> +Similarly to the Collision Monitor, the Collision Detector uses polygons relative the robot's base frame origin to define "zones".
As well as for CM, this is correct statement, but not general. Having the ability to utilize dynamic polygons via topic, CM (and CD) are both could set safety zone in any static frame, say in "map". This is not rather standard use-case of CM and CD, however it was specified in CM's configuration doc page. So, I think, to absorb this ability as well, the text could be generalized to something like:
```
Similarly to the Collision Monitor, the Collision Detector uses robot's relative polygons to define "zones".
```

2023-08-16 17:54 UTC, SteveMacenski commented
One last thing from me - add an entry in the migration guide page for the new node to show off to the users!

2023-08-17 11:42 UTC, tonynajjar commented
> One last thing from me - add an entry in the migration guide page for the new node to show off to the users!

Added for Jazzy and Iron, so now we **have** to backport to Iron :smile:

2023-08-17 15:55 UTC, SteveMacenski commented on migration/Humble.rst
> +New node in nav2_collision_monitor: Collision Detector
Remove, this should only be in one migration guide

2023-08-17 15:55 UTC, SteveMacenski commented on migration/Iron.rst
> +It works similarly to the Collision Monitor, but does not affect the robot's velocity. It will only inform that data from the configured sources has been detected within the configured polygons via m
```suggestion
It works similarly to the Collision Monitor, but does not affect the robot's velocity. It will only inform that data from the configured sources has been detected within the configured polygons via message to the ``collision_detector_state`` topic.
```

two forward quotes are required for it to render as code

2023-08-22 17:18 UTC, SteveMacenski commented
Just @AlexeyMerzlyakov 's comments left but I'm happy when he is

2023-08-22 17:18 UTC, SteveMacenski approved these changes

2023-08-28 17:55 UTC, SteveMacenski commented on migration/Iron.rst
> +It works similarly to the Collision Monitor, but does not affect the robot's velocity. It will only inform that data from the configured sources has been detected within the configured polygons via m
```suggestion
It works similarly to the Collision Monitor, but does not affect the robot's velocity. It will only inform that data from the configured sources has been detected within the configured polygons via message to the ``collision_detector_state`` topic that might be used by any external module (e.g. switching LED or sound alarm in case of collision).
```

2023-08-28 17:56 UTC, merged