GPS WPF tutorial
ros-planning/navigation.ros.org pull request #457
Opened 2023-08-24 17:39 UTC by pepisg

2023-08-30 23:37 UTC, SteveMacenski reviewed
Very good! One last thing is to capitalize "Nav2" throughout

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +.. _navigation2-with-gps:
This tutorial wasn't added to the index.html so it doesn't appear on the website :-)

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +Navigating with a GPS Based Localization System
How about just "Navigating Using GPS Localization"

Make sure to adjust the `****` to be the same length under

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +To cope with this, geodesy allows for the definition of  `Local tangent planes <https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates>`_. According to `REP 103 <https://www.ros.org/reps/rep-0
```suggestion
To cope with this, geodesy allows for the definition of  `Local tangent planes <https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates>`_. According to `REP 103 <https://www.ros.org/reps/rep-0103.html>`_ the coordinate systems of these planes should follow the ENU convention, which means their +x axis should face East, +y axis should face North and the +z axis should point Up, as the image below shows. In the context of this tutorial the GPS coordinates of the origin of the local cartesian plane will be called **datum** as it is in `robot_localization <http://docs.ros.org/en/noetic/api/robot_localization/html/index.html>`_.
```

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +Additionally, to fully describe a robot's localization using the ENU convention we need to know its heading as well, however GPS sensors do not provide orientation measurements, only position measure
Is that a realistic expectations of IMUs? Don't they typically start at 0 when powered on / initialized?  That's not really what is meant by "absolute" when you buy IMUs (it just means it has a way to fuse all the IMU sensors to get an absolute orientation, but its not necessarily aligned to anything but the initial pose) 

I know you talk about that a bit in the later paragraphs about how that can't be relied on, but I don't think this is actually a true statement. I think this should be adjusted.

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +To get actual gps readings we need to create a robot model with a GPS sensor. An updated turtle model is provided in the `tutorial repo <https://github.com/ros-planning/navigation2_tutorials/tree/mas
Below this paragraph would be a great place to put a code block with the GPS code added to the URDF for reference

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +To get actual gps readings we need to create a robot model with a GPS sensor. An updated turtle model is provided in the `tutorial repo <https://github.com/ros-planning/navigation2_tutorials/tree/mas
Imagine that the user is trying to set this up for their robot by reading this -- so we should provide the example changes where made inline so they can copy/paste for their particular situation

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +To navigate using GPS we first need to create an outdoors Gazebo world with a robot having a GPS sensor. For this tutorial we will be using the `sonoma raceway <https://docs.px4.io/main/en/sim_gazebo
```suggestion
To navigate using GPS we first need to create an outdoors Gazebo world with a robot having a GPS sensor to setup for navigation. For this tutorial we will be using the `sonoma raceway <https://docs.px4.io/main/en/sim_gazebo_classic/gazebo_worlds.html#sonoma-raceway>`_ because its aligned with the real location. A sample world has been setup `here <https://github.com/ros-planning/navigation2_tutorials/tree/master/nav2_gps_waypoint_follower_demo/worlds/sonoma_raceway.world>`_ using gazebo's spherical coordinates plugin, which creates a local tangent plane centered in the set geographic origin and provides latitude, longitude and altitude coordinates for each point in the world.
```

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +  ``ros2 launch nav2_gps_waypoint_follower_demo gazebo_gps_world.launch.py``
Try to use actual code blocks, see the other tutorials for the rst formatting

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +.. image:: images/Gps_Navigation/gazebo_sonoma_raceway.png
What's up with this having no skin (e.g. just white)?

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +Once you have your simulation (or real robot) up and running, it's time to set up your localization system. Remember that nav2 needs a ``tf`` chain with the structure ``map`` -> ``odom`` -> ``base_li
```suggestion
Once you have your simulation (or real robot) up and running, it's time to set up your localization system. Remember that nav2 needs a ``tf`` chain with the structure ``map`` -> ``odom`` -> ``base_link`` -> ``[sensor frames]``; global localization (``map`` -> ``odom``) is usually provided by ``amcl``, while ``odom`` -> ``base_link`` is usually provided by the user's odometry system (wheel odometry, visual odometry, etc).
```

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +In this tutorial, the GPS sensor on the robot will replace ``amcl`` in providing global localization. Though you may build a custom module that takes in the ``NavSatFix`` and ``Imu`` messages of your
map->odom. It might calculate map->base but we actually publish map->odom via TF

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +In this tutorial, the GPS sensor on the robot will replace ``amcl`` in providing global localization. Though you may build a custom module that takes in the ``NavSatFix`` and ``Imu`` messages of your
Nav2 **uses** robot localization for this purpose, not "needs".

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +A `configuration file <https://github.com/ros-planning/navigation2_tutorials/tree/master/nav2_gps_waypoint_follower_demo/config/dual_ekf_navsat_params.yaml>`_ and a `launch file <https://github.com/r
I think it might be worth walking through some of this file, especially the NavSat Transform configuration. The Filters I wouldn't go crazy explaining but some introduction would be good

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +The navsat transform node exposes the ``datum`` parameter to set the GPS coordinates of the origin of the local tangent plane, which given translates to the origin of the position measurements output
This first sentence is a bit run on and needs to be reworded. I'm having trouble understanding the second half of it

"however you may specify them said parameter in the yaml file" --> the?

"calling" -> "call"

"in runtime" to "at runtime"

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +A `static transforms launch <https://github.com/ros-planning/navigation2_tutorials/tree/master/nav2_gps_waypoint_follower_demo/launch/static_transforms.launch.py>`_ is provided to set the transforms
This no longer exists, I don't think this paragraph is necessary anymore

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +  ``ros2 launch nav2_gps_waypoint_follower_demo mapviz.launch.py``
After this command, a picture of mapviz would be nice

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +  ``ros2 launch nav2_gps_waypoint_follower_demo gazebo_gps_world.launch.py``
^ also across this file, there are alot of places this formatting appears

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +1. If your IMU does not provide absolute heading measurements accurately, consider setting the ``differential`` parameter of its input to RL to ``true``. This way the filter will only fuse changes in
So how does this deal with the fact that the IMU never has the absolute orientation w.r.t. global coordinates and only on the initialized pose? Or does the EKF somehow above deal with that already?

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +Once you have your localization system up and running it's time to setup nav2. since RL is already providing the ``tf`` tree we don't need to launch ``amcl``, thus we can remove its parameters from t
```suggestion
Once you have your localization system up and running it's time to setup nav2. since RL is already providing the ``tf`` tree we don't need to launch ``amcl``, thus we can remove its parameters from the params file and node from Nav2 launch files.
```

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +Outdoors environments can get quite big, to a degree that they may not me practically represented on a single costmap. For that reason in this tutorial we use a rolling global costmap that is big eno
may not "be practical"

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +The gif below shows what you should see
```suggestion
The gif below shows what you should see Nav2 navigating the robot autonomously!
```

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +Now that we have performed our complete system setup, lets leverage nav2 GPS waypoint follower capabilities to navigate to goals that are expressed directly in GPS coordinates. For this demo we want
Mention that this is a useful demo to showcase how to get started

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +  ``ros2 run nav2_gps_waypoint_follower_demo logged_waypoint_follower``
Needs gif / graphic 

Also after this section have a short conclusion section to round it off

2023-08-30 23:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +Outdoors environments can get quite big, to a degree that they may not me practically represented on a single costmap. For that reason in this tutorial we use a rolling global costmap that is big eno
Make a bulleted list of the options:
- Have a static map used to size the costmap for global planning
- Have a large but realistic environment and set the costmap size to the space's size 
- Have a very large environment so have a rolling costmap large enough to fit any consecutive tasks

2023-08-30 23:42 UTC, SteveMacenski commented
Also a few things we should pull from https://github.com/ros-planning/navigation.ros.org/pull/129/files
- Add some talk of GPS in the Concepts page 
- Show the 3 configuration setups for the 3 modes (map, no map static sized, no map rolling) in the global costmap (e.g. the actual configuration settings that change / matter)

2023-09-09 16:12 UTC, pepisg commented on tutorials/docs/navigation2_with_gps.rst
> +.. image:: images/Gps_Navigation/gazebo_sonoma_raceway.png
I have looked into this and It looks like the model in nav2 has no skin either, at least it always shows white in my computer even in the turtlebot world simulation. I think this happens because the meshes in the [model](https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/worlds/waffle.model) file don't have a `<material>` tag. Could you please check if the turtlebot3 model has a skin in your simulation in the turtlebot3 and let me know?

2023-09-10 16:14 UTC, pepisg commented
I think I've gone through most of your comments here and in the tutorial code. Let me know what you think @SteveMacenski

2023-09-11 18:04 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +In this tutorial, the GPS sensor on the robot will replace ``amcl`` in providing global localization. Though you may build a custom module that takes in the ``NavSatFix`` and ``Imu`` messages of your
@pepisg missing

2023-09-11 18:31 UTC, SteveMacenski requested changes

2023-09-11 18:31 UTC, SteveMacenski commented on configuration/packages/configuring-waypoint-follower.rst
> +    The name of the coordinate frame published by robot_localization. Only used by the gps_waypoint_follower.
published by robot localization ... for what purpose?

2023-09-11 18:31 UTC, SteveMacenski commented on concepts/index.rst
> +``nav2_waypoint_follower`` also supports GPS waypoint following when global localization is provided by `robot_localization <https://github.com/cra-ros-pkg/robot_localization/>`_  using the ``navsat_
```suggestion
``nav2_waypoint_follower`` also supports GPS waypoint following when global localization is provided by `robot_localization <https://github.com/cra-ros-pkg/robot_localization/>`_  using the ``navsat_transform`` node - but also may be provided by Fuse or any number of other sources.
```

2023-09-11 18:31 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +This tutorial shows how to set up a localization system using a GPS sensor as source of global positioning and robot_localization (RL) for sensor fusion, and how to use Nav2 to follow GPS waypoints.
```suggestion
This tutorial shows how to set up a localization system using a GPS sensor(s) as the source of global positioning, robot_localization (RL) for sensor fusion, and how to use Nav2 to follow GPS waypoints. It was written by Pedro Gonzalez at `Kiwibot <https://www.kiwibot.com/>`_.
```

2023-09-11 18:31 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +In this tutorial we assume the robot's GPS produces a really accurate and smooth estimation of the robot's position, however in the real world for standalone GPSs that's often not the case: you shoul
This paragraph has good context but its a bit misleading up the front. The first sentence makes it sound like there's some critical problem that this tutorial is just ignoring. But then its clear later on in the paragraph there are common solutions. 

I think the first sentence should be re-written. Maybe ignore the "In this tutorial we assume..." bit and just explain the GPS jumps and here are some solutions more abstractly. Maybe at the end of this paragraph we just say "In this tutorial, we assume we have adequate localization via RTK or similar technologies or good conditions".

2023-09-11 18:31 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +Additionally, to fully describe a robot's localization we need to know its heading as well, however standalone GPS sensors do not provide orientation measurements, only position measurements. In this
```suggestion
Additionally, to fully describe a robot's localization we need to know its heading as well, however standalone GPS sensors do not provide orientation measurements, only position measurements. In this tutorial we will refer as 'absolute heading' to a yaw measurement which is given w.r.t. a cardinal direction (e.g, the east), in contrast to relative heading, which is given w.r.t. the angle the robot is turned on or any other reference that cannot be directly mapped  to a cardinal direction.
```

2023-09-11 18:31 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +When using robot_localization with GPS, measuring absolute orientation is mandatory. There are several alternatives for getting absolute orientation data, like IMUs with magnetometers, dual GPS syste
```suggestion
When using robot_localization with GPS, measuring absolute orientation is mandatory. There are several strategies for getting absolute orientation data, like IMUs with magnetometers, dual GPS systems or matching techniques over a known map; in this tutorial we assume the robot is equipped with an IMU that can accurately measure absolute orientation following the ENU convention, meaning it will output zero yaw when facing east and +90 degrees when facing north. 
```

2023-09-11 18:31 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +Through the development of the tutorial we will see how to leverage robot_localization's Kalman Filters to mitigate this problem.
```suggestion
Thus, for a particular application you should consider the behavior and localization quality you require when making decisions about how to estimate your absolute heading. When using IMU's without relative headings to a cardinal direction, the robot may need to move around for a bit in an 'initialization dance' to converge to the right heading using the filter. Using dual-GPS or 3D mapping system overlay, the initial heading is quite good. 

For the purposes of this tutorial, we model a well-built system using an IMU that has absolute orientation already, but that may be augmented or replaced on a practical system using one of the techniques above (or others).
```

2023-09-11 18:31 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +In this tutorial, the GPS sensor on the robot will replace ``amcl`` in providing global localization. Though you may build a custom module that takes in the ``NavSatFix`` and ``Imu`` messages of your
Remove any reference to Nav2 "needs" R_L, we don't "need" it, we're currently using it. There are other solutions as well, including the ones we're working on recently with Fuse

2023-09-11 18:31 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +The global odometry is provided by the ``ekf_filter_node_map``, which publishes the transform between ``map`` and ``base_link``. This EKF is set to work in 2D mode as well. In addition to the IMU and
```suggestion
The global odometry is provided by the ``ekf_filter_node_map``, which publishes the transform between ``map`` and ``base_link``. This EKF is set to work in 2D mode as well. In addition to the IMU and wheel odometry data, this filter takes in the odometry output of the gps, published by the ``navsat_transform`` node on ``/odometry/gps``, as an odometry message:
```

2023-09-11 18:31 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +3. **Static position and size**: Finally, depending on your application you may still choose to use a fixed global costmap, just remember to make it fit all the potential locations the robot may visi
```suggestion
3. **Static position and size**: Finally, depending on your application you may still choose to use a fixed global costmap if you have a restricted operating environment you know beforehand, just remember to make it fit all the potential locations the robot may visit. In this case you need to set the size and origin position in the parameters:
```

2023-09-11 18:31 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +
Create a short conclusion section just to go over what we setup and conclude the tutorial

2023-09-11 18:40 UTC, pepisg commented on tutorials/docs/navigation2_with_gps.rst
> +In this tutorial, the GPS sensor on the robot will replace ``amcl`` in providing global localization. Though you may build a custom module that takes in the ``NavSatFix`` and ``Imu`` messages of your
But the GPS waypoint follower does "need" robot localization to be used (or at least the navsat_transform node) because it relies on the `/fromLL` service to convert GPS to cartesian goals. Maybe I could add the reason why its needed so its clearer

2023-09-11 18:49 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +In this tutorial, the GPS sensor on the robot will replace ``amcl`` in providing global localization. Though you may build a custom module that takes in the ``NavSatFix`` and ``Imu`` messages of your
That another option could provide that as well. As you know, we're moving GPS / state estimation to Fuse right now, so clearly R_L is not going to be the only game in town as a requirement

2023-09-12 20:09 UTC, SteveMacenski commented
@pepisg I assume with this all written out that the GPS waypoint follower works fine? I haven't seen an update there that I should re-review. That would need to be ready before the tutorial can be merged since its used in the tutorial

2023-09-12 20:22 UTC, pepisg commented
Yeah, I used it for creating the tutorial. Last I pulled `main` though the tests were not passing. I will review why is that by the end of the week and let you know when I think everything is ready

2023-09-18 17:26 UTC, SteveMacenski approved these changes

2023-09-18 17:26 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +In the real world GPS sensors can be noisy: With standalone GPSs you should expect accuracies of 1-2 meters under excellent conditions and up to 10 meters, and frequent jumps in the position as the G
```suggestion
In the real world GPS sensors can be noisy: With standalone GPSs you should expect accuracies of 1-2 meters under excellent conditions and up to 10 meters, and frequent jumps in the position as the GPS sensor picks up less or more satellites, which can degrade the quality of navigation significantly. Several positioning augmentation technologies exists to reduce the error of GPS measurements, one of the most common ones is called `RTK <https://en.wikipedia.org/wiki/Real-time_kinematic_positioning>`_ (Real Time Kinematic Positioning), which can bring the accuracy of receivers down to 1cm. If accuracy matters in your application this technology is highly recommended; though this requires the deployment of a second fixed GPS called base, most of the US and Europe are already covered with public free to use bases that you can connect to. You can read more about RTK and how to get started `here <https://learn.sparkfun.com/tutorials/setting-up-a-rover-base-rtk-system>`_. In this tutorial we assume the robot's GPS produces an accurate and smooth estimation of the robot's position.
```

2023-09-18 17:26 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_gps.rst
> +In this tutorial, the GPS sensor on the robot will replace ``amcl`` in providing global localization. Though you may build a custom module that takes in the ``NavSatFix`` and ``Imu`` messages of your
```suggestion
In this tutorial, the GPS sensor on the robot will replace ``amcl`` in providing global localization. Though you may build a custom module that takes in the ``NavSatFix`` and ``Imu`` messages of your GPS and imu, and outputs a ``tf`` between your ``map`` and ``odom`` frames using a planar projection, Nav2's GPS waypoint follower currently uses robot_localization for converting GPS goals to cartesian goals, and thus at a `navsat_transform_node <http://docs.ros.org/en/jade/api/robot_localization/html/navsat_transform_node.html>`_ should be active. Additionally, ``robot_localization`` features reconfigurable state estimation nodes that use Kalman Filters to fuse multiple sources of data, which is yet another reason to use it.
```

2023-09-20 17:37 UTC, SteveMacenski commented on migration/Iron.rst
> +`This PR 2814 <https://github.com/ros-planning/navigation2/pull/2814>`_  adds the ``follow_gps_waypoints`` action server in ``nav2_waypoint_follower``. This server accepts a set of GPS goals instead
```suggestion
`This PR 2814 <https://github.com/ros-planning/navigation2/pull/2814>`_  adds the ``follow_gps_waypoints`` action server in ``nav2_waypoint_follower``. This server accepts a set of GPS goals instead of cartesian goals and provides all the other functionalities available on ``nav2_waypoint_follower``. A new tutorial demonstrating its functionality was also added on `PR 70 on navigation2_tutorials <https://github.com/ros-planning/navigation2_tutorials/pull/70>`_ and can be found on the General Tutorials directory on this website. 
```

2023-09-25 21:34 UTC, merged