Action result timeout
ros-planning/navigation.ros.org pull request #461
Opened 2023-09-07 01:29 UTC by pepisg

docs updates for https://github.com/ros-planning/navigation2/pull/3787

2023-09-07 17:44 UTC, SteveMacenski requested changes
Good!

2023-09-07 17:44 UTC, SteveMacenski commented on migration/Iron.rst
> +******************************************************
The `**` need to match length for it to render properly

2023-09-07 17:44 UTC, SteveMacenski commented on migration/Iron.rst
> +is not produced within 10 seconds, when the default was set to 15 minutes before. Since actions in Nav2 may take more than 10 seconds to complete, the user has now the ability
```suggestion
is not produced within 10 seconds, when the default was set to 15 minutes before. Since some actions in Nav2 may take more than 10 seconds to complete, the user has now the ability
```

2023-09-07 17:44 UTC, SteveMacenski commented on configuration/packages/configuring-behavior-server.rst
> +    some actions in Nav2 take to run.
For all I'd add:

"For most applications, this should not need to be adjusted as long as the actions within the server do not exceed this deadline. This issue has been raised with OSRF to find another solution to avoid active goal timeouts for bookkeeping, so this is a semi-temporary workaround."

2023-09-08 00:17 UTC, AlexeyMerzlyakov reviewed
Thanks for the diligent work on all Action Servers in Nav2! Some nitpicks for documentation update are below:

2023-09-08 00:17 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-behavior-server.rst
> +    15 minutes in rclc but was changed to 10 seconds in this `PR #1012 <https://github.com/ros2/rcl/pull/1012>`_, which may be less than
rclc -> rcl here and in all other places

2023-09-08 00:17 UTC, AlexeyMerzlyakov commented on configuration/packages/configuring-behavior-server.rst
> +
Here and below: please check extra blank line (one line between chapters is enough)

2023-09-09 17:28 UTC, SteveMacenski approved these changes

2023-09-09 17:28 UTC, merged