Documentation for Graceful Motion
ros-planning/navigation.ros.org pull request #517
Opened 2024-02-05 17:56 UTC by ajtudela

Documentation for [#4021](https://github.com/ros-planning/navigation2/pull/4021)

2024-02-05 20:10 UTC, SteveMacenski requested changes

2024-02-05 20:10 UTC, SteveMacenski commented on configuration/packages/configuring-graceful-motion-controller.rst
> +:initial_rotation:
Appears twice? Should be final rotation?

2024-02-05 20:19 UTC, ajtudela commented on configuration/packages/configuring-graceful-motion-controller.rst
> +:initial_rotation:
Fixed now!

2024-02-05 21:35 UTC, merged

2024-02-05 21:35 UTC, SteveMacenski commented
@ajtudela thanks for the contribution! If you had a video of this controller in action, that would be great for an announcement post to the community about your new controller plugin! Its worth spending a few minutes to make a nice demo video (then, that could be added to the config guide page as an example!)

2024-02-06 17:08 UTC, ajtudela commented
I totally forgot! I made this [video](https://youtu.be/P-iKCo4h56M)

I don't know if it worth it.

2024-02-06 17:14 UTC, SteveMacenski commented
That video is a bit slow and glitchy (lots of jumps), if you could make another one at more reasonable speeds and smoothness, that would be great!

2024-02-13 19:53 UTC, ajtudela commented
Hi, I didn't forget about the video. It seems that YTdecrese the bitrate too much. So, I'd try to make a new video during this week.

2024-02-29 20:58 UTC, SteveMacenski commented
It seems a bit wobbly when there are small deviations in the path that the control point jitters between. Is there a nice way to smooth that out? (@mikeferguson perhaps a nice challenge when you're working on the dynamic point setting)

It definitely seems like keeping the point further off is a good move.