updating Bt's with the selectors
ros-planning/navigation.ros.org pull request #519
Opened 2024-02-06 17:17 UTC by padhupradheep

2024-02-06 17:29 UTC, SteveMacenski reviewed
Can you make this PR include the migration guide (with a screen shot or gif of the tool) for the new selector feature + all the BTs were updated to be able to use it?

Easier to do this all in batch

2024-02-06 18:16 UTC, padhupradheep commented
Tbh, entirely forgot about the migration guide.. got bit rusty :laughing: 

Did the necessary updates..

2024-02-06 18:18 UTC, SteveMacenski commented on migration/Iron.rst
> +The primarly goal of this plugin is to facilitate the developers and integrators to easily test their configuration before deploying the robot in the intended application.
```suggestion
The primary goal of this plugin is to facilitate the developers and easy integration testing of their configuration before deploying the robot in the intended application.
```

2024-02-06 18:38 UTC, SteveMacenski commented
Pending discussion in ticket

2024-02-07 18:12 UTC, SteveMacenski approved these changes

2024-02-08 17:42 UTC, SteveMacenski requested changes

2024-02-08 17:42 UTC, SteveMacenski commented on requirements.txt
> +breathe
Revert, these should stay as they are for this PR

2024-02-08 17:50 UTC, padhupradheep commented on requirements.txt
> +breathe
sorry.. damn!

2024-02-08 18:01 UTC, SteveMacenski approved these changes

2024-02-09 19:47 UTC, merged