Improve description of goal_checker_plugins
ros-planning/navigation.ros.org pull request #523
Opened 2024-02-08 11:02 UTC by ssr-yuki

This PR complements #302, reflecting https://github.com/ros-planning/navigation2/pull/2269 in the documents.

This PR consists of ...

- modification of the type of `goal_checker_plugins` parameter and its example
- description of how to handle `goal_checker_id` field in `FollowPath` actions with the parameter

2024-02-08 17:30 UTC, SteveMacenski requested changes

2024-02-08 17:30 UTC, SteveMacenski commented on configuration/packages/configuring-controller-server.rst
>    ============== ==============
Its pedantic, but the CI job complains: the table's top/bottom/dividers need to be the same length or larger than the content. This overflows in the 'value' part by 2 chars

2024-02-09 04:53 UTC, ssr-yuki commented on configuration/packages/configuring-controller-server.rst
>    ============== ==============
I've fixed this :+1:

2024-02-09 17:31 UTC, SteveMacenski approved these changes
Thanks! I try very hard to keep the docs in line with main, but sometimes something slips through the cracks :(

2024-02-09 17:31 UTC, merged