PR 4140 docs
ros-planning/navigation.ros.org pull request #530
Opened 2024-02-29 08:10 UTC by doisyg

2024-02-29 21:03 UTC, SteveMacenski requested changes

2024-02-29 21:03 UTC, SteveMacenski commented on migration/Iron.rst
> -Here we can see the working demo of the plugin:
You removed the selector plugin demo gif?
Edit: oh and some important text below it as well. Please readd those!

2024-02-29 21:03 UTC, SteveMacenski commented on migration/Iron.rst
> +Additionaly, the conflict between ``use_rotate_to_heading` and ``allow_reversing`` was fixed so ``use_rotate_to_heading`` can now be used backward.
```suggestion
Additionally, the conflict between ``use_rotate_to_heading` and ``allow_reversing`` was fixed so ``use_rotate_to_heading`` can now be used backward.
```

2024-03-01 09:23 UTC, doisyg commented on migration/Iron.rst
> -Here we can see the working demo of the plugin:
Oupsie, sorry, good catch

2024-03-01 17:25 UTC, SteveMacenski approved these changes

2024-03-01 17:25 UTC, merged