Refactor the plugin names for bt_navigator to use double colons
ros-planning/navigation.ros.org pull request #539
Opened 2024-03-28 13:40 UTC by alanxuefei

2024-03-28 17:12 UTC, SteveMacenski commented
Missing the migration guide entry. Also, for the lines that you change, add a comment that in Iron and older it uses `/`

2024-03-29 04:41 UTC, alanxuefei commented
> Missing the migration guide entry. Also, for the lines that you change, add a comment that in Iron and older it uses `/`

---

**migration guide entry** is as below. A documentation warning regarding asterisk (*) length mismatch has been addressed.

<img src="https://github.com/ros-planning/navigation.ros.org/assets/7146994/a2832344-bd57-4ed0-9d72-c142d4edbadc" width="600" alt="Corrected Migration Guide Screenshot">







**Comments** have been added to all YAML example files that were modified:

<img src="https://github.com/ros-planning/navigation.ros.org/assets/7146994/c6f96960-fcbd-46ce-beb1-65c486bbd917" width="400" alt="YAML Example with Comments 1">

<img src="https://github.com/ros-planning/navigation.ros.org/assets/7146994/c9c6b60f-cfc5-44d2-9f5d-d8557be73fac" width="400" alt="YAML Example with Comments 2">


---

2024-03-29 17:29 UTC, SteveMacenski requested changes

2024-03-29 17:29 UTC, SteveMacenski commented on migration/Iron.rst
> +`PR #4220 <https://github.com/ros-planning/navigation2/pull/4220>`_ standardizes plugin naming to use double colons (::), replacing the previous mixed use of slashes (/) and double colons.
Please call out the specific plugin names that changed so its clear to folks if they fall into it. 

Otherwise, I can merge the pair of PRs. Thanks!

2024-03-30 02:15 UTC, alanxuefei commented on migration/Iron.rst
> +`PR #4220 <https://github.com/ros-planning/navigation2/pull/4220>`_ standardizes plugin naming to use double colons (::), replacing the previous mixed use of slashes (/) and double colons.
Updated as below
<img width="1115" alt="image" src="https://github.com/ros-planning/navigation.ros.org/assets/7146994/f309ddbb-36da-414e-8a5c-bb8251f719f9">

2024-03-30 18:19 UTC, merged