Add docs for Velocity Deadband Critic
ros-planning/navigation.ros.org pull request #546
Opened 2024-04-11 18:42 UTC by perchess

This PR adds documentation for the main [nav2_mppi_controller PR](https://github.com/ros-planning/navigation2/pull/4256)

2024-04-11 19:34 UTC, SteveMacenski requested changes

2024-04-11 19:34 UTC, SteveMacenski commented on configuration/packages/configuring-mppic.rst
> +          critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic", "VelocityDeadbandCritic"]
Remove

2024-04-11 19:34 UTC, SteveMacenski commented on configuration/packages/configuring-mppic.rst
> +          VelocityDeadbandCritic:
Remove

2024-04-12 18:08 UTC, perchess commented on configuration/packages/configuring-mppic.rst
> +  double          100.0
Yeah, I agree, it can be scary. The deadband velocity is always small. I've tested other weights and velocities in the simulator. A weight of 35.0 is sufficient, but sometimes in tight places, where the cost or obstacle critics take a lead, the robot can get stuck until the spinning behavior kicks in to help.

2024-04-12 18:19 UTC, SteveMacenski approved these changes

2024-04-12 18:19 UTC, merged