Update GoalUpdater docs
ros-planning/navigation.ros.org pull request #621
Opened 2024-12-11 09:20 UTC by tonynajjar

https://github.com/ros-navigation/navigation2/pull/4771

2024-12-11 19:10 UTC, SteveMacenski requested changes
Otherwise, :+1:

2024-12-11 19:10 UTC, SteveMacenski commented on configuration/packages/bt-plugins/decorators/GoalUpdater.rst
> +  ====== ==============
the table needs to be expanded by 1 `=` and `-` since the content bleeds outside of it 

... rst is really annoying

2025-01-10 20:06 UTC, SteveMacenski approved these changes
Please add the migration guide too. You can add it under the `New BT Nodes[](https://docs.nav2.org/migration/Jazzy.html#new-bt-nodes)` section I think (with a small title rename to BT Node Changes)

2025-01-13 20:50 UTC, SteveMacenski commented
@tonynajjar just add to the migration guide and we should be Good to Go to merge this too

2025-01-14 08:31 UTC, tonynajjar commented
Done

2025-01-14 15:04 UTC, merged