Add CostmapFilters/KeepoutFilter into documentation
ros-planning/navigation.ros.org pull request #85
Opened 2020-09-11 12:16 UTC by AlexeyMerzlyakov

Cover Costmap Filters / Keepout Zones in documentation web-site.
Original feature ticket: https://github.com/ros-planning/navigation2/issues/1263, PR: https://github.com/ros-planning/navigation2/pull/1882

2020-09-14 20:21 UTC, SteveMacenski requested changes
Remove the PDF, that doesn't belong here

2020-09-14 20:21 UTC, SteveMacenski commented on concepts/index.rst
> +Costmap filters - is a costmap layer-based instrument which provides an ability to apply on map spatial-dependent raster objects drawn on map-masks. These objects are used in filters algorithms when
Please make this more descriptive. The first sentence I don't think anyone could understand on the first read-through. You don't need all the technical jargon. 

Those algorithms are also "examples" not an extensive list, as the wording implies. Be more clear about the usefulness of this, and then some examples of plugins we provide using it. This is the very first introduction into this concept for people. 

Also proof read, there's some "s" where there should be an "a", there's a few typos in other parts of this PR as well.

2020-09-14 20:21 UTC, SteveMacenski commented on plugins/index.rst
> +| `Keepout Filter`_  | Alexey Merzlyakov  | Maintanins keep-out/safety zones  |
Typos

2020-09-14 20:21 UTC, SteveMacenski commented on plugins/index.rst
> +|                    |                    | and preferred lanes in industries |
I don't know what you mean by "in industries"

2020-09-14 20:21 UTC, SteveMacenski commented on migration/Eloquent.rst
> +Costmap Filters
This belongs in the Foxy migration guide

2020-09-14 20:21 UTC, SteveMacenski commented on configuration/packages/costmap-plugins/costmap_filters.rst
> +There are following parameters common for all costmap filters plugins:
This isn't "most common" this is the official documentation for all of nav2. This needs to be extensive and complete. This should be for the keepout layer and all the parameters it contains.

2020-09-14 20:21 UTC, SteveMacenski commented on migration/Eloquent.rst
> +A new concept interacting with spatial-dependent objects called "Costmap Filters" appeared in Foxy (more information about this concept could be found at :ref:`concepts` page). Costmap filters consis
Please describe how / why this works in common terms

2020-09-14 20:21 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +1. Prepare map mask in the same way as any other PGM/PNG/BMP map made. For ``KeepoutFilter`` the passibility is proportional to color intesity (darker colors means more impassable areas). Black color
You don't explain at all how to "prepare map mask" that's not an obvious process. What tools should they use? How? What do the pixels mean? How to prepare a message with multiplier / base?

2020-09-14 20:21 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +1. Prepare map mask in the same way as any other PGM/PNG/BMP map made. For ``KeepoutFilter`` the passibility is proportional to color intesity (darker colors means more impassable areas). Black color
What does it mean to have the pixels marked here? How to do for lanes?

2020-09-14 20:21 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +2. CostmapFilters are Costamp2D plugins. Add ``KeepoutFilter`` plugin in params of local and/or global costmap:
This shouldn't be and/or, this is the official tutorial. You should be telling the reader what to do specifically.

2020-09-14 20:21 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +.. code-block:: text
Should 1 complete yaml blob and then have your annotations below it. Splitting into 2 isn't easy to understand and the reader cant just copy paste a block

2020-09-14 20:21 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +NOTE: Enabling ``KeepoutFilter`` for ``global_costmap`` only will cause path planner to build path plan bypassing keepout zones. Enabling ``KeepoutFilter`` for ``local_costmap`` only will cause robot
Good, leave this here, but the instructions should just tell people to use both. This should be more of an FYI on why that's true.

2020-09-14 20:21 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +.. code-block:: text
These are bash, not text

2020-09-14 20:21 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +It will launch dummy info publisher and map server set to mask publishing.
You should probably be telling them how to modify existing launch files to launch with their specific needs. That way this tutorial is usable in a production / automated way and not requiring them to setup commandline things every bringup.

2020-09-14 20:27 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +.. image:: images/Navigation2_with_Keepout_Filter/keepout_global.gif
These are OK examples to show that its working, but I think the absolute most common case will be a map annotated with some keepout zone. I think it would be good to have a gif of that. An annotated mask of the map size with some keepout zone in the middle. Then the gif showing the robot planning around some keepout zone in the middle of the map. 

Keep these, but put them on the same line and a comment above them saying that this is showing that you can use a map of any size, shape, or origin. They don't need to be the same as the map. In fact, that would be good to mention specifically in concepts and the migration guide.

2020-09-21 20:17 UTC, SteveMacenski requested changes

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +(Costmap Filters) Navigating with Keepout Zones
```suggestion
Navigating with Keepout Zones
```

Title is too long to fit on one line in browser

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +This tutorial shows how to simply utilize keep-out/safety zones where robots can't enter and preferred lanes for robots moving in industries and warehouses. All this functionality is being covered by
industries -> "industrial environments".

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +Map mask is the usual ROS map distributed through PGM, PNG or BMP raster file with its metadata YAML file. As an example you can use `keepout_mask.yaml <https://github.com/ros-planning/navigation2/tr
How did you make your keepout map? You didn't actually tell anyone how to do this. This should be a specific tutorial with specific instructions.

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +For exaple, in ``nav2_params.yaml``:
"example"

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +CostmapFilters are Costamp2D plugins. Enable ``KeepoutFilter`` plugin in Costmap2D. For that plugin name ``keepout_filter`` should be added to ``plugins`` parameter in ``nav2_params.yaml`` for ``glob
"CostmapFilters are Costamp2D plugins. You can enable the `KeepoutFilter` plugin in Costmap2D by adding `keepout_filter` to the `plugins` parameter in `nav2_params.yaml`. You can place it in the `global_costmap` for planning with keepouts and `local_costmap` to make sure the robot won't attempt to drive through a keepout zone. The `KeepoutFilter` plugin should have the following parameters defined:"

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +It is important to note that enabling ``KeepoutFilter`` for ``global_costmap`` only will cause path planner to build path plan bypassing keepout zones. Enabling ``KeepoutFilter`` for ``local_costmap`
"will cause **the** path planner to build plan**s**"

"... will only cause the robot to not enter keepout zones, but the path may still go through them"

Some comment here that the keepout zones don't have to be the same for both would be great.

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +It is important to note that enabling ``KeepoutFilter`` for ``global_costmap`` only will cause path planner to build path plan bypassing keepout zones. Enabling ``KeepoutFilter`` for ``local_costmap`
Why do you have a `/global_costmap` in the namespace for local? You don't have that for `global` and `global` is getting the topic from the main namespace. The semantic info publisher isn't in the `global_costmap` namespace.

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +According to the feature design, map mask is being published along with costmap filter info messages of ``nav2_msgs/msg/CostmapFilterInfo.msg`` type. These messages should be published by Semantic Ma
Link to feature design doc

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +According to the feature design, map mask is being published along with costmap filter info messages of ``nav2_msgs/msg/CostmapFilterInfo.msg`` type. These messages should be published by Semantic Ma
`nav2_msgs/CostmapFilterInfo`

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +According to the feature design, map mask is being published along with costmap filter info messages of ``nav2_msgs/msg/CostmapFilterInfo.msg`` type. These messages should be published by Semantic Ma
Delete anything referencing semantic map server, you're writing the official documentation for using this. Use the tools that are available.

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +According to the feature design, map mask is being published along with costmap filter info messages of ``nav2_msgs/msg/CostmapFilterInfo.msg`` type. These messages should be published by Semantic Ma
This tutorial should be showing how to go from what's available in the nav stack now (no keepout stuff in the launch files, no launch files, no parameters) to using it. So any modifications you make to the nav2 launch files or parameter files **as they exist right now** should be documented here as changes to add / make. This includes adding whatever's in `costmap_filter_info.launch.py` to an existing file with their implementation specific details.

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +  When ``KeepoutFilter`` is enabled for both global and local costmaps, there is no need to duplicate Costmap Filter Info Publisher and mask Map Server instances. Instead of this, leave ``costmap_fil
That is incorrect. Neither of the 2 servers belong to `global_costmap`

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +  ros2 launch nav2_bringup tb3_simulation_launch.py costmap_filters:=True
Remove this `costmap_filters` thing, that doesn't exist. Only have this if your tutorial provides it when you show how to add this capability to the existing files.

2020-09-21 20:17 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +Map mask is the usual ROS map distributed through PGM, PNG or BMP raster file with its metadata YAML file. As an example you can use `keepout_mask.yaml <https://github.com/ros-planning/navigation2/tr
Try rewriting this paragraph, there's enough grammatical errors I'm not really following it. This is the first introduction to this topic you give people, be specific and approachable.

2020-09-21 20:18 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +        base: 0.0
Explain all these values in your tutorial, you haven't really introduced them or why they're used and what they represent.

2020-09-30 20:21 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +It is important to note that enabling ``KeepoutFilter`` for ``global_costmap`` only will cause path planner to build path plan bypassing keepout zones. Enabling ``KeepoutFilter`` for ``local_costmap`
> Some comment here that the keepout zones don't have to be the same for both would be great.

Yes, keepout zones are not mandatory for both layers (local and global) to be at the same place. But I really did not find any use-case of why could they be different for them?

2020-09-30 20:23 UTC, AlexeyMerzlyakov commented
Made an update for documentation & tutorial. Almost all items should be resolved (https://github.com/ros-planning/navigation.ros.org/pull/85#discussion_r497777053 is being discussed). If you are OK with new approach in the tutorial, the only one thing is required to re-take YouTube video and update the link for it.

2020-09-30 21:30 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +It is important to note that enabling ``KeepoutFilter`` for ``global_costmap`` only will cause path planner to build path plan bypassing keepout zones. Enabling ``KeepoutFilter`` for ``local_costmap`
Maybe there's an area you absolutely don't want to plan through, but its not the end of the world if the robot nudges alongside it so you don't want to incur the extra costs of the local costmap copy. So it doesn't let the robot intentionally go there, but if its there, the robot can drive in and out really quick if it clips an edge / corner.

2020-09-30 21:32 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +.. image:: images/Navigation2_with_Keepout_Filter/keepout_global.gif
Still a true statement - I think one of these should be the output of what you tell people to do in the tutorial (start with base pgm and edit it with a keepout area like you show)

2020-09-30 21:33 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +.. image:: images/Navigation2_with_Keepout_Filter/keepout_global.gif
it would be great to update this when you do the video

2020-09-30 21:52 UTC, SteveMacenski requested changes
Super good, small stuff just to clean up.

In the video:
- It would be nice if in the start you showed how you created that annotated file. I can just see the flood of students filing tickets not knowing how to do that.
- Updating it for the changes reflected here

2020-09-30 21:52 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> + - For Keepout Filter ``base`` and ``multiplier`` parameters should be set to ``0.0`` and ``1.0`` accordingly
You didn't explain here what those parameters are / do, I think you should add that equation here to tell people these are used to remap into the different number space

2020-09-30 21:52 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
>  .. _navigation2_with_keepout_filter:
Please pull in the master branch, there's some organizing that changed this PR doesn't use (tutorials were renamed to `general tutorials`)

2020-09-30 21:52 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +Open ``keepout_mask.pgm`` in your favourite raster graphics editor. Each pixel there means an encoded information for the specific costmap filter you are going to use. For Keepout Filter pixel color
An example of a graphics editor would be helpful. I think gimp (?) will do what you want. 

Also, you should let people know what "color" to use, if this is a pgm, then 0 is free, 255 is unknown, and 254 is lethal. You should tell people what to use. Letting people know that this layer can also act as a 'weighted areas layer' as well by setting the cost to higher but non-lethal if they like.

2020-09-30 21:52 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +Open ``keepout_mask.pgm`` in your favourite raster graphics editor. Each pixel there means an encoded information for the specific costmap filter you are going to use. For Keepout Filter pixel color
Most graphics editor tools will let you pick a specific number, and that's good so that they can set the right keepout or amount of cost they like

2020-09-30 21:52 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +According to the feature design, filter mask is being published along with costmap filter info messages of ``nav2_msgs/CostmapFilterInfo`` type. These messages are being published by `Costmap Filter
Remove the first "According to the feature design", since you say it twice and the second time actually has the link.

2020-09-30 21:52 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +  $ ros2 launch launch/costmap_filter_info.launch.py params_file:=params/keepout_params.yaml mask:=maps/keepout_mask.yaml
Please add that launch configuration to the blob example launch file above, so that these are equal

2020-09-30 21:52 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +It is important to note that enabling ``KeepoutFilter`` for ``global_costmap`` only will cause the path planner to build plans bypassing keepout zones. Enabling ``KeepoutFilter`` for ``local_costmap`
Add a note in the next line that the keepout is after the inflation layer so that the keepout boundaries aren't inflated as obstacles

2020-09-30 21:52 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +It is important to note that enabling ``KeepoutFilter`` for ``global_costmap`` only will cause path planner to build path plan bypassing keepout zones. Enabling ``KeepoutFilter`` for ``local_costmap`
eh you know what, people will figure it out if they care, I don't think its worth noting as you say.

2020-10-01 10:37 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_keepout_filter.rst
>  .. _navigation2_with_keepout_filter:
Re-based over latest master. Does this tutorial belong to "General Tutorials" or better to move it to plugins tutorial list? (I think it is better to put it to `general tutorials` since it is not a new plugin invention, rather than using of existing approach).

2020-10-01 12:45 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_keepout_filter.rst
> + - For Keepout Filter ``base`` and ``multiplier`` parameters should be set to ``0.0`` and ``1.0`` accordingly
Previously I've made the following reference:
```
These parameters and their meaning are listed at Map Server / Saver page. Please, refer to it for more information.
```
Is this not enough to not duplicate information in tutorial and configuration page?

2020-10-01 13:25 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +.. image:: images/Navigation2_with_Keepout_Filter/keepout_global.gif
Sorry, that is not clear for me: what should I need with that GIFs: change robot moving scenario, re-take with the keepout in the middle of the map, or add some steps how did I make a PGM from the scratch? If the last one is true - why do I need to put that GIF about PGM creating in the chapter "4. Run Navigation2 stack", not in the "2. Configure Costmap Filter Info Publisher Server" ?

2020-10-01 17:22 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +.. image:: images/Navigation2_with_Keepout_Filter/keepout_global.gif
You created some mask for the map in the step where you show annotations. I think 1 of the 2 gifs should reflect using that filter mask in the simulation you showed yourself creating over the full map. So just swap 1 of the gifs with your differently-sized keepout filter mask with the filter mask you created for the tutorial in step 1.

2020-10-01 17:23 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> + - For Keepout Filter ``base`` and ``multiplier`` parameters should be set to ``0.0`` and ``1.0`` accordingly
I think for this case, it would be good, especially since its only 1 sentence. The main reason I feel that way is because you specifically note that they have to be particular values of 0 and 1, so I think its only fair to give context for what they do if you need them to be some specific value.

2020-10-01 17:24 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
>  .. _navigation2_with_keepout_filter:
General tutorials, the `plugin tutorials` are for `how to write plugins`, but I agree that name might not be immediately obvious.

2020-10-01 17:55 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_keepout_filter.rst
> + - For Keepout Filter ``base`` and ``multiplier`` parameters should be set to ``0.0`` and ``1.0`` accordingly
OK. These items were made in order to highlight some additional circumstances (tuned only for this setup) applied over standard parameters description.

2020-10-01 19:11 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +.. image:: images/Navigation2_with_Keepout_Filter/keepout_global.gif
OK, got it. Changed local costmap gif to a mask file in https://github.com/ros-planning/navigation.ros.org/pull/85/commits/7848af53a14f028ea633fdc26e7a1e92b59f2865.

2020-10-01 19:14 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +Open ``keepout_mask.pgm`` in your favourite raster graphics editor. Each pixel there means an encoded information for the specific costmap filter you are going to use. For Keepout Filter pixel color
Hope, this was improved starting from https://github.com/ros-planning/navigation.ros.org/pull/85/commits/7848af53a14f028ea633fdc26e7a1e92b59f2865#diff-ee85e4992078335301bf3d583dcab890R38 line.

2020-10-01 19:15 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +According to the feature design, filter mask is being published along with costmap filter info messages of ``nav2_msgs/CostmapFilterInfo`` type. These messages are being published by `Costmap Filter
Done: https://github.com/ros-planning/navigation.ros.org/commit/7848af53a14f028ea633fdc26e7a1e92b59f2865#diff-ee85e4992078335301bf3d583dcab890R82

2020-10-01 19:16 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +  $ ros2 launch launch/costmap_filter_info.launch.py params_file:=params/keepout_params.yaml mask:=maps/keepout_mask.yaml
Not sure that copy-paste of whole file will increase readability, but it was made in https://github.com/ros-planning/navigation.ros.org/commit/7848af53a14f028ea633fdc26e7a1e92b59f2865#diff-ee85e4992078335301bf3d583dcab890R88-R192

2020-10-01 19:17 UTC, AlexeyMerzlyakov commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +It is important to note that enabling ``KeepoutFilter`` for ``global_costmap`` only will cause the path planner to build plans bypassing keepout zones. Enabling ``KeepoutFilter`` for ``local_costmap`
Added in here: https://github.com/ros-planning/navigation.ros.org/commit/7848af53a14f028ea633fdc26e7a1e92b59f2865#diff-ee85e4992078335301bf3d583dcab890R239

2020-10-01 19:37 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +It is important to note that enabling ``KeepoutFilter`` for ``global_costmap`` only will cause the path planner to build plans bypassing keepout zones. Enabling ``KeepoutFilter`` for ``local_costmap`
I don't see it.

2020-10-01 19:38 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> +It is important to note that enabling ``KeepoutFilter`` for ``global_costmap`` only will cause the path planner to build plans bypassing keepout zones. Enabling ``KeepoutFilter`` for ``local_costmap`
See it now

2020-10-01 19:38 UTC, SteveMacenski commented on tutorials/docs/navigation2_with_keepout_filter.rst
> + - For Keepout Filter ``base`` and ``multiplier`` parameters should be set to ``0.0`` and ``1.0`` accordingly
I don't see any clarification on the meaning of base and multiplier in the changes

2020-10-01 19:41 UTC, SteveMacenski reviewed
LGTM, just need the update with base / multiplier. You happy to merge once that's in? I think there's the video update as well.

2020-10-01 23:38 UTC, SteveMacenski approved these changes
Merging, please submit a new PR with the video updated link & the base / multiplier stuff. I want to separate them a bit so that its easier to review your next changes and this is good enough for initial public consumption.

2020-10-01 23:38 UTC, merged